import{test,expect}from'@playwright/test';import{readFile,writeFile,mkdir}from'node:fs/promises';import{resolve}from'node:path';import{pathToFileURL}from'node:url';import{createHash}from'node:crypto';
const fixture='examples/browser/blind/cache-response.first.html',expectedHash='1ce5200d24d259a29af160ead40059d96fb2ae5db35145533c6a78e6912e67eb',lock=JSON.parse(await readFile('cdn-lock.json','utf8'));
const states=[[80,100],[0,100],[100,100],[5,100],[37,20],[25,20],[10,50],[2,250],[63,400],[100,400],[0,20]];
test.use({serviceWorkers:'block'});
for(const colorScheme of ['light','dark'])for(const width of [390,1100])test(`unchanged blind cache first draft ${colorScheme} ${width}px: CDN, two inputs, graph and narrative`,async({page})=>{
  expect(createHash('sha256').update(await readFile(fixture)).digest('hex')).toBe(expectedHash);
  await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme});const cdp=await page.context().newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});const responses=[],requests=[],errors=[],blocked=[];cdp.on('Network.responseReceived',({response:r})=>{if(r.url.startsWith('https://cdn.jsdelivr.net/'))responses.push({url:r.url,status:r.status,mime:r.mimeType,fromDiskCache:r.fromDiskCache===true,fromServiceWorker:r.fromServiceWorker===true});});page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>{const u=route.request().url();if(u.startsWith('file:')||[lock.js,lock.css].includes(u))route.continue();else{blocked.push(u);route.abort('blockedbyclient');}});
  await page.goto(pathToFileURL(resolve(fixture)).href);await page.waitForLoadState('networkidle');await expect(page.locator('.iui-root')).toBeVisible();await expect(page.getByRole('heading',{name:'缓存命中率为什么影响平均响应时间？',exact:true})).toBeVisible();await expect(page.locator('math')).toHaveCount(4);await expect(page.locator('.iui-math-error')).toHaveCount(0);await expect(page.locator('input[type=range]')).toHaveCount(2);expect(await page.locator('.iui-root').evaluate(el=>getComputedStyle(el).maxWidth)).toBe('780px');const rootColors=await page.locator('.iui-root').evaluate(el=>({background:getComputedStyle(el).backgroundColor,text:getComputedStyle(el).color,fontSize:getComputedStyle(el).fontSize}));expect(rootColors.background).toBe(colorScheme==='dark'?'rgb(25, 27, 31)':'rgb(255, 255, 255)');expect(parseFloat(rootColors.fontSize)).toBeGreaterThanOrEqual(15);
  const hit=page.getByRole('slider',{name:'缓存命中率',exact:true}),source=page.getByRole('slider',{name:'一次源站访问耗时',exact:true});await expect(source).toHaveAttribute('min','20');await expect(source).toHaveAttribute('max','400');await page.getByText('View chart data',{exact:true}).click();const values=[];
  for(const[h,s]of states){await source.fill(String(s));await hit.fill(String(h));const avg=(500+(100-h)*s)/100,speed=s/avg,threshold=500/s;const metrics=page.locator('.iui-metric-value');await expect(metrics.nth(0)).toHaveText(avg.toFixed(1)+'ms');await expect(metrics.nth(1)).toHaveText(speed.toFixed(2)+'倍');await expect(metrics.nth(2)).toHaveText(threshold.toFixed(2)+'%');const rows=page.locator('.iui-chart table tbody tr');const rawDirect=await rows.nth(0).locator('td').nth(1).textContent(),rawAverage=await rows.nth(1).locator('td').nth(1).textContent();expect(Math.abs(Number(rawDirect)-s)).toBeLessThan(1e-9);expect(Math.abs(Number(rawAverage)-avg)).toBeLessThan(1e-9);const bars=await page.locator('[data-series="response_ms"] rect').evaluateAll(nodes=>nodes.map(n=>({height:Number(n.getAttribute('height')),y:Number(n.getAttribute('y'))})));expect(bars).toHaveLength(2);const axisMax=Math.max(1,s,avg);expect(Math.abs(bars[0].height-190*s/axisMax)).toBeLessThan(1e-8);expect(Math.abs(bars[1].height-190*avg/axisMax)).toBeLessThan(1e-8);const note=page.locator('.iui-text').filter({hasText:/^当前假设下/});await expect(note).toContainText(h*s>500?'降低了':h*s<500?'增加了':'相同');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);values.push({hit:h,source:s,average:avg,speedup:speed,threshold,rawDirect,rawAverage,bars});}
  await page.getByRole('button',{name:'恢复默认教学例子',exact:true}).click();await expect(hit).toHaveValue('80');await expect(source).toHaveValue('100');await expect(page.locator('.iui-metric-value').first()).toHaveText('25.0ms');await page.getByText('教学假设与适用边界',{exact:true}).click();await expect(page.locator('details').last()).toHaveAttribute('open','');expect(errors).toEqual([]);expect(blocked).toEqual([]);expect(requests.filter(u=>u.startsWith('http')).every(u=>[lock.js,lock.css].includes(u))).toBe(true);for(const url of [lock.js,lock.css])expect(responses.some(r=>r.url===url&&r.status===200&&!r.fromDiskCache&&!r.fromServiceWorker)).toBe(true);await mkdir('test-results',{recursive:true});const record={artifactSha256:expectedHash,attempt:'first unchanged',overallAcceptance:'not fully compliant: known raw-less-than escape-rule failure',scopeNote:'equal hit/miss path cost is outside the explicitly declared parameter domain and is not counted as a functional failure',viewport:width,colorScheme,rootColors,states:values,requests,responses,consolePageErrors:errors,blockedRequests:blocked};await writeFile(`test-results/blind-cache-first-${colorScheme}-${width}.json`,JSON.stringify(record,null,2));await page.screenshot({path:`test-results/blind-cache-first-${colorScheme}-${width}.png`,fullPage:true});
});
