import {test,expect} from '@playwright/test';
for(const colorScheme of ['light','dark'])for(const width of [390,768,1100])test(`checklist native state/filter/bulk ${colorScheme} ${width}`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme});await page.goto('/checklist.html');const root=page.locator('.iui-checklist'),checks=root.getByRole('checkbox'),filter=root.getByLabel('显示项目');
 await expect(root.getByRole('status').first()).toContainText('0 / 3');await checks.nth(0).focus();await page.keyboard.press('Space');await expect(checks.nth(0)).toBeChecked();await expect(checks.nth(2)).toBeDisabled();await filter.selectOption('open');await expect(root.locator('[data-item=draft]')).toBeHidden();await checks.nth(0).focus();await page.keyboard.press('Space');await expect(root.locator('[data-item=review]')).toBeHidden();await expect(filter).toBeFocused();await filter.selectOption('all');await root.getByRole('button',{name:'清除可用项目'}).click();await expect(checks.nth(0)).not.toBeChecked();await expect(checks.nth(1)).not.toBeChecked();await root.getByRole('button',{name:'全选可用项目'}).click();await expect(checks.nth(0)).toBeChecked();await expect(checks.nth(1)).toBeChecked();
 const all=root.getByRole('button',{name:'全选可用项目'});await expect(all).toHaveAttribute('aria-disabled','true');await all.focus();await page.keyboard.press('Enter');await expect(all).toBeFocused();await expect(root.locator('output')).toContainText('2 / 3');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/checklist-${colorScheme}-${width}.png`,fullPage:true});
 await page.getByRole('checkbox',{name:'锁定这份清单'}).click();await expect(checks.nth(0)).toBeDisabled();await expect(filter).toBeDisabled();await page.getByRole('button',{name:'恢复全部初值'}).click();await expect(checks.nth(0)).not.toBeChecked();await expect(checks.nth(0)).toBeEnabled();expect(errors).toEqual([]);
});
test.describe('checklist touch',()=>{test.use({hasTouch:true});test('real repeated tap, filter and form cancel preserve native ownership',async({page})=>{
 await page.setViewportSize({width:390,height:900});await page.goto('/checklist-form.html');const root=page.locator('.iui-checklist'),check=root.getByRole('checkbox').nth(0),form=page.getByRole('form');await check.tap();await expect(check).toBeChecked();await check.tap();await expect(check).not.toBeChecked();await root.getByRole('button',{name:'全选可用项目'}).tap();await expect(form).toHaveAttribute('data-status','idle');await page.getByRole('button',{name:'检查并保存本页'}).tap();await expect(form).toHaveAttribute('data-status','success');await page.getByRole('button',{name:'取消并恢复'}).tap();await expect(check).not.toBeChecked();await expect(form).toHaveAttribute('data-status','cancelled');
});});
test('checklist actual RTL/forced colors and atomic rejection retain focus and exact DOM',async({page})=>{
 await page.setViewportSize({width:390,height:900});await page.emulateMedia({forcedColors:'active',reducedMotion:'reduce'});await page.goto('/mount.html');await page.waitForFunction(()=>!!window.iui);await page.evaluate(()=>{document.documentElement.lang='en';window.list=window.iui.mount(document.getElementById('host'),{version:'iui/1',description:'قائمة أصلية للاختبار المحلي.',state:{a:false,b:false},body:[{type:'checklist',label:'قائمة',items:[{id:'a',label:'أول عنصر',bind:'a'},{id:'b',label:'عنصر آخر',bind:'b'}]},{type:'loading',label:'Bound',progress:{op:'if',args:[{$:'a'},101,0]}}]});});const root=page.locator('.iui-checklist');await expect(root).toHaveCSS('direction','rtl');const all=root.getByRole('button',{name:'Select all enabled items'});await all.focus();await page.keyboard.press('Space');await expect(root.locator('.iui-checklist-feedback')).toContainText('rejected');await expect(all).toBeFocused();await expect(root.getByRole('checkbox').nth(0)).not.toBeChecked();await expect(root.getByRole('checkbox').nth(1)).not.toBeChecked();await expect(all).toHaveCSS('outline-style','solid');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/checklist-rtl-forced.png',fullPage:true});
});
