import {test,expect} from '@playwright/test';
// Prepared for combined CI only; no local Chromium execution was performed.
for(const colorScheme of ['light','dark'])for(const width of [390,768,1100])test(`checkbox native activation ${colorScheme} ${width}`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme});await page.goto('/checkbox-practice.html');
 const form=page.getByRole('form',{name:'练习设置'}),check=form.getByRole('checkbox',{name:'启用本次练习'});await expect(check).not.toBeChecked();await expect(check).toHaveAccessibleDescription(/选中后/);
 await form.getByRole('button',{name:'保存设置'}).click();await expect(form).toHaveAttribute('data-status','invalid');await expect(check).toBeFocused();await expect(check).toHaveAttribute('aria-invalid','true');
 await page.keyboard.press('Space');await expect(check).toBeChecked();await expect(check).toHaveAttribute('aria-invalid','false');await form.getByRole('button',{name:'保存设置'}).click();await expect(form).toHaveAttribute('data-status','success');
 await page.locator('label').filter({hasText:'启用本次练习'}).click();await expect(check).not.toBeChecked();await expect(form).toHaveAttribute('data-status','idle');await form.getByRole('button',{name:'恢复初值'}).click();await expect(check).not.toBeChecked();await expect(check).toHaveAttribute('aria-invalid','false');
 const label=page.locator(`label[for="${await check.getAttribute('id')}"]`);expect((await label.boundingBox()).height).toBeGreaterThanOrEqual(44);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);await page.screenshot({path:`test-results/checkbox-${colorScheme}-${width}.png`,fullPage:true});
});
test('checkbox forced colors, RTL, inherited disabled, host overwrite and cleanup',async({page})=>{
 await page.emulateMedia({forcedColors:'active'});await page.goto('/mount.html');await page.waitForFunction(()=>!!window.iui);await page.evaluate(()=>{
 document.documentElement.lang='en';document.documentElement.dir='rtl';window.cb=window.iui.mount(document.querySelector('#host'),{version:'iui/1',description:'مثال أصلي للتحقق من مربعات الاختيار.',state:{checked:false,locked:false},body:[{type:'form',label:'Practice',children:[{type:'field',label:'Group',disabled:{$:'locked'},children:[{type:'input',kind:'checkbox',label:'Practice switch',bind:'checked',required:true}]}]}]});
 });const check=page.getByRole('checkbox',{name:'Practice switch'});await expect(page.locator('.iui-field-checkbox')).toHaveCSS('direction','rtl');await check.focus();await page.keyboard.press('Space');await expect(check).toBeChecked();await page.evaluate(()=>window.cb.setState({locked:true}));await expect(check).toBeDisabled();await page.getByRole('button',{name:'Submit',exact:true}).click();await expect(page.getByRole('form')).toHaveAttribute('data-status','success');await page.evaluate(()=>window.cb.setState({checked:false,locked:false}));await expect(check).not.toBeChecked();await check.focus();await page.keyboard.press('Space');await expect(check).toHaveCSS('outline-style','solid');await page.evaluate(()=>window.cb.dispose());await expect(page.locator('#host')).toBeEmpty();
});
