import{test,expect}from'@playwright/test';import{readFile,writeFile}from'node:fs/promises';
const tokens=JSON.parse(await readFile(new URL('../../docs/color-tokens.json',import.meta.url)));
for(const theme of ['light','dark'])for(const width of [390,1100])test(`semantic color roles ${theme} ${width}: computed values and actual elements`,async({page})=>{
 await page.setViewportSize({width,height:1000});await page.emulateMedia({colorScheme:theme});await page.goto('/colors.html');const root=page.locator('.iui-root');await root.evaluate((el,t)=>el.dataset.theme=t,theme);
 const actual=await root.evaluate((el,names)=>Object.fromEntries(names.map(name=>[name,getComputedStyle(el).getPropertyValue('--iui-'+name).trim()])),Object.keys(tokens[theme]));expect(actual).toEqual(tokens[theme]);
 const colors=await page.evaluate(()=>{const style=s=>getComputedStyle(document.querySelector(s));return{link:style('.iui-root a').color,info:style('[data-color=info]').color,accent:style('[data-color=accent]').color,success:style('[data-color=success]').color,danger:style('[data-color=danger]').color,warning:style('[data-color=warning]').color,background:style('.iui-root').backgroundColor,selected:style('input[type=range]').accentColor,disabled:style('input:disabled').color,disabledBackground:style('input:disabled').backgroundColor,series:[...document.querySelectorAll('[data-series] path')].map(p=>getComputedStyle(p).stroke)};});
 expect(colors.link).toBe(theme==='light'?'rgb(51, 156, 255)':'rgb(153, 206, 255)');expect(colors.info).toBe(theme==='light'?'rgb(1, 105, 204)':'rgb(102, 181, 255)');expect(colors.accent).toBe(colors.link);expect(colors.selected).toBe('rgb(2, 133, 255)');expect(colors.disabled).toBe(theme==='light'?'rgb(143, 143, 143)':'rgb(93, 93, 93)');expect(colors.series[0]).toBe('rgb(51, 156, 255)');expect(new Set(colors.series).size).toBe(6);
 const range=page.getByRole('slider');await range.focus();await page.keyboard.press('ArrowRight');expect(await range.evaluate(e=>getComputedStyle(e).outlineColor)).toBe(theme==='light'?'rgb(1, 105, 204)':'rgb(2, 133, 255)');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await writeFile(`test-results/colors-${theme}-${width}.json`,JSON.stringify({theme,width,tokens:actual,elements:colors},null,2));await page.screenshot({path:`test-results/colors-${theme}-${width}.png`,fullPage:true});
 // Explicit light stays light even under dark OS; auto chooses the same dark token set.
 await page.emulateMedia({colorScheme:'dark'});await root.evaluate(e=>e.dataset.theme='auto');expect(await root.evaluate(e=>getComputedStyle(e).getPropertyValue('--iui-link').trim())).toBe(tokens.dark.link);await root.evaluate(e=>e.dataset.theme='light');expect(await root.evaluate(e=>getComputedStyle(e).getPropertyValue('--iui-link').trim())).toBe(tokens.light.link);
});
