import{test,expect}from'@playwright/test';import{readFile,writeFile}from'node:fs/promises';import{createHash}from'node:crypto';import{pathToFileURL}from'node:url';import{resolve}from'node:path';
const lock=JSON.parse(await readFile('cdn-lock.json','utf8')),allowed=[lock.js,lock.css,lock.schema,...Object.keys(lock.integrity).filter(n=>n.endsWith('.woff2')).map(n=>new URL(n,lock.css).href)];
test.use({serviceWorkers:'block'});
for(const theme of ['light','dark'])for(const width of [390,768,1100])test(`converter actual CDN ${theme} ${width}: units snapshots and local keyboard controls`,async({page})=>{
 await page.setViewportSize({width,height:1000});await page.emulateMedia({colorScheme:theme});const cdp=await page.context().newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});
 const transport=[],requests=[],errors=[],assets={},pending=[];cdp.on('Network.responseReceived',({response:r})=>{if(allowed.includes(r.url))transport.push({url:r.url,status:r.status,disk:r.fromDiskCache===true,worker:r.fromServiceWorker===true,mime:r.mimeType});});
 page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>errors.push(r.url()+': '+r.failure()?.errorText));await page.route('**/*',r=>r.request().url().startsWith('file:')||allowed.includes(r.request().url())?r.continue():r.abort());
 page.on('response',r=>{if(allowed.includes(r.url()))pending.push((async()=>{const b=await r.body();assets[r.url()]={status:r.status(),sha256:createHash('sha256').update(b).digest('hex'),headers:await r.allHeaders()};})());});
 await page.goto(pathToFileURL(resolve('examples/browser/converters-preview.html')).href);await expect(page.locator('#status')).toBeEmpty();const units=page.locator('[data-kind="unit-converter"]'),temperature=units.first(),currency=page.locator('[data-kind="currency-converter"]'),control=(root,name)=>root.locator(`[data-converter-control="${name}"]`);
 await expect(units).toHaveCount(2);await expect(temperature.locator('output')).toHaveText('18 Δ°F');await control(temperature,'amount').fill('20');await expect(temperature.locator('output')).toHaveText('36 Δ°F');await control(temperature,'mode').selectOption('absolute');await control(temperature,'amount').fill('0');await expect(temperature.locator('output')).toHaveText('32 °F');
 await temperature.getByRole('button',{name:'恢复初始换算设置'}).focus();await page.keyboard.press('Enter');await expect(temperature.locator('output')).toHaveText('18 Δ°F');await expect(units.nth(1).locator('output')).toHaveText('1.048576 MB');
 await expect(currency.locator('output')).toHaveText('80 EUR');await control(currency,'to').selectOption('GBP');await expect(currency.locator('output')).toHaveText('—');await control(currency,'amount').fill('0');await expect(currency.locator('output')).toHaveText('—');await control(currency,'to').selectOption('EUR');await expect(currency.locator('output')).toHaveText('0 EUR');await currency.getByRole('button',{name:'恢复初始换算设置'}).click();await expect(currency.locator('output')).toHaveText('80 EUR');
 await currency.locator('summary').focus();await page.keyboard.press('Enter');await expect(currency.locator('table')).toBeVisible();await expect(currency.locator('tbody tr')).toHaveCount(4);await expect(currency.locator('footer')).toContainText('Inform UI');await expect(currency.locator('footer')).toContainText('合成演示');
 const schema=await page.evaluate(async url=>{const r=await fetch(url,{cache:'no-store'});return{status:r.status,count:(await r.json()).$defs.Node.oneOf.length};},lock.schema);expect(schema).toEqual({status:200,count:52});await page.waitForLoadState('networkidle');await Promise.all(pending);
 expect(await page.locator('.iui-root style').count()).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);expect(requests.filter(u=>u.startsWith('http')).every(u=>allowed.includes(u))).toBe(true);
 for(const url of [lock.js,lock.css,lock.schema]){const name=new URL(url).pathname.split('/cdn/')[1];expect(assets[url]?.status).toBe(200);expect(assets[url].sha256).toBe(lock.integrity[name].sha256);expect(assets[url].headers['access-control-allow-origin']).toBe('*');expect(transport.some(r=>r.url===url&&r.status===200&&!r.disk&&!r.worker)).toBe(true);}
 await writeFile(`test-results/converters-cdn-${theme}-${width}.json`,JSON.stringify({commit:lock.commit,transport,requests,errors,assets,schema},null,2));await page.screenshot({path:`test-results/converters-cdn-${theme}-${width}.png`,fullPage:true});
});
