import{test,expect}from'@playwright/test';import{readFile,writeFile}from'node:fs/promises';import{createHash}from'node:crypto';import{pathToFileURL}from'node:url';import{resolve}from'node:path';
const lock=JSON.parse(await readFile('cdn-lock.json','utf8')),allowed=[lock.js,lock.css,...Object.keys(lock.integrity).filter(n=>n.endsWith('.woff2')).map(n=>new URL(n,lock.css).href)];test.use({serviceWorkers:'block'});
for(const theme of ['light','dark'])for(const width of [390,768,1100])test(`domains actual CDN ${theme} ${width}: sports and learning with fresh fixed assets`,async({page})=>{
 await page.setViewportSize({width,height:950});await page.emulateMedia({colorScheme:theme});const cdp=await page.context().newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});const transport=[],requests=[],errors=[],assets={},pending=[];cdp.on('Network.responseReceived',({response:r})=>{if(allowed.includes(r.url))transport.push({url:r.url,status:r.status,disk:r.fromDiskCache===true,worker:r.fromServiceWorker===true,mime:r.mimeType});});page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>errors.push(r.url()+': '+r.failure()?.errorText));await page.route('**/*',r=>r.request().url().startsWith('file:')||allowed.includes(r.request().url())?r.continue():r.abort());page.on('response',r=>{if(allowed.includes(r.url()))pending.push((async()=>{const b=await r.body();assets[r.url()]={status:r.status(),sha256:createHash('sha256').update(b).digest('hex'),headers:await r.allHeaders()};})());});
 await page.goto(pathToFileURL(resolve('examples/browser/domains-preview.html')).href);await expect(page.locator('#status')).toBeEmpty();const root=page.locator('.iui-root'),schedule=page.locator('.iui-sports-schedule'),standings=page.locator('.iui-sports-standings'),quiz=page.locator('.iui-quiz'),cards=page.locator('.iui-flashcards');await expect(root).toBeVisible();expect(await root.evaluate(e=>getComputedStyle(e).getPropertyValue('--iui-series-blue').trim())).toBe('#339cff');expect(await root.evaluate(e=>getComputedStyle(e).getPropertyValue('--iui-link').trim())).toBe(theme==='light'?'#339cff':'#99ceff');
 await schedule.locator('[data-sports-filter="team"]').selectOption({label:'天琴队'});await expect(schedule.locator('[data-game-id]')).toHaveCount(2);await standings.locator('[data-sort-key="points"]').click();expect(await standings.locator('tbody tr').evaluateAll(rows=>rows.map(r=>r.dataset.teamId))).toEqual(['a','b','c','d']);
 await quiz.getByRole('radio',{name:'30 ms',exact:true}).check();await quiz.getByRole('button',{name:'确认答案'}).click();await quiz.getByRole('button',{name:'下一题'}).click();await expect(quiz.locator('h3')).toBeFocused();await quiz.getByRole('checkbox').nth(0).check();await quiz.getByRole('checkbox').nth(1).check();await quiz.getByRole('button',{name:'确认答案'}).click();await quiz.getByRole('button',{name:'查看结果'}).click();await expect(quiz.locator('.iui-learning-score')).toHaveText('得分: 5 / 5');await cards.getByRole('button',{name:'查看答案'}).focus();await page.keyboard.press('Enter');await cards.getByRole('button',{name:'已掌握',exact:true}).click();await expect(cards.locator('progress')).toHaveAttribute('value','1');await expect(cards.locator('.katex')).toHaveCount(1);
 await page.waitForLoadState('networkidle');await page.evaluate(()=>document.fonts.ready);await Promise.all(pending);expect(await root.locator('style').count()).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);expect(requests.filter(u=>u.startsWith('http')).every(u=>allowed.includes(u))).toBe(true);for(const url of [lock.js,lock.css]){const name=new URL(url).pathname.split('/cdn/')[1];expect(assets[url]?.status).toBe(200);expect(assets[url].sha256).toBe(lock.integrity[name].sha256);expect(assets[url].headers['access-control-allow-origin']).toBe('*');expect(transport.some(r=>r.url===url&&r.status===200&&!r.disk&&!r.worker)).toBe(true);}await writeFile(`test-results/domains-cdn-${theme}-${width}.json`,JSON.stringify({commit:lock.commit,transport,requests,errors,assets},null,2));await page.screenshot({path:`test-results/domains-cdn-${theme}-${width}.png`,fullPage:true});
});
