// PREPARED, UNEXECUTED: owner runs these in the grouped browser acceptance batch.
// Clipboard assertions use explicit local writeText STUBS, never the OS Clipboard.
// Native pointer, keyboard and touch input remain genuine Playwright interactions.
import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {compileHtml} from '../../dist/index.js';
const mail=JSON.parse(await readFile(new URL('../../examples/email-draft.json',import.meta.url),'utf8'));
const tasks=JSON.parse(await readFile(new URL('../../examples/task-expansion-card.json',import.meta.url),'utf8'));
const fixture={version:'iui/1',state:{count:0,locked:false},body:[mail.body[0],tasks.body[0]]};
const email=page=>page.locator('[data-iui=email-draft]'),plan=page=>page.locator('[data-iui=task-expansion-card]');
const copy=page=>email(page).locator('[data-writing-action=copy]'),select=page=>email(page).locator('[data-writing-action=select]'),reset=page=>plan(page).getByRole('button',{name:'Reset review marks'});
const original=mail.body[0].body.replace(/\r\n?/g,'\n');
async function mount(page,input=fixture,lang='en'){
 await page.goto('/mount.html');await page.waitForFunction(()=>Boolean(window.iui));
 await page.evaluate(({input,lang})=>{const host=document.getElementById('host');host.lang=lang;window.draftReviewInput=input;window.draftReview=window.iui.mount(host,input);},{input,lang});
}
async function pointer(page,target){await target.scrollIntoViewIfNeeded();const box=await target.boundingBox();expect(box).not.toBeNull();const p={x:box.x+box.width/2,y:box.y+box.height/2};expect(await target.evaluate((node,p)=>node.contains(node.ownerDocument.elementFromPoint(p.x,p.y)),p)).toBe(true);await page.mouse.click(p.x,p.y);}
async function clipboardStub(page){await page.evaluate(()=>{window.reviewWrites=[];window.reviewCopies=[];Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText(value){window.reviewWrites.push(value);return new Promise((resolve,reject)=>window.reviewCopies.push({resolve,reject}));}}});});}
async function settle(page,kind='resolve',index=0){await page.evaluate(({kind,index})=>window.reviewCopies[index][kind](kind==='reject'?Error('Denied'):undefined),{kind,index});}
test.beforeEach(async({page})=>{page.__reviewErrors=[];page.on('pageerror',error=>page.__reviewErrors.push(error.message));});
test.afterEach(async({page})=>expect(page.__reviewErrors).toEqual([]));
for(const theme of ['light','dark'])for(const width of [390,768,1100])test(`review cards ${theme} ${width}: native editing/checking/disclosure, wrapping and local identity`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});await page.emulateMedia({colorScheme:theme,reducedMotion:'reduce'});const input=structuredClone(fixture);input.theme=theme;input.body[0].to.push('long-address-'.repeat(20)+'@example.invalid');await mount(page,input);
 const text=email(page).getByRole('textbox',{name:'Message body'});await expect(text).toHaveValue(original);await text.focus();await page.keyboard.press('End');await page.keyboard.type(' Local edit.');const edited=await text.inputValue();expect(edited).not.toBe(original);
 await pointer(page,select(page));await expect(text).toBeFocused();expect(await text.evaluate(node=>[node.selectionStart,node.selectionEnd])).toEqual([0,edited.length]);
 const check=plan(page).getByRole('checkbox').nth(1);await check.focus();await page.keyboard.press('Space');await expect(check).toBeChecked();await expect(plan(page).getByRole('status')).toHaveText('2 of 3 steps marked reviewed');await expect(check).toBeFocused();
 const summary=plan(page).locator('summary').first();await pointer(page,summary);await expect(plan(page).locator('details').first()).toHaveAttribute('open','');
 await check.focus();await page.evaluate(()=>{window.reviewCheck=document.querySelectorAll('.iui-task-expansion-card input')[1];window.draftReview.setState({count:2});});await expect(check).toBeFocused();expect(await check.evaluate(node=>node===window.reviewCheck)).toBe(true);
 await pointer(page,reset(page));await expect(check).not.toBeChecked();await expect(plan(page).locator('details').first()).toHaveAttribute('open','');await expect(text).toHaveValue(edited);await expect(reset(page)).toHaveAttribute('aria-disabled','true');await pointer(page,reset(page));await expect(plan(page).getByRole('status')).toHaveText('1 of 3 steps marked reviewed');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath(`review-${theme}-${width}.png`),fullPage:true});
});
test('STUB: trusted keyboard/pointer Copy preserves body-only payload, single flight and stale status',async({page})=>{
 await mount(page);await clipboardStub(page);const text=email(page).getByRole('textbox');await text.fill('Only current body 😀');await copy(page).focus();await page.keyboard.press('Enter');await pointer(page,copy(page));await copy(page).evaluate(node=>node.click());expect(await page.evaluate(()=>window.reviewWrites)).toEqual(['Only current body 😀']);await expect(copy(page)).toHaveAttribute('aria-disabled','true');
 await text.fill('Newer body');await settle(page);await expect(email(page).getByRole('status')).toContainText('earlier version');await pointer(page,copy(page));await settle(page,'reject',1);await expect(email(page).getByRole('status')).toContainText('Select the text');await pointer(page,select(page));await expect(text).toBeFocused();expect(await text.evaluate(node=>[node.selectionStart,node.selectionEnd])).toEqual([0,'Newer body'.length]);
});
test('invalid update is atomic; valid replacement and disposal stop retired native controls and pending Copy',async({page})=>{
 await mount(page);await clipboardStub(page);const text=email(page).getByRole('textbox');await text.fill('Keep local');await plan(page).getByRole('checkbox').nth(1).check();await pointer(page,copy(page));
 await page.evaluate(()=>{window.retiredEmail=document.querySelector('.iui-email-draft');const bad=structuredClone(window.draftReviewInput);bad.body[0].send=true;try{window.draftReview.update(bad);}catch{window.reviewInvalid=true;}});expect(await page.evaluate(()=>window.reviewInvalid)).toBe(true);await expect(text).toHaveValue('Keep local');await expect(plan(page).getByRole('checkbox').nth(1)).toBeChecked();
 await page.evaluate(()=>window.draftReview.update(window.draftReviewInput));await settle(page);await expect(email(page).getByRole('status')).toHaveText('');await expect(text).toHaveValue(original);await expect(plan(page).getByRole('checkbox').nth(1)).not.toBeChecked();expect(await page.evaluate(()=>window.retiredEmail.isConnected)).toBe(false);await page.evaluate(()=>window.draftReview.dispose());await expect(page.locator('#host')).toBeEmpty();
});
test('external disabled fieldset blocks native controls and real pointer/forged email/plan changes',async({page})=>{
 await mount(page);await email(page).getByRole('textbox').fill('Kept body');await plan(page).getByRole('checkbox').nth(1).check();await page.evaluate(()=>{const host=document.getElementById('host'),fieldset=document.createElement('fieldset');host.before(fieldset);fieldset.append(host);fieldset.disabled=true;window.reviewExternal=fieldset;});
 await expect(email(page).getByRole('textbox')).toBeDisabled();const check=plan(page).getByRole('checkbox').nth(1);await expect(check).toBeDisabled();await pointer(page,reset(page));await page.evaluate(()=>{const input=document.querySelectorAll('.iui-task-expansion-card input')[1];input.checked=false;input.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('.iui-task-review-reset').dispatchEvent(new MouseEvent('click',{bubbles:true}));const draft=document.querySelector('.iui-writing-draft');draft.value='Forged';draft.dispatchEvent(new Event('input',{bubbles:true}));});
 await expect(check).toBeChecked();await expect(email(page).getByRole('textbox')).toHaveValue('Kept body');await page.evaluate(()=>window.reviewExternal.disabled=false);await pointer(page,reset(page));await expect(check).not.toBeChecked();
});
test('plan own disabled state and pending Forms guard native changes, omit review flags from snapshot',async({page})=>{
 const input={version:'iui/1',state:{other:'value',count:0,locked:false},body:[{type:'form',label:'Local host form',action:'save',children:[{type:'input',kind:'text',label:'Other',bind:'other'},tasks.body[0]]}]};await mount(page,input);
 await page.evaluate(()=>{window.draftReview.dispose();window.draftReview=window.iui.mount(document.getElementById('host'),window.draftReviewInput,{actions:{save:({values})=>{window.reviewSnapshot=values;return new Promise(resolve=>window.reviewResolve=resolve);}}});});
 const check=plan(page).getByRole('checkbox').nth(1);await check.check();await page.evaluate(()=>window.draftReview.setState({locked:true}));await expect(check).toBeDisabled();await page.evaluate(()=>window.draftReview.setState({locked:false}));await page.getByRole('button',{name:'Submit',exact:true}).click();await expect(check).toBeDisabled();expect(await page.evaluate(()=>window.reviewSnapshot)).toEqual({other:'value'});await pointer(page,reset(page));await expect(check).toBeChecked();await page.evaluate(()=>window.reviewResolve());await expect(check).toBeEnabled();await reset(page).click();await expect(check).not.toBeChecked();
});
test('external native form reset preserves local body/review state; component controls never submit',async({page})=>{
 await mount(page);await page.evaluate(()=>{const host=document.getElementById('host'),form=document.createElement('form'),input=document.createElement('input');input.defaultValue='original';input.id='review-other';input.name='other';host.before(form);form.append(input,host);form.id='review-outer';window.reviewSubmits=0;form.addEventListener('submit',event=>{event.preventDefault();window.reviewSubmits++;});});
 await email(page).getByRole('textbox').fill('retained');await plan(page).getByRole('checkbox').nth(1).check();await page.evaluate(()=>document.getElementById('review-outer').reset());await expect(email(page).getByRole('textbox')).toHaveValue('retained');await expect(plan(page).getByRole('checkbox').nth(1)).toBeChecked();await page.locator('#review-other').fill('independent');await reset(page).click();await select(page).click();await expect(page.locator('#review-other')).toHaveValue('independent');expect(await page.evaluate(()=>window.reviewSubmits)).toBe(0);expect(await page.evaluate(()=>[...new FormData(document.getElementById('review-outer')).keys()])).toEqual(['other']);
});
test('Arabic-first local text, Chinese UI, forced colors and genuine visible keyboard focus',async({page})=>{
 await page.setViewportSize({width:390,height:1000});await page.emulateMedia({forcedColors:'active',reducedMotion:'reduce'});const input=structuredClone(fixture);Object.assign(input.body[0],{label:'مسودة محلية',subject:'موضوع عربي',body:'هذا نص عربي\nسطر جديد'});Object.assign(input.body[1],{title:'خطة عربية',summary:'قراءة النص لا تعني تنفيذ المهمة'});input.body[1].steps[0].title='اقرأ الخطوة';await mount(page,input,'zh-CN');
 const text=email(page).getByRole('textbox',{name:'邮件正文'});expect(await text.evaluate(node=>getComputedStyle(node).direction)).toBe('rtl');await text.focus();await page.keyboard.press('Tab');await expect(copy(page)).toBeFocused();expect(await copy(page).evaluate(node=>getComputedStyle(node).outlineStyle)).toBe('solid');const check=plan(page).getByRole('checkbox').first();await check.focus();await page.keyboard.press('Space');await expect(check).not.toBeChecked();expect(await check.evaluate(node=>getComputedStyle(node).outlineStyle)).toBe('solid');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('offline compiler hydration creates the local controls with no external requests',async({page})=>{const html=await compileHtml(fixture),requests=[];page.on('request',request=>requests.push(request.url()));await page.context().setOffline(true);await page.setContent(html);await expect(email(page).getByRole('textbox')).toHaveValue(original);await plan(page).getByRole('checkbox').nth(1).check();await expect(plan(page).getByRole('status')).toHaveText('2 of 3 steps marked reviewed');expect(requests).toEqual([]);});
test.describe('touch prepared acceptance',()=>{
 test.use({hasTouch:true,viewport:{width:390,height:1000}});
 test('STUB: real taps review/disclose/reset and copy only the current body',async({page})=>{await mount(page);await clipboardStub(page);const check=plan(page).getByRole('checkbox').nth(1),label=plan(page).locator('.iui-task-review-check').nth(1);await label.tap();await expect(check).toBeChecked();await plan(page).locator('summary').first().tap();await expect(plan(page).locator('details').first()).toHaveAttribute('open','');await reset(page).tap();await expect(check).not.toBeChecked();await copy(page).tap();expect(await page.evaluate(()=>window.reviewWrites)).toEqual([original]);await settle(page);await select(page).tap();await expect(email(page).getByRole('textbox')).toBeFocused();});
});
