import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const icon=await readFile(new URL('../fixtures/favicon-original.png',import.meta.url));
const remote='https://example.invalid/supplied-icon.png';
for(const colorScheme of ['light','dark'])for(const width of [390,768,1100])test(`favicon consent and local fallback ${colorScheme} ${width}`,async({page})=>{
 const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url()===remote)requests.push(r.url());});await page.route(remote,route=>route.fulfill({status:200,contentType:'image/png',body:icon}));await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme});await page.goto('/favicon.html');
 const roots=page.locator('.iui-favicon'),external=roots.nth(3);await expect(roots.nth(1)).toHaveAttribute('data-state','loaded');await expect(external.locator('img')).toHaveCount(0);expect(requests).toEqual([]);const button=external.getByRole('button');await expect(button).toHaveAccessibleName('加载图标');await button.evaluate(el=>window.originalFaviconLoad=el);await button.focus();await page.keyboard.press('Enter');await expect(external).toHaveAttribute('data-state','loaded');expect(requests).toEqual([remote]);await expect(button).toHaveAccessibleName('已加载所提供的图标。');expect(await button.evaluate(el=>el===window.originalFaviconLoad)).toBe(true);await expect(button).toBeFocused();await page.keyboard.press('Space');expect(requests).toEqual([remote]);await expect(button).toHaveAttribute('aria-disabled','true');
 await page.getByRole('button',{name:'仅更新其他状态'}).click();expect(requests).toEqual([remote]);await expect(external).toHaveAttribute('data-state','loaded');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);for(const [i,size] of [24,32,48].entries()){const box=await roots.nth(i).locator('.iui-favicon-visual').boundingBox();expect(box.width).toBe(size);expect(box.height).toBe(size);}await page.screenshot({path:`test-results/favicon-${colorScheme}-${width}.png`,fullPage:true});expect(errors).toEqual([]);
});
test('favicon error and explicit native retry keep focus, dimensions and no eager requests',async({page})=>{
 let calls=0;await page.route(remote,route=>{calls++;return calls===1?route.fulfill({status:404,body:'not an icon'}):route.fulfill({status:200,contentType:'image/png',body:icon});});await page.goto('/favicon.html');const root=page.locator('.iui-favicon').nth(3),button=root.getByRole('button');expect(calls).toBe(0);const before=await root.locator('.iui-favicon-visual').boundingBox();await button.click();await expect(root).toHaveAttribute('data-state','error');await expect(root.locator('.iui-favicon-fallback')).toBeVisible();await expect(button).toBeFocused();await expect(button).toHaveText('重试图标');await button.click();await expect(root).toHaveAttribute('data-state','loaded');expect(calls).toBe(2);const after=await root.locator('.iui-favicon-visual').boundingBox();expect(after.width).toBe(before.width);expect(after.height).toBe(before.height);
});
test.describe('favicon touch',()=>{test.use({hasTouch:true});test('touch load repeated activation cannot duplicate a pending request',async({page})=>{
 let release,seen=0;const held=new Promise(resolve=>release=resolve);await page.route(remote,async route=>{seen++;await held;await route.fulfill({status:200,contentType:'image/png',body:icon});});await page.setViewportSize({width:390,height:900});await page.goto('/favicon.html');const root=page.locator('.iui-favicon').nth(3),button=root.getByRole('button');await button.tap();await expect(root).toHaveAttribute('data-state','loading');const b=await button.boundingBox();const point={x:b.x+b.width/2,y:b.y+b.height/2};expect(await button.evaluate((el,p)=>el.contains(el.ownerDocument.elementFromPoint(p.x,p.y)),point)).toBe(true);await page.touchscreen.tap(point.x,point.y);await expect.poll(()=>seen).toBe(1);release();await expect(root).toHaveAttribute('data-state','loaded');expect(seen).toBe(1);
});});
test('favicon actual RTL, forced colors, disabled ancestor and atomic lifecycle',async({page})=>{
 await page.setViewportSize({width:390,height:900});await page.emulateMedia({forcedColors:'active'});await page.goto('/mount.html');await page.waitForFunction(()=>!!window.iui);await page.evaluate(()=>{document.documentElement.lang='en';window.favSpec={version:'iui/1',description:'أيقونة أصلية للاختبار.',state:{locked:true},body:[{type:'form',label:'Outer',disabled:{$:'locked'},children:[{type:'favicon',label:'المصدر',fallback:'م',src:'https://example.invalid/supplied-icon.png'}]}]};window.fav=window.iui.mount(document.getElementById('host'),window.favSpec);});const root=page.locator('.iui-favicon'),button=root.getByRole('button');await expect(root).toHaveCSS('direction','rtl');await expect(button).toBeDisabled();await page.evaluate(()=>window.fav.setState({locked:false}));await button.focus();await expect(button).toHaveCSS('outline-style','solid');await page.evaluate(()=>{const bad=structuredClone(window.favSpec);bad.body[0].children[0].src='javascript:bad()';try{window.fav.update(bad);}catch{window.rejected=true;}});expect(await page.evaluate(()=>window.rejected)).toBe(true);await expect(button).toBeFocused();await expect(root.locator('img')).toHaveCount(0);await page.screenshot({path:'test-results/favicon-rtl-forced.png',fullPage:true});await page.evaluate(()=>window.fav.dispose());await expect(page.locator('#host')).toBeEmpty();
});
