// Prepared only. Native action suppression plus explicit forged-event/lifecycle probes.
import {test,expect} from '@playwright/test';
const input={version:'iui/1',state:{note:'original'},body:[{type:'form',label:'Guarded form',action:'save',children:[{type:'input',kind:'text',label:'Note',bind:'note'}]}]};
async function setup(page,pending=false){await page.goto('/mount.html');await page.waitForFunction(()=>!!window.iui);await page.evaluate(({input,pending})=>{
 const host=document.getElementById('host'),outer=document.createElement('fieldset'),before=document.createElement('button'),after=document.createElement('button');outer.id='outer';before.id='before';after.id='after';before.textContent='Before';after.textContent='After';host.before(before,outer);outer.append(host);outer.after(after);window.guardCalls=[];window.guardEvents=[];
 host.addEventListener('iui:submit',e=>window.guardEvents.push(e.detail));window.formGuard=window.iui.mount(host,input,{actions:{save:({values,signal})=>{window.guardCalls.push(values);window.guardSignal=signal;if(pending)return new Promise(resolve=>window.guardResolve=resolve);}}});
},{input,pending});}
async function pointer(page,target,touch=false){await target.scrollIntoViewIfNeeded();const box=await target.boundingBox();expect(box).not.toBeNull();const point={x:box.x+box.width/2,y:box.y+box.height/2};expect(await target.evaluate((el,p)=>el.contains(el.ownerDocument.elementFromPoint(p.x,p.y)),point)).toBe(true);if(touch)await page.touchscreen.tap(point.x,point.y);else await page.mouse.click(point.x,point.y);}
for(const touch of [false,true])test.describe(touch?'touch inherited boundary':'pointer inherited boundary',()=>{if(touch)test.use({hasTouch:true});test('disabled native actions stay inert, Tab skips them and re-enabled controls recover',async({page})=>{
 await setup(page);const form=page.getByRole('form',{name:'Guarded form'}),note=form.getByRole('textbox'),submit=form.getByRole('button',{name:'Submit',exact:true}),cancel=form.getByRole('button',{name:'Cancel',exact:true});await note.fill('edited');await page.evaluate(()=>document.getElementById('outer').disabled=true);await expect(submit).toBeDisabled();await expect(cancel).toBeDisabled();await pointer(page,submit,touch);await pointer(page,cancel,touch);await page.locator('#before').focus();await page.keyboard.press('Tab');await expect(page.locator('#after')).toBeFocused();
 await page.evaluate(()=>{const form=document.querySelector('form');form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));document.querySelector('.iui-form-actions button[type=button]').dispatchEvent(new MouseEvent('click',{bubbles:true}));form.reset();});expect(await page.evaluate(()=>window.guardCalls)).toEqual([]);await expect(note).toHaveValue('edited');await expect(form).toHaveAttribute('data-status','idle');expect(await page.evaluate(()=>window.guardEvents)).toEqual([]);
 await page.evaluate(()=>document.getElementById('outer').disabled=false);await pointer(page,submit,touch);await expect(form).toHaveAttribute('data-status','success');expect(await page.evaluate(()=>window.guardCalls)).toEqual([{note:'edited'}]);await cancel.focus();await page.keyboard.press('Space');await expect(note).toHaveValue('original');await expect(form).toHaveAttribute('data-status','cancelled');await expect(cancel).toBeFocused();
});});
test('pending outer disable blocks Cancel until enabled; native Cancel aborts and ignores late resolution',async({page})=>{
 await setup(page,true);const form=page.getByRole('form',{name:'Guarded form'}),note=form.getByRole('textbox'),submit=form.getByRole('button',{name:'Submit',exact:true}),cancel=form.getByRole('button',{name:'Cancel',exact:true});await note.fill('edited');await submit.click();await expect(form).toHaveAttribute('aria-busy','true');await page.evaluate(()=>document.getElementById('outer').disabled=true);await pointer(page,cancel);await page.evaluate(()=>{document.querySelector('.iui-form-actions button[type=button]').dispatchEvent(new MouseEvent('click',{bubbles:true}));document.querySelector('form').reset();});expect(await page.evaluate(()=>window.guardSignal.aborted)).toBe(false);await expect(note).toHaveValue('edited');
 await page.evaluate(()=>document.getElementById('outer').disabled=false);await cancel.focus();await page.keyboard.press('Space');expect(await page.evaluate(()=>window.guardSignal.aborted)).toBe(true);await expect(form).toHaveAttribute('data-status','cancelled');await page.evaluate(async()=>{window.guardResolve();await Promise.resolve();await Promise.resolve();});await expect(form).toHaveAttribute('data-status','cancelled');expect(await page.evaluate(()=>window.guardCalls.length)).toBe(1);expect(await page.evaluate(()=>window.guardEvents)).toEqual([]);
});
test('real click with a synchronous adapter getter replacement never launches retired work',async({page})=>{
 await setup(page);await page.evaluate(input=>{window.formGuard.dispose();window.guardCalls=[];window.retired=null;const actions={get save(){window.retired=document.querySelector('form');window.retiredHTML=window.retired.outerHTML;window.formGuard.update(input);return()=>window.guardCalls.push('must not run');}};window.formGuard=window.iui.mount(document.getElementById('host'),input,{actions});},input);
 await page.getByRole('button',{name:'Submit',exact:true}).click();expect(await page.evaluate(()=>window.guardCalls)).toEqual([]);expect(await page.evaluate(()=>window.retired.outerHTML===window.retiredHTML)).toBe(true);await expect(page.getByRole('form',{name:'Guarded form'})).toHaveAttribute('data-status','idle');
});
