import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';
const fixture=JSON.parse(await readFile(new URL('../../examples/learning.json',import.meta.url)));
for(const theme of ['light','dark'])for(const width of [390,768,1100])test(`learning ${theme} ${width}: keyboard answers, scoring, flashcards and reset`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme,reducedMotion:'reduce'});await page.goto('/learning.html');await page.locator('.iui-root').evaluate((e,t)=>e.dataset.theme=t,theme);const quiz=page.locator('.iui-quiz'),cards=page.locator('.iui-flashcards');
 await expect(quiz.getByRole('button',{name:'确认答案'})).toBeDisabled();await quiz.getByRole('radio',{name:'30 ms',exact:true}).focus();await page.keyboard.press('Space');await quiz.getByRole('button',{name:'确认答案'}).focus();await page.keyboard.press('Enter');await expect(quiz.locator('.iui-learning-feedback')).toContainText('回答正确');await expect(quiz.getByRole('button',{name:'下一题'})).toBeFocused();await page.keyboard.press('Enter');await expect(quiz.locator('h3')).toBeFocused();await page.setViewportSize({width:width+1,height:880});await expect(quiz.locator('h3')).toBeFocused();await page.setViewportSize({width,height:900});
 await quiz.getByRole('checkbox').nth(0).check();await quiz.getByRole('checkbox').nth(1).check();await quiz.getByRole('button',{name:'确认答案'}).click();await expect(quiz.locator('.iui-learning-feedback')).toContainText('回答正确');
 await cards.getByRole('button',{name:'查看答案'}).focus();await page.keyboard.press('Enter');await expect(cards.locator('.iui-flashcard')).toHaveAttribute('data-side','back');await expect(cards.getByRole('button',{name:'返回正面'})).toBeFocused();await cards.getByRole('button',{name:'已掌握',exact:true}).click();await expect(cards.locator('progress')).toHaveAttribute('value','1');
 for(const component of [quiz,cards]){const live=component.locator(".iui-learning-live");await expect(live).toHaveAttribute("aria-live","polite");await expect(live).not.toHaveAttribute("aria-hidden","true");expect(await live.evaluate(e=>{const s=getComputedStyle(e);return{position:s.position,clip:s.clipPath,width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height};})).toEqual({position:"absolute",clip:"inset(50%)",width:1,height:1});}
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/learning-${theme}-${width}.png`,fullPage:true});
 await quiz.getByRole('button',{name:'查看结果'}).click();await expect(quiz.locator('.iui-learning-score')).toHaveText('得分: 5 / 5');await quiz.getByRole('button',{name:'重新开始'}).click();await expect(quiz.locator('progress')).toHaveAttribute('value','0');await expect(quiz.locator('input:checked')).toHaveCount(0);
 await cards.getByRole('button',{name:'下一张'}).click();await expect(cards.getByRole('button',{name:'已掌握',exact:true})).toBeDisabled();await cards.getByRole('button',{name:'查看答案'}).click();await cards.getByRole('button',{name:'再练一次'}).click();await cards.getByRole('button',{name:'查看结果'}).click();await expect(cards.locator('.iui-learning-score')).toHaveText('已掌握: 1 / 2');await cards.getByRole('button',{name:'重新开始'}).click();await expect(cards.locator('progress')).toHaveAttribute('value','0');expect(errors).toEqual([]);
});
test('learning loading/error/empty lifecycle and disposal',async({page})=>{await page.goto('/mount.html');await page.waitForFunction(()=>window.iui);await page.evaluate(spec=>window.learning=window.iui.mount(document.getElementById('host'),spec),fixture);for(const status of ['loading','error','ready']){await page.evaluate(({spec,status})=>{const next=structuredClone(spec);next.body[0].status=status;next.body[2].status=status;if(status==='ready'){next.body[0].questions=[];next.body[2].cards=[];}window.learning.update(next);},{spec:fixture,status});await expect(page.locator('.iui-learning-empty')).toHaveCount(2);await expect(page.locator('[data-learning-action]')).toHaveCount(0);}await page.evaluate(()=>window.learning.dispose());await expect(page.locator('#host')).toBeEmpty();});
