import{test,expect}from'@playwright/test';import{readFile,writeFile,mkdir}from'node:fs/promises';import{resolve}from'node:path';import{pathToFileURL}from'node:url';import{createHash}from'node:crypto';import{glyphEvidence}from'./math-evidence.mjs';
const lock=JSON.parse(await readFile('cdn-lock.json','utf8')),input=JSON.parse(await readFile('examples/math-fonts.json','utf8')),fontNames=Object.keys(lock.integrity).filter(n=>n.endsWith('.woff2')),fontURLs=fontNames.map(n=>new URL(n,lock.css).href),allowed=[lock.js,lock.css,...fontURLs];test.use({serviceWorkers:'block'});
for(const theme of ['light','dark'])for(const width of [390,1100])test(`CDN mathematics use actual licensed font glyphs ${theme} ${width}`,async({page})=>{
  await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme});const cdp=await page.context().newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});const transport=[],requests=[],failures=[],errors=[],assets={},pending=[];
  cdp.on('Network.responseReceived',({response:r})=>{if(allowed.includes(r.url))transport.push({url:r.url,status:r.status,mime:r.mimeType,disk:r.fromDiskCache===true,worker:r.fromServiceWorker===true});});
  page.on('request',r=>requests.push(r.url()));page.on('requestfailed',r=>failures.push({url:r.url(),failure:r.failure()}));page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await page.route('**/*',r=>r.request().url().startsWith('file:')||allowed.includes(r.request().url())?r.continue():r.abort('blockedbyclient'));
  page.on('response',r=>{if(allowed.includes(r.url()))pending.push((async()=>{const body=await r.body();assets[r.url()]={status:r.status(),headers:await r.allHeaders(),sha256:createHash('sha256').update(body).digest('hex'),bytes:body.length};})());});
  await page.goto(pathToFileURL(resolve('examples/browser/math-fonts.html')).href);await expect(page.locator('#status')).toBeEmpty();await expect(page.locator('.katex-html')).toHaveCount(5);await page.waitForLoadState('networkidle');const glyphs=await glyphEvidence(page);await Promise.all(pending);
  expect(await page.locator('.iui-root style').count()).toBe(0);expect(await page.locator('.katex-html').first().isVisible()).toBe(true);expect(await page.locator('.katex-mathml').first().evaluate(el=>({width:el.getBoundingClientRect().width,height:el.getBoundingClientRect().height,overflow:getComputedStyle(el).overflow}))).toEqual({width:1,height:1,overflow:'hidden'});
  expect(await page.locator('annotation[encoding="application/x-tex"]').allTextContents()).toEqual(input.body.filter(n=>n.type==='math').map(n=>n.latex));expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  const loaded=fontURLs.filter(url=>assets[url]);expect(loaded.length).toBeGreaterThanOrEqual(5);
  for(const url of [lock.js,lock.css,...loaded]){const name=new URL(url).pathname.split('/cdn/')[1],a=assets[url];expect(a?.status).toBe(200);expect(a.headers['access-control-allow-origin']).toBe('*');expect(a.headers['content-type']).toMatch(url.endsWith('.woff2')?/font\/woff2/:url.endsWith('.js')?/javascript/:/text\/css/);expect(a.sha256).toBe(lock.integrity[name].sha256);expect(a.bytes).toBe(lock.integrity[name].bytes);expect(transport.some(t=>t.url===url&&t.status===200&&!t.disk&&!t.worker)).toBe(true);}
  expect(requests.filter(u=>u.startsWith('http')).every(u=>allowed.includes(u))).toBe(true);expect(failures).toEqual([]);expect(errors).toEqual([]);await mkdir('test-results',{recursive:true});await writeFile(`test-results/math-cdn-${theme}-${width}.json`,JSON.stringify({commit:lock.commit,glyphs,transport,assets,requests,failures,errors},null,2));await page.screenshot({path:`test-results/math-cdn-${theme}-${width}.png`,fullPage:true});
});
