import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
// Prepared only. Browser execution/visual review belongs to the combined acceptance batch.
const fixture=JSON.parse(await readFile(new URL('../../examples/restaurant-menu.json',import.meta.url)));
const visible=root=>root.locator('.iui-menu-item:visible');
for(const colorScheme of ['light','dark'])for(const width of [390,768,1100])test(`menu native search and sections ${colorScheme} ${width}`,async({page})=>{
 const external=[],errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:4173/'))external.push(r.url());});
 await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme,reducedMotion:'reduce'});await page.goto('/restaurant-menu.html');
 const root=page.locator('.iui-menu'),search=root.getByRole('searchbox',{name:'搜索菜单'}),category=root.getByRole('combobox',{name:'分类'}),clear=root.getByRole('button',{name:'清除搜索'});
 await expect(visible(root)).toHaveCount(4);await expect(root.locator('[data-item-id=water] .iui-menu-price')).toHaveText('0 CNY');await expect(root.locator('[data-item-id=soup] .iui-menu-price')).toHaveText('未提供价格');await expect(root.locator('[data-item-id=tea] .iui-menu-price')).toHaveText('1e-7 CNY');await expect(root.locator('[data-item-id=rice] .iui-menu-price')).toHaveText('28.125 CNY');
 const summary=root.locator('summary');await summary.click();await expect(root.locator('details')).toHaveAttribute('open','');
 await search.focus();await page.keyboard.insertText('  香草  ');await expect(visible(root)).toHaveCount(2);await page.keyboard.press('Tab');await expect(category).toBeFocused();await category.selectOption('drinks');await expect(visible(root)).toHaveCount(1);await expect(root.locator('.iui-menu-count')).toHaveText('显示 1 / 4 个项目');await page.keyboard.press('Tab');await expect(clear).toBeFocused();await page.keyboard.press('Space');await expect(search).toBeFocused();await expect(search).toHaveValue('');await expect(category).toHaveValue('');await expect(root.locator('details')).toHaveAttribute('open','');
 await category.selectOption('empty');await expect(visible(root)).toHaveCount(0);await expect(root.locator('.iui-menu-empty')).toContainText('没有符合');await expect(search).toBeVisible();await clear.click();await search.fill('香草');await page.getByRole('button',{name:'只更新其他状态'}).click();await expect(search).toHaveValue('香草');await expect(visible(root)).toHaveCount(2);await expect(root.locator('details')).toHaveAttribute('open','');
 await clear.click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);for(const box of await root.locator('input,select,button,summary').evaluateAll(nodes=>nodes.filter(n=>n.getClientRects().length).map(n=>{const r=n.getBoundingClientRect();return{left:r.left,right:r.right,height:r.height};}))){expect(box.left).toBeGreaterThanOrEqual(0);expect(box.right).toBeLessThanOrEqual(width);expect(box.height).toBeGreaterThanOrEqual(44);}
 await page.screenshot({path:`test-results/menu-${colorScheme}-${width}.png`,fullPage:true});expect(errors).toEqual([]);expect(external).toEqual([]);
});
test.describe('menu touch',()=>{test.use({hasTouch:true});test('native controls and retained details by tap',async({page})=>{
 await page.setViewportSize({width:390,height:900});await page.goto('/restaurant-menu.html');const root=page.locator('.iui-menu');await root.locator('summary').tap();await expect(root.locator('details')).toHaveAttribute('open','');await root.getByRole('searchbox').tap();await page.keyboard.insertText('香草');await expect(visible(root)).toHaveCount(2);await root.getByRole('combobox').selectOption('drinks');await expect(visible(root)).toHaveCount(1);await root.getByRole('button',{name:'清除搜索'}).tap();await expect(visible(root)).toHaveCount(4);await expect(root.getByRole('searchbox')).toBeFocused();await expect(root.locator('details')).toHaveAttribute('open','');
});});
test('menu genuine Arabic-first RTL, forced colors and literal long wrapping',async({page})=>{
 await page.setViewportSize({width:390,height:900});await page.emulateMedia({forcedColors:'active'});await page.goto('/mount.html');await page.waitForFunction(()=>!!window.iui);
 await page.evaluate(spec=>{delete spec.description;delete spec.title;spec.body=spec.body.slice(0,1);const menu=spec.body[0];menu.title='قائمة طعام تجريبية';menu.description='هذه بيانات تجريبية مستقلة.';menu.sections[0].title='الأطباق';menu.sections[0].items[0].name='طبق تجريبي';menu.sections[0].items[0].description='كلمةطويلة'.repeat(100);document.documentElement.dir='rtl';document.documentElement.lang='ar';window.menu=window.iui.mount(document.getElementById('host'),spec);},fixture);
 const root=page.locator('.iui-menu');await expect(root).toHaveCSS('direction','rtl');await expect(root.locator('.iui-menu-price[data-price=supplied]').first()).toHaveCSS('direction','ltr');await root.getByRole('searchbox').focus();await page.keyboard.press('Tab');await expect(root.getByRole('combobox')).toBeFocused();await expect(root.getByRole('combobox')).toHaveCSS('outline-style','solid');await root.locator('summary').first().click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/menu-arabic-forced-390.png',fullPage:true});
});
test('menu outer form ownership, disabled fieldset, Unicode draft and atomic lifecycle',async({page})=>{
 await page.goto('/mount.html');await page.waitForFunction(()=>!!window.iui);await page.evaluate(spec=>{document.documentElement.lang='en';const host=document.getElementById('host'),form=document.createElement('form'),fieldset=document.createElement('fieldset');form.append(fieldset);fieldset.append(host);document.body.append(form);window.submits=0;form.addEventListener('submit',e=>{e.preventDefault();window.submits++;});window.menuSpec=spec;window.menu=window.iui.mount(host,spec);window.outerForm=form;window.menuFieldset=fieldset;},fixture);
 const root=page.locator('.iui-menu'),search=root.getByRole('searchbox'),category=root.getByRole('combobox');await search.fill('香草');await search.press('Enter');expect(await page.evaluate(()=>window.submits)).toBe(0);await category.selectOption('drinks');await page.evaluate(()=>window.outerForm.reset());await expect(search).toHaveValue('香草');await expect(category).toHaveValue('drinks');await expect(visible(root)).toHaveCount(1);
 await page.evaluate(()=>window.menuFieldset.disabled=true);await expect(search).toBeDisabled();await search.evaluate(e=>{e.value='forged';e.dispatchEvent(new Event('input',{bubbles:true}));});await root.getByRole('button',{name:'Clear search'}).evaluate(e=>e.dispatchEvent(new MouseEvent('click',{bubbles:true})));await expect(search).toHaveValue('香草');await expect(visible(root)).toHaveCount(1);await page.evaluate(()=>window.menuFieldset.disabled=false);
 await search.fill('😀'.repeat(201));await expect(search).toHaveValue('😀'.repeat(201));await expect(search).toHaveAttribute('aria-invalid','true');await expect(root.locator('.iui-menu-limit')).toContainText('last valid search');await search.fill('香草');await search.focus();await search.evaluate(e=>{e.setSelectionRange(0,1);window.keptSearch=e;});await page.evaluate(()=>window.menu.setState({n:2}));expect(await search.evaluate(e=>e===window.keptSearch&&e.selectionStart===0&&e.selectionEnd===1)).toBe(true);await expect(search).toBeFocused();
 await page.evaluate(()=>{const bad=structuredClone(window.menuSpec);delete bad.body[0].sections[0].items[0].price;try{window.menu.update(bad);}catch{window.menuRejected=true;}});expect(await page.evaluate(()=>window.menuRejected)).toBe(true);await expect(search).toHaveValue('香草');await page.evaluate(()=>window.menu.update(window.menuSpec));await expect(root.getByRole('searchbox')).toHaveValue('');await expect(visible(root)).toHaveCount(4);await page.evaluate(()=>window.menu.dispose());await expect(page.locator('#host')).toBeEmpty();
});
