import{test,expect}from'@playwright/test';import{readFile,writeFile,mkdir}from'node:fs/promises';import{pathToFileURL}from'node:url';import{resolve}from'node:path';import{createHash}from'node:crypto';
const lock=JSON.parse(await readFile('cdn-lock.json','utf8')),allowed=[lock.js,lock.css,...Object.keys(lock.integrity).filter(n=>n.endsWith('.woff2')).map(n=>new URL(n,lock.css).href)];test.use({serviceWorkers:'block'});
for(const theme of ['light','dark'])for(const width of [390,768,1100])test(`phase one actual CDN ${theme} ${width}: fields, weather and numeric charts coexist`,async({page})=>{
  await page.setViewportSize({width,height:950});await page.emulateMedia({colorScheme:theme});const cdp=await page.context().newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});const transport=[],requests=[],errors=[],assets={},pending=[];cdp.on('Network.responseReceived',({response:r})=>{if(allowed.includes(r.url))transport.push({url:r.url,status:r.status,disk:r.fromDiskCache===true,worker:r.fromServiceWorker===true,mime:r.mimeType});});page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>errors.push(r.url()+': '+r.failure()?.errorText));await page.route('**/*',r=>r.request().url().startsWith('file:')||allowed.includes(r.request().url())?r.continue():r.abort());page.on('response',r=>{if(allowed.includes(r.url()))pending.push((async()=>{const b=await r.body();assets[r.url()]={status:r.status(),sha256:createHash('sha256').update(b).digest('hex'),headers:await r.allHeaders()};})());});
  await page.goto(pathToFileURL(resolve('examples/browser/phase-one.html')).href);await expect(page.locator('#status')).toBeEmpty();await expect(page.locator('.iui-root')).toBeVisible();const form=page.getByRole('form',{name:'合成分账表单'}),amount=form.getByRole('spinbutton',{name:'总点数'}),people=form.getByRole('spinbutton',{name:'参与人数'});await amount.fill('200');await people.fill('4');await expect(form.locator('.iui-metric-value')).toHaveText('50点');await form.getByRole('button',{name:'确认分账'}).click();await expect(form).toHaveAttribute('data-status','success');
  const weather=page.locator('.iui-weather');await weather.getByRole('button',{name:'华氏度'}).click();await expect(weather.locator('.iui-weather-current-temperature')).toHaveText('57.6°F');await weather.getByRole('button',{name:'表格',exact:true}).click();await expect(weather.locator('tbody')).toContainText('GMT-8');await expect(amount).toHaveValue('200');await expect(people).toHaveValue('4');
  const chart=page.locator('[id$="-uneven"]');const xs=await chart.locator('circle').evaluateAll(nodes=>nodes.map(n=>Number(n.getAttribute('cx'))));expect(Math.abs((xs[1]-xs[0])/(xs[2]-xs[0])-.01)).toBeLessThan(1e-10);await chart.locator('svg').focus();await page.keyboard.press('End');await expect(chart.locator('output')).toContainText('100 · 合成电压: 4V');await form.getByRole('button',{name:'恢复初值'}).click();await expect(amount).toHaveValue('126');await expect(weather).toHaveAttribute('data-unit','fahrenheit');await expect(chart.locator('[data-series]')).toHaveCount(1);
  await page.waitForLoadState('networkidle');await page.evaluate(()=>document.fonts.ready);await Promise.all(pending);expect(await page.locator('.iui-root style').count()).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);expect(requests.filter(u=>u.startsWith('http')).every(u=>allowed.includes(u))).toBe(true);for(const url of [lock.js,lock.css]){const name=new URL(url).pathname.split('/cdn/')[1];expect(assets[url]?.status).toBe(200);expect(assets[url].sha256).toBe(lock.integrity[name].sha256);expect(assets[url].headers['access-control-allow-origin']).toBe('*');expect(transport.some(r=>r.url===url&&r.status===200&&!r.disk&&!r.worker)).toBe(true);}await mkdir('test-results',{recursive:true});await writeFile(`test-results/phase-one-cdn-${theme}-${width}.json`,JSON.stringify({commit:lock.commit,transport,requests,errors,assets},null,2));await page.screenshot({path:`test-results/phase-one-cdn-${theme}-${width}.png`,fullPage:true});
});
