import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
// PREPARED ONLY: run in the owner's combined real-browser acceptance batch.
const fixture=JSON.parse(await readFile(new URL('../../examples/rating.json',import.meta.url)));
async function setup(page,input=fixture,language='zh-CN'){
 await page.goto('/mount.html');await page.waitForFunction(()=>!!window.iui);
 await page.evaluate(({input,language})=>{const host=document.getElementById('host');host.lang=language;window.ratingController=window.iui.mount(host,input);},{input,language});
}
const state=page=>page.evaluate(()=>window.ratingController.getState());
for(const colorScheme of ['light','dark'])for(const width of [390,768,1100])test(`rating native input ${colorScheme} ${width}`,async({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.setViewportSize({width,height:950});await page.emulateMedia({colorScheme});await setup(page);
 const group=page.getByRole('group',{name:'清晰程度',exact:true}),radios=group.getByRole('radio'),clear=group.getByRole('button',{name:'清除评分'}),output=group.locator('output');
 await expect(radios).toHaveCount(5);await expect(group.locator('input:checked')).toHaveCount(0);await expect(output).toHaveText('尚未评分');
 await radios.nth(2).click();await expect(radios.nth(2)).toBeChecked();expect((await state(page)).clarity).toBe(3);await expect(output).toHaveText('3 分，满分 5 分');
 await page.keyboard.press('ArrowRight');await expect(radios.nth(3)).toBeChecked();await expect(radios.nth(3)).toBeFocused();await page.keyboard.press('ArrowDown');await expect(radios.nth(4)).toBeChecked();await page.keyboard.press('ArrowRight');await expect(radios.first()).toBeChecked();await page.keyboard.press('ArrowLeft');await expect(radios.last()).toBeChecked();
 await clear.click();await expect(clear).toBeFocused();await expect(clear).toHaveAttribute('aria-disabled','true');expect(await clear.evaluate(button=>button.disabled)).toBe(false);await expect(group.locator('input:checked')).toHaveCount(0);await page.keyboard.press('Space');await expect(output).toHaveText('尚未评分');await expect(clear).toBeFocused();
 await radios.nth(1).focus();await page.keyboard.press('Space');await expect(radios.nth(1)).toBeChecked();await page.evaluate(()=>window.ratingController.setState({confidence:4}));await expect(radios.nth(1)).toBeFocused();await expect(radios.nth(1)).toBeChecked();
 const size=await radios.nth(1).locator('..').boundingBox();expect(size.height).toBeGreaterThanOrEqual(44);expect(size.width).toBeGreaterThanOrEqual(44);
 await page.getByRole('button',{name:'恢复初始评分'}).click();await expect(output).toHaveText('尚未评分');await expect(page.getByRole('group',{name:'学习信心'}).getByRole('radio',{name:'3 分，满分 10 分',exact:true})).toBeChecked();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
 await page.screenshot({path:`test-results/rating-${colorScheme}-${width}.png`,fullPage:true});
});
test('rating keyboard Tab enters the radio group once and disabled state has no active interaction',async({page})=>{
 await setup(page);const group=page.getByRole('group',{name:'清晰程度',exact:true}),radios=group.getByRole('radio'),clear=group.getByRole('button');await radios.first().focus();await page.keyboard.press('Space');await page.keyboard.press('Tab');await expect(clear).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(radios.first()).toBeFocused();
 await page.evaluate(()=>window.ratingController.setState({locked:true}));await expect(radios.first()).toBeDisabled();await expect(clear).toBeDisabled();await page.evaluate(()=>{const radio=document.querySelector('.iui-rating input');radio.checked=true;radio.dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('.iui-rating-clear').dispatchEvent(new Event('click',{bubbles:true}));});expect((await state(page)).clarity).toBe(1);
 await page.evaluate(()=>window.ratingController.setState({clarity:4,locked:false}));await expect(radios.nth(3)).toBeChecked();await expect(radios.nth(3)).toBeEnabled();
});
test('rating genuine touch target selects once and Clear remains stable on repeated activation',async({browser})=>{
 const context=await browser.newContext({baseURL:'http://127.0.0.1:4173',hasTouch:true,viewport:{width:390,height:950}}),page=await context.newPage();await setup(page);const group=page.getByRole('group',{name:'清晰程度',exact:true});const label=group.getByRole('radio').nth(3).locator('..');for(let i=0;i<2;i++){const box=await label.boundingBox();await page.touchscreen.tap(box.x+box.width/2,box.y+box.height/2);expect((await state(page)).clarity).toBe(4);}const clear=group.getByRole('button');await clear.tap();const clearBox=await clear.boundingBox();const point={x:clearBox.x+clearBox.width/2,y:clearBox.y+clearBox.height/2};expect(await clear.evaluate((button,p)=>button.contains(button.ownerDocument.elementFromPoint(p.x,p.y)),point)).toBe(true);await page.touchscreen.tap(point.x,point.y);expect((await state(page)).clarity).toBe(0);await expect(group.locator('input:checked')).toHaveCount(0);await context.close();
});
test('rating real RTL, long literal labels, forced colors and reduced motion remain readable',async({page})=>{
 await page.setViewportSize({width:390,height:950});await page.emulateMedia({forcedColors:'active',reducedMotion:'reduce'});
 const input={version:'iui/1',description:'تقييم محلي واضح للقارئ.',state:{score:3,other:0},body:[{type:'rating',label:'تقييم الشرح '+ 'طويل '.repeat(20),bind:'score',max:10,hint:'النص المتوفر هنا يبقى داخل الصفحة.'}]};await setup(page,input,'ar');const group=page.locator('.iui-rating');await expect(group).toHaveCSS('direction','rtl');const radio=group.getByRole('radio',{name:'3 of 10',exact:true});await radio.focus();await expect(radio).toHaveCSS('outline-style','solid');await page.keyboard.press('Space');await expect(radio).toBeChecked();await expect(group.locator('output')).toHaveText('3 of 10');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/rating-rtl-forced-colors.png',fullPage:true});
});
test('rating global rejection, atomic invalid update, replacement, and teardown preserve accepted state',async({page})=>{
 const input={version:'iui/1',state:{score:2,other:0},body:[{type:'rating',label:'Clarity',bind:'score'},{type:'loading',label:'Guard',progress:{op:'mul',args:[{$:'score'},30]}}]};await setup(page,input,'en');const group=page.getByRole('group',{name:'Clarity'}),rejected=group.getByRole('radio',{name:'4 of 5',exact:true});await rejected.click();await expect(rejected).toBeFocused();await expect(group.getByRole('radio',{name:'2 of 5',exact:true})).toBeChecked();await expect(group.getByRole('status').last()).toContainText('could not be applied');expect((await state(page)).score).toBe(2);
 expect(await page.evaluate(()=>{const host=document.getElementById('host'),before=host.innerHTML,focus=document.activeElement;try{window.ratingController.update({version:'iui/1',state:{score:6},body:[{type:'rating',label:'Bad',bind:'score'}]});return false;}catch{return before===host.innerHTML&&focus===document.activeElement;}})).toBe(true);
 await page.evaluate(()=>{window.oldRating=document.querySelector('.iui-rating');window.ratingController.update({version:'iui/1',state:{score:1},body:[{type:'rating',label:'New',bind:'score'}]});const radio=window.oldRating.querySelector('[value="5"]');radio.checked=true;radio.dispatchEvent(new Event('change',{bubbles:true}));window.oldRating.querySelector('button').click();});expect((await state(page)).score).toBe(1);await page.evaluate(()=>window.ratingController.dispose());await expect(page.locator('#host')).toBeEmpty();
});
