import {test,expect} from '@playwright/test';import {readFile} from 'node:fs/promises';
const fixture=JSON.parse(await readFile(new URL('../../examples/tabs-local-state.json',import.meta.url)));
async function setup(page,input=fixture){await page.goto('/mount.html');await page.waitForFunction(()=>!!window.iui);await page.evaluate(input=>{document.getElementById('host').lang='zh-CN';window.tabsController=window.iui.mount(document.getElementById('host'),input);},input);}
for(const colorScheme of ['light','dark'])for(const width of [390,768,1100])test(`tabs ${colorScheme} ${width} native keys and preserved children`,async({page})=>{
 await page.setViewportSize({width,height:950});await page.emulateMedia({colorScheme});const errors=[];page.on('pageerror',e=>errors.push(e.message));await setup(page);
 const list=page.getByRole('tablist',{name:'阅读方式'}),first=list.getByRole('tab',{name:'概览',exact:true}),last=list.getByRole('tab',{name:'参考与代码',exact:true}),input=page.getByRole('spinbutton',{name:'偶数样本',exact:false}),timer=page.locator('.iui-time');await expect(first).toHaveAttribute('aria-selected','true');await expect(list.getByRole('tab',{name:'暂不可用',exact:true})).toBeDisabled();
 await input.fill('3');await page.locator('[data-time-action=start]').click();await expect(timer).toHaveAttribute('data-status','running');await first.focus();await page.keyboard.press('ArrowRight');await expect(last).toBeFocused();await expect(last).toHaveAttribute('aria-selected','true');await expect(input).toBeHidden();await expect(page.locator('.iui-metric-value').last()).toContainText('2');
 await page.evaluate(()=>window.tabsController.setState({other:1}));await expect(last).toBeFocused();await page.keyboard.press('Home');await expect(first).toBeFocused();await expect(input).toHaveValue('3');await expect(timer).toHaveAttribute('data-status','running');await page.getByRole('button',{name:'练习说明',exact:true}).click();await expect(page.locator('.iui-overlay-popover')).toHaveAttribute('data-open','true');await last.click();await expect(page.locator('.iui-overlay-popover')).toHaveAttribute('data-open','false');await expect(last).toBeFocused();await page.keyboard.press('ArrowRight');await expect(first).toBeFocused();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);await page.screenshot({path:`test-results/tabs-${colorScheme}-${width}.png`,fullPage:true});
});
test('tabs genuine RTL narrow rail reveals focused tab without moving the page',async({page})=>{
 await page.setViewportSize({width:390,height:900});const input={version:'iui/1',description:'مثال أصلي لعلامات التبويب.',body:[{type:'tab-group',label:'Views',children:Array.from({length:12},(_,i)=>({type:'tab-panel',id:'panel'+i,label:'Panel '+i+' long title',children:[{type:'text',value:'Content '+i}]}))}]};await setup(page,input);const list=page.getByRole('tablist',{name:'Views'});await expect(list).toHaveCSS('direction','rtl');const tabs=list.getByRole('tab');await tabs.first().focus();const scrollY=await page.evaluate(()=>window.scrollY);await page.keyboard.press('End');await expect(tabs.last()).toBeFocused();await expect(tabs.last()).toHaveAttribute('aria-selected','true');const rects=await list.evaluate(el=>{const active=el.querySelector('[aria-selected=true]'),a=active.getBoundingClientRect(),b=el.getBoundingClientRect();return{a:{left:a.left,right:a.right},b:{left:b.left,right:b.right}};});expect(rects.a.left).toBeGreaterThanOrEqual(rects.b.left-1);expect(rects.a.right).toBeLessThanOrEqual(rects.b.right+1);expect(await page.evaluate(()=>window.scrollY)).toBe(scrollY);await page.keyboard.press('Home');await page.keyboard.press('ArrowLeft');await expect(tabs.nth(1)).toBeFocused();
});
test('native touch activation, repeated selection and disabled tabs preserve one panel',async({browser})=>{
 const context=await browser.newContext({baseURL:'http://127.0.0.1:4173',hasTouch:true,viewport:{width:390,height:900}}),page=await context.newPage();await setup(page);const last=page.getByRole('tab',{name:'参考与代码',exact:true});for(let i=0;i<2;i++){const b=await last.boundingBox();await page.touchscreen.tap(b.x+b.width/2,b.y+b.height/2);await expect(last).toHaveAttribute('aria-selected','true');}await expect(page.getByRole('tabpanel')).toHaveCount(1);await context.close();
});
test('tabs forced-colors, nested form submission, atomic invalid update and disposal',async({page})=>{
 await page.emulateMedia({forcedColors:'active',reducedMotion:'reduce'});await setup(page);const first=page.getByRole('tab',{name:'概览',exact:true});await first.focus();await page.keyboard.press('End');await page.keyboard.press('Home');expect(await first.evaluate(el=>getComputedStyle(el).outlineStyle)).not.toBe('none');await page.getByRole('button',{name:'检查本页',exact:true}).click();await expect(page.getByRole('form',{name:'本地练习'})).toHaveAttribute('data-status','success');await first.focus();expect(await page.evaluate(()=>{const host=document.getElementById('host'),before=host.innerHTML,focus=document.activeElement;try{window.tabsController.update({version:'iui/1',body:[{type:'tab-panel',id:'bad',label:'Bad',children:[]}]});return false;}catch{return host.innerHTML===before&&document.activeElement===focus;}})).toBe(true);await page.evaluate(()=>window.tabsController.dispose());await expect(page.locator('#host')).toBeEmpty();
});
