import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const fixture=JSON.parse(await readFile(new URL('../../examples/supplied-trackers.json',import.meta.url)));
// Prepared only. Real-browser interaction and screenshot review remain pending.
async function setup(page,input=fixture,lang='en'){
 await page.goto('/mount.html');await page.waitForFunction(()=>!!window.iui);const requests=[];page.on('request',r=>requests.push(r.url()));
 await page.evaluate(({input,lang})=>{const host=document.getElementById('host');host.lang=lang;window.trackerController=window.iui.mount(host,input);},{input,lang});return requests;
}
for(const theme of ['light','dark'])for(const width of [390,768,1100])test(`trackers ${theme} ${width}: actual reading, native filtering, reset and exact times`,async({page,context})=>{
 await page.setViewportSize({width,height:1100});const requests=await setup(page,{...fixture,theme});await context.setOffline(true);const parcel=page.locator('.iui-package-tracker'),flight=page.locator('.iui-flight-tracker'),filter=parcel.getByRole('combobox'),reset=parcel.getByRole('button',{name:'Reset filter'}),details=parcel.locator('details');
 await expect(flight.locator('.iui-tracker-missing')).toHaveCount(2);await expect(flight).toContainText('2028-02-29T07:20-05:00');await details.locator('summary').focus();await page.keyboard.press('Enter');await expect(details).toHaveAttribute('open','');
 await filter.focus();await page.keyboard.press('End');await page.keyboard.press('Enter');await expect(filter).toHaveValue('pending');await expect(parcel.locator('.iui-tracker-record:visible')).toHaveCount(1);await expect(filter).toBeFocused();await page.keyboard.press('Escape');await expect(filter).toHaveValue('pending');await expect(filter).toBeFocused();
 await page.evaluate(()=>{window.savedTrackerRow=document.querySelector('[data-record-id=hub]');window.trackerController.setState({other:1});});await expect(filter).toBeFocused();await reset.click();await expect(parcel.locator('.iui-tracker-record:visible')).toHaveCount(3);await expect(details).toHaveAttribute('open','');expect(await page.evaluate(()=>document.querySelector('[data-record-id=hub]')===window.savedTrackerRow)).toBe(true);
 await reset.focus();await page.keyboard.press('Enter');await page.keyboard.press('Space');await expect(reset).toBeFocused();await expect(reset).toHaveAttribute('aria-disabled','true');await flight.getByRole('combobox').selectOption('disruption');await expect(flight.locator('.iui-tracker-record:visible')).toHaveCount(1);
 expect(await page.locator('.iui-tracker select,.iui-tracker button,.iui-tracker summary').evaluateAll(nodes=>nodes.every(n=>n.getBoundingClientRect().height>=44))).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(requests).toEqual([]);await page.screenshot({path:`test-results/trackers-${theme}-${width}.png`,fullPage:true});
});
test('trackers actual touch disclosures and local filter reset',async({browser})=>{const context=await browser.newContext({baseURL:'http://127.0.0.1:4173',hasTouch:true,viewport:{width:390,height:1000}}),page=await context.newPage(),requests=await setup(page),parcel=page.locator('.iui-package-tracker');await parcel.locator('summary').tap();await expect(parcel.locator('details')).toHaveAttribute('open','');await parcel.locator('select').tap();await page.keyboard.press('Escape');await parcel.locator('select').selectOption('pending');await parcel.locator('button').tap();await expect(parcel.locator('select')).toHaveValue('');expect(requests).toEqual([]);await context.close();});
test('trackers Arabic-first RTL, Chinese labels, forced-colors and narrow wrapping',async({page})=>{await page.setViewportSize({width:390,height:1100});await page.emulateMedia({forcedColors:'active',reducedMotion:'reduce'});const spec=structuredClone(fixture);for(const n of spec.body)n.label='معلومات مقدمة '.repeat(8);spec.body[0].milestones[1].description='تفاصيل أصلية '.repeat(80);const requests=await setup(page,spec,'zh-CN');await expect(page.locator('.iui-package-tracker')).toHaveCSS('direction','rtl');await expect(page.locator('.iui-flight-tracker')).toContainText('实际');await expect(page.locator('.iui-tracker-time').first()).toHaveCSS('direction','ltr');await page.locator('.iui-package-tracker select').focus();expect(await page.locator('.iui-package-tracker select').evaluate(el=>getComputedStyle(el).outlineStyle)).not.toBe('none');await page.locator('.iui-package-tracker summary').click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(requests).toEqual([]);await page.screenshot({path:'test-results/trackers-rtl-forced-colors.png',fullPage:true});});
test('trackers disabled/pending controls, ordinary source link, native outer reset and retirement',async({page})=>{const requests=await setup(page);await page.evaluate(nodes=>{window.trackerController.dispose();window.trackerController=window.iui.mount(document.getElementById('host'),{version:'iui/1',state:{note:'Only bound'},body:[{type:'form',label:'Local',action:'save',children:[{type:'input',kind:'text',label:'Note',bind:'note'},...nodes]}]},{actions:{save:({values})=>{window.trackerSnapshot=values;return new Promise(r=>window.finishTracker=r);}}});},fixture.body);const parcel=page.locator('.iui-package-tracker'),filter=parcel.locator('select');await filter.selectOption('pending');await page.getByRole('button',{name:'Submit',exact:true}).click();await expect(filter).toBeDisabled();await parcel.locator('button').evaluate(el=>el.dispatchEvent(new MouseEvent('click',{bubbles:true})));await expect(filter).toHaveValue('pending');const link=parcel.locator('a');await link.evaluate(el=>el.addEventListener('click',e=>{window.trackerLinkBlocked=e.defaultPrevented;e.preventDefault();}));await link.click();expect(await page.evaluate(()=>window.trackerLinkBlocked)).toBe(false);expect(await page.evaluate(()=>window.trackerSnapshot)).toEqual({note:'Only bound'});await page.evaluate(()=>window.finishTracker());await expect(filter).toBeEnabled();await page.evaluate(()=>{const old=document.querySelector('.iui-package-tracker'),before=old.outerHTML;window.trackerController.dispose();old.querySelector('button').click();if(old.outerHTML!==before)throw Error('Retired tracker changed');});await expect(page.locator('#host')).toBeEmpty();expect(requests).toEqual([]);});

test('trackers ordinary outer-form reset retains guarded local filters and matching rows',async({page})=>{const requests=await setup(page);await page.evaluate(()=>{const host=document.getElementById('host'),form=document.createElement('form'),field=document.createElement('fieldset');host.replaceWith(form);form.append(field);field.append(host);});const parcel=page.locator('.iui-package-tracker'),filter=parcel.locator('select');await filter.selectOption('current');await page.evaluate(()=>document.querySelector('form').reset());await expect(filter).toHaveValue('');await expect(parcel.locator('.iui-tracker-record:visible')).toHaveCount(3);await filter.selectOption('pending');await page.evaluate(()=>{document.querySelector('fieldset').disabled=true;document.querySelector('form').reset();});await expect(filter).toHaveValue('pending');await expect(parcel.locator('.iui-tracker-record:visible')).toHaveCount(1);await page.evaluate(()=>{document.querySelector('fieldset').disabled=false;document.querySelector('.iui-package-tracker .iui-tracker-toolbar').setAttribute('inert','');document.querySelector('form').reset();});await expect(filter).toHaveValue('pending');expect(await page.evaluate(()=>[...new FormData(document.querySelector('form')).entries()])).toEqual([]);expect(requests).toEqual([]);});
