import test from 'node:test';import assert from 'node:assert/strict';import {readFile,mkdtemp,symlink,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';
import {parseDiscovery,browserInputHashes,requiredRecoveryPaths} from '../scripts/batch-browser-plan.mjs';
test('browser discovery parses prepared counts and refuses absent, duplicate or unbounded totals',()=>{assert.deepEqual(parseDiscovery('  [chromium] example\nTotal: 691 tests in 78 files\n'),{tests:691,files:78});for(const s of ['', 'Total: 0 tests in 0 files','Total: -1 tests in 78 files','Total: 1 test in 1 file\nTotal: 2 tests in 2 files','Total: 999999999999999999999 tests in 78 files'])assert.throws(()=>parseDiscovery(s));});
test('browser plan includes pinned licensed font and native-select recovery source owners',async()=>{const hashes=await browserInputHashes(process.cwd());for(const p of requiredRecoveryPaths)assert.match(hashes[p],/^[a-f0-9]{64}$/);assert.ok(Object.keys(hashes).filter(p=>/^tests\/browser\/.*\.spec\.mjs$/.test(p)).length>=78);assert.ok(hashes['tests/browser/helpers/current-demo.mjs']);assert.ok(hashes['scripts/build-examples.mjs']);assert.ok(hashes['.github/workflows/ci.yml']);});
test('browser plan refuses a symlinked checkout root',async t=>{const dir=await mkdtemp(path.join(tmpdir(),'inform-plan-'));t.after(()=>rm(dir,{recursive:true,force:true}));const link=path.join(dir,'link');await symlink(process.cwd(),link,'dir');await assert.rejects(browserInputHashes(link),/Real browser input root/);});
test('prepared 115 workflow has a single canonical execution and preserves historical lock bytes',async()=>{const workflow=await readFile('.github/workflows/ci.yml','utf8');assert.equal((workflow.match(/run: npm run test:browser/g)||[]).length,1);assert.ok(workflow.includes('batch-browser-plan.mjs --lock tests/consumer/batch-lock-115.json'));assert.ok(workflow.includes('Read reviewed batch revisions'));assert.ok(workflow.includes('node scripts/prepare-test-font.mjs --install'));assert.ok(!workflow.includes('fonts-noto-cjk'));const historyBytes=await readFile('tests/consumer/batch-lock.json');assert.equal(createHash('sha256').update(historyBytes).digest('hex'),'cb5d4483b37c501f949dc4662e9bb1ce9f4821dd9ec590f7ca128925a1dc6852');const history=JSON.parse(historyBytes);assert.equal(history.format,'inform-ui-batch-lock/1');assert.equal(history.consumers.find(p=>p.id==='pending').examples.length,37);});

test('115 lock preparation cannot overwrite the historical lock or escape its explicit destination',()=>{for(const output of ['tests/consumer/batch-lock.json','../outside.json','/tmp/outside.json']){const run=spawnSync(process.execPath,['scripts/prepare-batch-lock.mjs','--skill','/unused','--asset','a'.repeat(40),'--output',output],{encoding:'utf8'});assert.notEqual(run.status,0);assert.match(run.stderr,/batch-lock-115/);}});
