import test from 'node:test';import assert from 'node:assert/strict';import{JSDOM}from'jsdom';import{validateDocument,evaluateState,mount}from'../dist/index.js';
const chart=(kind='line',extra={})=>({type:'chart',kind,xScale:'linear',xKey:'x',data:[{x:0,y:1},{x:1,y:2},{x:100,y:3}],series:[{key:'y',label:'Value'}],...extra});const spec=n=>({version:'iui/1',body:[n]});const setup=n=>{const d=new JSDOM('<div id="host"></div>'),h=d.window.document.querySelector('#host'),c=mount(h,spec(n));return{d,h,c};};
const invalid=(n,code)=>{const r=validateDocument(spec(n));assert.equal(r.ok,false);assert.ok(r.issues.some(i=>i.code===code),JSON.stringify(r));};
test('linear coordinates preserve 1% rather than equidistant categorical spacing',()=>{const {h,c}=setup(chart()),dots=[...h.querySelectorAll('[data-series] circle')].map(e=>Number(e.getAttribute('cx')));assert.ok(Math.abs((dots[1]-dots[0])/(dots[2]-dots[0])-.01)<1e-12);assert.equal(h.querySelector('figure').dataset.xScale,'linear');c.dispose();const legacy=chart('line');delete legacy.xScale;const other=setup(legacy),xs=[...other.h.querySelectorAll('circle')].map(e=>Number(e.getAttribute('cx')));assert.equal((xs[1]-xs[0])/(xs[2]-xs[0]),.5);other.c.dispose();});
test('time coordinates preserve elapsed time with explicit offsets',()=>{const{h,c}=setup(chart('line',{xScale:'time',timezone:'Asia/Shanghai',data:[{x:'2026-10-08T08:00:00+08:00',y:1},{x:'2026-10-08T00:01:00Z',y:2},{x:'2026-10-08T01:40:00Z',y:3}]}));const xs=[...h.querySelectorAll('circle')].map(e=>Number(e.getAttribute('cx')));assert.ok(Math.abs((xs[1]-xs[0])/(xs[2]-xs[0])-.01)<1e-12);c.dispose();});
test('scatter accepts unordered negative x and area preserves null-separated segments',()=>{const scatter=setup(chart('scatter',{data:[{x:3,y:-1},{x:-4,y:2},{x:0,y:null}]}));assert.equal(scatter.h.querySelectorAll('[data-series] circle').length,2);assert.equal(scatter.h.querySelectorAll('[data-series] path').length,0);scatter.c.dispose();const area=setup(chart('area',{data:[{x:-4,y:-1},{x:0,y:2},{x:1,y:null},{x:7,y:3}]}));assert.equal(area.h.querySelectorAll('[data-area=true]').length,2);assert.match(area.h.textContent,/Missing/);area.c.dispose();});
test('empty, all-null, singleton, loading and error charts have explicit readable states',()=>{for(const data of [[],[{x:1,y:null}]]){const{h,c}=setup(chart('line',{data}));assert.match(h.textContent,/No data/);assert.equal(h.querySelector('svg').style.display,'none');c.dispose();}const single=setup(chart('line',{data:[{x:-2,y:5}]}));assert.equal(single.h.querySelectorAll('circle').length,1);assert.ok(Number.isFinite(Number(single.h.querySelector('circle').getAttribute('cx'))));single.c.dispose();for(const status of ['loading','error']){const{h,c}=setup(chart('line',{data:[],status}));assert.equal(h.querySelector('.iui-data-status').dataset.state,status);assert.equal(h.querySelector('svg').style.display,'none');c.dispose();}});
test('donut uses numeric proportions, preserves null and handles zero total without fabricated slices',()=>{const donut=chart('donut',{xScale:'category',data:[{x:'A',y:1},{x:'B',y:3},{x:'Missing',y:null}]});const{h,c}=setup(donut);assert.deepEqual([...h.querySelectorAll('[data-share]')].map(e=>Number(e.dataset.share)),[.25,.75]);assert.match(h.textContent,/Missing/);c.dispose();const zero=setup({...donut,data:[{x:'A',y:0}]});assert.equal(zero.h.querySelectorAll('[data-share]').length,0);assert.match(zero.h.textContent,/No data/);zero.c.dispose();invalid({...donut,data:[{x:'A',y:-1}]},'CHART_DONUT');});
test('axis types, chronological order and domain integrity reject misleading plots',()=>{invalid(chart('line',{data:[{x:'1',y:2}]}),'CHART_X');invalid(chart('line',{data:[{x:1,y:2},{x:1,y:3}]}),'CHART_ORDER');invalid(chart('line',{xScale:'time',data:[{x:'2026-02-30T00:00:00Z',y:1}]}),'CHART_X');invalid(chart('scatter',{xScale:'category'}),'CHART_AXIS');invalid(chart('line',{xMax:10}),'CHART_BOUNDS');invalid(chart('line',{timezone:'invalid/zone'}),'TIMEZONE');const r=validateDocument({version:'iui/1',state:{x:1},body:[chart('line',{xMin:0,xMax:5,data:[{x:{$:'x'},y:2}]})]});assert.equal(r.ok,true);assert.equal(evaluateState(r.document,{x:9}).ok,false);});
