import test from 'node:test';import assert from 'node:assert/strict';import{JSDOM}from'jsdom';import{validateDocument,mount}from'../dist/index.js';
const unit=(patch={})=>({type:'unit-converter',category:'length',amount:1,from:'m',to:'cm',...patch});
const currency=(patch={})=>({type:'currency-converter',amount:1,base:'USD',from:'AAA',to:'BBB',source:{label:'Original synthetic rates',synthetic:true},asOf:'2026-10-09T00:00:00Z',rates:[{currency:'AAA',rate:0.8},{currency:'BBB',rate:160}],...patch});
const doc=node=>({version:'iui/1',body:[node]});
const reject=(n,code)=>{const r=validateDocument(doc(n));assert.equal(r.ok,false);assert.ok(r.issues.some(i=>i.code===code),JSON.stringify(r));};
function result(n){const d=new JSDOM('<html lang="en"><div id="host"></div></html>'),host=d.window.document.getElementById('host'),c=mount(host,doc(n));const value=host.querySelector('output').dataset.rawValue;c.dispose();return value===undefined?null:Number(value);}
test('unit membership, temperature mode and precision enforce explicit contracts',()=>{reject(unit({from:'kg'}),'UNIT_ID');reject(unit({to:'unknown'}),'SCHEMA');reject(unit({temperatureMode:'difference'}),'UNIT_MODE');for(const precision of [0,13,1.5])reject(unit({precision}),'SCHEMA');});
test('absolute zero boundaries use source-unit definitions and differences remain signed',()=>{for(const[from,amount]of[['K',-Number.MIN_VALUE],['C',-273.15001],['F',-459.67001]])reject(unit({category:'temperature',from,to:'K',amount}),'UNIT_RANGE');for(const[from,amount]of[['K',0],['C',-273.15],['F',-459.67]])assert.equal(result(unit({category:'temperature',from,to:'K',amount})),0);assert.equal(result(unit({category:'temperature',from:'C',to:'F',amount:-300,temperatureMode:'difference'})),-540);});
test('unit definitions independently cover imperial, SI, time and binary quantities',()=>{for(const[category,from,to,amount,expected]of[['length','mi','m',1,1609.344],['length','nmi','m',1,1852],['mass','lb','kg',1,.45359237],['volume','gal-us','L',1,3.785411784],['volume','gal-imp','L',1,4.54609],['pressure','atm','Pa',1,101325],['time','d','s',1,86400],['data','MiB','MB',1,1.048576],['area','acre','m2',1,4046.8564224]])assert.ok(Math.abs(result(unit({category,from,to,amount}))/expected-1)<1e-12);});
test('unrepresentable unit results are explicit errors, not zero or infinity',()=>{reject(unit({amount:Number.MAX_VALUE}),'UNIT_RANGE');reject(unit({amount:Number.MIN_VALUE,from:'mm',to:'km'}),'UNIT_RANGE');assert.equal(result(unit({amount:0,from:'mm',to:'km'})),0);});
test('snapshot currencies, rate identities, dates and source URLs are validated',()=>{reject(currency({rates:[{currency:'AAA',rate:1},{currency:'AAA',rate:2}]}),'CURRENCY_ID');for(const rate of [0,-1])reject(currency({rates:[{currency:'AAA',rate}]}),'SCHEMA');for(const rate of [null,2])reject(currency({rates:[{currency:'USD',rate}]}),'CURRENCY_RATE');reject(currency({to:'ZZZ'}),'CURRENCY_ID');reject(currency({asOf:'2026-02-30T00:00:00Z'}),'CURRENCY_DATE');reject(currency({source:{label:'Bad link',synthetic:true,url:'javascript:alert(1)'}}),'UNSAFE_URL');});
test('extreme finite rates avoid overflow and underflow in intermediate ratios',()=>{const rates=(a,b)=>[{currency:'AAA',rate:a},{currency:'BBB',rate:b}];for(const[amount,a,b,expected]of[[0,1e-308,1e308,0],[1e-308,1e-308,1e308,1e308],[1e308,1e308,1e-308,1e-308],[Number.MIN_VALUE,Number.MIN_VALUE,Number.MIN_VALUE,Number.MIN_VALUE],[Number.MAX_VALUE,Number.MAX_VALUE,Number.MAX_VALUE,Number.MAX_VALUE],[-1e-308,1e-308,1e308,-1e308]]){const actual=result(currency({amount,rates:rates(a,b)}));if(expected===0)assert.equal(actual,0);else assert.ok(Math.abs(actual/expected-1)<1e-14,`${actual} != ${expected}`);}reject(currency({amount:1,rates:rates(1e-308,1e308)}),'CURRENCY_RANGE');reject(currency({amount:1,rates:rates(1e308,1e-308)}),'CURRENCY_RANGE');});
test('unknown rates stay unavailable at zero, while known identity needs no cross-rate',()=>{const n=currency({amount:0,rates:[{currency:'AAA',rate:null},{currency:'BBB',rate:1}]});assert.equal(validateDocument(doc(n)).ok,true);assert.equal(result(n),null);assert.equal(result({...n,amount:7,to:'AAA'}),7);assert.equal(validateDocument(doc(currency({rates:[],from:'USD',to:'USD'}))).ok,true);});
