import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';import {mount} from '../dist/index.js';
const business={version:'iui/1',body:[{type:'local-business',name:'Supplied',category:'Example',address:'Example',initialDay:'monday',hours:[{day:'monday',status:'closed',periods:[]},{day:'friday',status:'unknown',periods:[]}]}]};const product={version:'iui/1',body:[{type:'product-card',productId:'p',name:'Supplied',availability:'unknown'}]};
function setup(spec,kind){const dom=new JSDOM('<div id="outer"></div>'),doc=dom.window.document,outer=doc.getElementById('outer');let container=outer,gate=outer;if(kind==='shadow')container=outer.attachShadow({mode:'open'});if(kind==='closed-shadow')container=outer.attachShadow({mode:'closed'});if(kind==='nested'){const first=outer.attachShadow({mode:'open'}),inner=doc.createElement('div');first.append(inner);container=inner.attachShadow({mode:'open'});}if(kind==='slot'){const shadow=outer.attachShadow({mode:'open'});shadow.innerHTML='<section><slot name="content"></slot></section>';gate=shadow.querySelector('section');}const form=doc.createElement('form'),host=doc.createElement('main');if(kind==='slot')form.slot='content';form.append(host);container.append(form);const controller=mount(host,spec);return{dom,doc,outer,gate,form,host,controller,end(){controller.dispose();dom.window.close();}};}
const flush=async()=>{await Promise.resolve();await Promise.resolve();};
for(const kind of['ordinary','shadow','closed-shadow','nested','slot'])for(const flag of['hidden','inert']){
 test(`reader blocks ${flag} across ${kind} ancestors`,()=>{const x=setup(business,kind),select=x.host.querySelector('select');x.gate.setAttribute(flag,'');select.value='friday';select.dispatchEvent(new x.dom.window.Event('change'));assert.equal(select.value,'monday');x.gate.removeAttribute(flag);select.value='friday';select.dispatchEvent(new x.dom.window.Event('change'));assert.equal(select.value,'friday');x.end();});
 test(`choice blocks ${flag} across ${kind} ancestors`,()=>{const x=setup(product,kind);let count=0;x.host.addEventListener('iui:product-choice',()=>count++);x.gate.setAttribute(flag,'');x.host.querySelector('.iui-product-review').dispatchEvent(new x.dom.window.MouseEvent('click'));assert.equal(count,0);x.gate.removeAttribute(flag);x.host.querySelector('.iui-product-review').click();assert.equal(count,1);x.end();});
 test(`native reset preserves local draft under ${flag} ${kind} ancestor`,async()=>{const x=setup(business,kind),select=x.host.querySelector('select');select.value='friday';select.dispatchEvent(new x.dom.window.Event('change'));x.gate.setAttribute(flag,'');x.form.reset();await flush();assert.equal(select.value,'friday');x.gate.removeAttribute(flag);x.form.reset();await flush();assert.equal(select.value,'monday');x.end();});
}
test('shadow ancestry guard does not invent cross-shadow disabled fieldset inheritance',()=>{const dom=new JSDOM('<fieldset disabled><div></div></fieldset>'),outer=dom.window.document.querySelector('div'),shadow=outer.attachShadow({mode:'open'});shadow.innerHTML='<main></main>';const host=shadow.querySelector('main'),controller=mount(host,product),button=host.querySelector('.iui-product-review');assert.equal(button.matches(':disabled'),false);let count=0;host.addEventListener('iui:product-choice',()=>count++);button.click();assert.equal(count,1);controller.dispose();dom.window.close();});
test('native first-legend disabled fieldset exception remains intact',()=>{const dom=new JSDOM('<fieldset disabled><legend><main></main></legend></fieldset>'),host=dom.window.document.querySelector('main'),controller=mount(host,product);let count=0;host.addEventListener('iui:product-choice',()=>count++);host.querySelector('.iui-product-review').click();assert.equal(count,1);controller.dispose();dom.window.close();});
