import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import {mount,validateDocument,compileHtml} from '../dist/index.js';
const fixture=JSON.parse(await readFile(new URL('../examples/sports.json',import.meta.url)));
const states=JSON.parse(await readFile(new URL('../examples/sports/states.json',import.meta.url)));
const input=()=>structuredClone(fixture);
const nodes=spec=>spec.body.filter(n=>n.type.startsWith('sports-'));
function setup(spec=input(),lang='zh-CN'){const dom=new JSDOM(`<!doctype html><html lang="${lang}"><body><div id="host"></div></body></html>`,{url:'https://example.org'}),host=dom.window.document.getElementById('host'),controller=mount(host,spec);return{dom,host,controller,schedule:host.querySelector('.iui-sports-schedule'),board:host.querySelector('.iui-sports-scoreboard'),standings:host.querySelector('.iui-sports-standings')};}
function choose(dom,root,selector,label){const control=root.querySelector(selector),option=[...control.options].find(o=>o.textContent.includes(label));assert.ok(option,label);control.value=option.value;control.dispatchEvent(new dom.window.Event('change',{bubbles:true}));}
const rows=root=>[...root.querySelectorAll('tbody [data-team-id]')].map(row=>row.dataset.teamId);

test('sports example and all state fixtures validate; compiler is deterministic without changing input',async()=>{const before=input();assert.equal(validateDocument(fixture).ok,true);for(const state of Object.values(states))assert.equal(validateDocument(state).ok,true);assert.equal(await compileHtml(fixture),await compileHtml(fixture));assert.deepEqual(fixture,before);});
test('schedule sorts actual instants and groups by location date including repeated DST hour',()=>{const{schedule,controller}=setup();assert.deepEqual([...schedule.querySelectorAll('[data-game-id]')].map(e=>e.dataset.gameId),['live','final','tomorrow','postponed','cancelled']);assert.equal(schedule.querySelectorAll('.iui-sports-day').length,3);assert.match(schedule.querySelector('[data-game-id="live"] time').textContent,/GMT-7 01:00/);assert.match(schedule.querySelector('[data-game-id="final"] time').textContent,/GMT-8 01:00/);assert.match(schedule.querySelector('[data-game-id="tomorrow"] time').textContent,/GMT-8 18:30/);assert.match(schedule.textContent,/数据快照，不自动刷新/);controller.dispose();});
test('zero scores stay zero, missing scores stay missing, winner is supplied rather than guessed',()=>{const{schedule,board,dom,controller}=setup();assert.deepEqual([...schedule.querySelectorAll('[data-game-id="live"] .iui-sports-score')].map(e=>e.textContent),['0','0']);assert.equal(schedule.querySelectorAll('[data-game-id="tomorrow"] [data-missing="true"]').length,2);assert.equal(board.querySelectorAll('.iui-sports-winner').length,0);choose(dom,board,'select','青');assert.equal(board.querySelector('.iui-sports-board').dataset.gameId,'final');assert.equal(board.querySelectorAll('.iui-sports-winner').length,1);assert.match(board.textContent,/点球/);assert.match(board.textContent,/中立场地/);controller.dispose();});
test('schedule filters compose and details remain expanded after local filtering',()=>{const{dom,schedule,controller}=setup();schedule.querySelector('[data-game-id="live"]').open=true;choose(dom,schedule,'[data-sports-filter="team"]','天琴');assert.deepEqual([...schedule.querySelectorAll('[data-game-id]')].map(e=>e.dataset.gameId),['live','postponed']);assert.equal(schedule.querySelector('[data-game-id="live"]').open,true);choose(dom,schedule,'[data-sports-filter="stage"]','淘汰赛');assert.equal(schedule.querySelectorAll('[data-game-id]').length,0);assert.match(schedule.textContent,/没有符合筛选/);choose(dom,schedule,'[data-sports-filter="team"]','全部');assert.equal(schedule.querySelector('[data-game-id]').dataset.gameId,'final');controller.dispose();});
test('standings sort uses supplied tied ranks and negative points; missing numbers stay last both ways',()=>{const{standings,dom,controller}=setup();assert.deepEqual(rows(standings),['a','b','d','c']);standings.querySelector('[data-sort-key="points"]').click();assert.deepEqual(rows(standings),['a','b','c','d']);assert.equal(standings.querySelector('[data-sort-key="points"]').parentElement.getAttribute('aria-sort'),'descending');assert.equal(dom.window.document.activeElement.dataset.sortKey,'points');standings.querySelector('[data-sort-key="points"]').click();assert.deepEqual(rows(standings),['c','a','b','d']);assert.equal(standings.querySelector('[data-team-id="c"] td').textContent,'3');choose(dom,standings,'[data-sports-filter="group"]','另一组');assert.deepEqual(rows(standings),['d']);assert.match(standings.textContent,/缺测/);controller.dispose();});
test('empty/loading/error/no-match are readable states, not invented games',()=>{for(const name of ['loading','error','empty','noMatches']){const{host,controller}=setup(states[name]);for(const root of host.querySelectorAll('.iui-sports')){if(name==='loading'||name==='error'){assert.equal(root.dataset.status,name);assert.equal(root.getAttribute('aria-busy'),String(name==='loading'));assert.equal(root.querySelector('.iui-sports-body').hidden,true);assert.equal(root.querySelector('.iui-sports-status').getAttribute('role'),name==='error'?'alert':'status');}else assert.ok(root.querySelector('.iui-sports-empty'));assert.match(root.textContent,/合成演示/);}controller.dispose();}});
test('sports views preserve state and input, isolate mounts, and remove handlers on update/dispose',()=>{const spec=input();spec.state={untouched:'kept'};const before=structuredClone(spec),{host,dom,schedule,controller}=setup(spec);const second=dom.window.document.createElement('div');dom.window.document.body.append(second);const sibling=mount(second,input());choose(dom,schedule,'[data-sports-filter="team"]','天琴');assert.equal(second.querySelectorAll('.iui-sports-schedule [data-game-id]').length,5);assert.deepEqual(controller.getState(),{untouched:'kept'});assert.deepEqual(spec,before);for(let i=0;i<12;i++){const next=input();for(const n of nodes(next))n.status=i%2?'loading':'ready';controller.update(next);assert.equal(host.querySelectorAll('.iui-sports').length,3);}choose(dom,schedule,'[data-sports-filter="team"]','白桦');assert.equal(schedule.querySelectorAll('[data-game-id]').length,2);controller.update(input());const current=host.querySelector('.iui-sports'),bad=input();nodes(bad)[0].data.teams=[];assert.throws(()=>controller.update(bad));assert.equal(host.querySelector('.iui-sports'),current);controller.dispose();assert.equal(host.childElementCount,0);assert.equal(second.querySelectorAll('.iui-sports').length,3);sibling.dispose();});
test('sports text is escaped, resource links are inert until navigation, labels are localized',()=>{const spec=input();for(const node of nodes(spec)){node.data.teams[0].name='<img src=x onerror=alert(1)>';node.data.source.url='https://example.org/sports';}const{host,controller}=setup(spec,'en');assert.equal(host.querySelectorAll('img,iframe,script').length,0);assert.match(host.textContent,/<img src=x onerror=alert\(1\)>/);assert.match(host.textContent,/Supplied snapshot/);const links=host.querySelectorAll('.iui-sports-source a');assert.equal(links.length,3);for(const a of links){assert.equal(a.rel,'noopener noreferrer');assert.equal(a.referrerPolicy,'no-referrer');}for(const select of host.querySelectorAll('select')){assert.ok(select.getAttribute('aria-label'));assert.ok(select.closest('label'));}controller.dispose();});
test('semantic validator rejects identity, date, status, record, filter and resource inconsistencies',()=>{const cases=[['SPORTS_ID',n=>n.data.teams.push(n.data.teams[0])],['SPORTS_ID',n=>n.data.games.push(n.data.games[0])],['SPORTS_TEAM',n=>n.data.games[0].homeTeam='absent'],['SPORTS_TEAM',n=>n.data.games[0].awayTeam=n.data.games[0].homeTeam],['SPORTS_DATE',n=>n.data.games[0].startAt='2026-02-30T00:00:00Z'],['SPORTS_DATE',n=>n.data.updatedAt='2026-02-30T00:00:00Z'],['TIMEZONE',n=>n.data.timezone='Invalid/Zone'],['SPORTS_STATUS',n=>n.data.games[0].homeScore=0],['SPORTS_RESULT',n=>n.data.games[0].winnerTeamId='a'],['SPORTS_STATUS',n=>n.data.games[0].tieBreak={label:'x',home:1,away:0}],['SPORTS_RECORD',n=>n.data.standings[0].played=5],['SPORTS_FILTER',n=>n.initialTeamId='unknown'],['SPORTS_FILTER',n=>n.initialStage='absent'],['SPORTS_DATE',n=>n.initialDate='2026-02-30'],['UNSAFE_URL',n=>n.data.source.url='javascript:alert(1)']];for(const[code,mutate]of cases){const spec=input();mutate(nodes(spec)[0]);const result=validateDocument(spec);assert.equal(result.ok,false,code);assert.ok(result.issues.some(i=>i.code===code),JSON.stringify(result.issues));}});
test('honest incomplete records, missing final scores and explicit empty filters remain valid',()=>{const spec=input(),all=nodes(spec);all[0].initialDate='2026-12-01';for(const n of all){n.data.standings[0].drawn=null;n.data.games.find(g=>g.id==='final').homeScore=null;}assert.equal(validateDocument(spec).ok,true);const{schedule,controller}=setup(spec);assert.ok(schedule.querySelector('.iui-sports-empty'));controller.dispose();});
