import test from 'node:test';import assert from 'node:assert/strict';import {readFile,mkdtemp,mkdir,cp,writeFile,rm,symlink} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {glyphLookup,requiredCjk,verifyFont} from '../scripts/prepare-test-font.mjs';
const root=process.cwd(),relative='tests/assets/fonts/noto-cjk-sc',font=await readFile(path.join(relative,'NotoSansCJKsc-Regular.otf'));
async function fixture(t){const dir=await mkdtemp(path.join(tmpdir(),'inform-font-test-'));t.after(()=>rm(dir,{recursive:true,force:true}));await mkdir(path.join(dir,'tests/assets/fonts'),{recursive:true});await cp(relative,path.join(dir,relative),{recursive:true});return dir;}
test('pinned OFL font covers every current CJK fixture and renderer label glyph',async()=>{const result=await verifyFont(root),codes=await requiredCjk(root);assert.equal(result.family,'Noto Sans CJK SC');assert.equal(result.fontBytes,16437364);assert.ok(result.requiredGlyphCount>800);for(const char of '中文汉漢测试測試')assert.ok(codes.includes(char.codePointAt(0)));});
test('actual Unicode cmap has Chinese glyphs and rejects missing glyph or invalid scalar',()=>{const has=glyphLookup(font);for(const char of '中文汉漢测试測試')assert.equal(has(char.codePointAt(0)),true);assert.equal(has(0x10ffff),false);assert.equal(has(-1),false);assert.equal(has(0x110000),false);assert.equal(has(1.5),false);});
test('absent required glyph fails instead of silently accepting fallback tofu',async()=>{await assert.rejects(verifyFont(root,{required:[0x10ffff]}),/lacks required CJK glyphs/);});
test('corrupted font is rejected before install',async t=>{const dir=await fixture(t),bytes=Buffer.from(font);bytes[bytes.length-1]^=1;await writeFile(path.join(dir,relative,'NotoSansCJKsc-Regular.otf'),bytes);await assert.rejects(verifyFont(dir,{required:[0x4e2d]}),/hash differs/);});
test('missing or changed license is rejected',async t=>{const dir=await fixture(t);await writeFile(path.join(dir,relative,'OFL.txt'),'missing license');await assert.rejects(verifyFont(dir,{required:[0x4e2d]}),/byte count differs/);});
test('lock cannot redirect the approved font filename',async t=>{const dir=await fixture(t),file=path.join(dir,relative,'font-lock.json'),lock=JSON.parse(await readFile(file,'utf8'));lock.file='../other.otf';await writeFile(file,JSON.stringify(lock));await assert.rejects(verifyFont(dir,{required:[0x4e2d]}));});
test('truncated and malformed SFNT headers fail closed',()=>{for(const bytes of [Buffer.alloc(0),Buffer.from('OTTO'),Buffer.alloc(12)])assert.throws(()=>glyphLookup(bytes));const bytes=Buffer.alloc(28);bytes.write('OTTO');bytes.writeUInt16BE(1,4);bytes.write('cmap',12);bytes.writeUInt32BE(1000,20);bytes.writeUInt32BE(1000,24);assert.throws(()=>glyphLookup(bytes),/outside file bounds/);});
test('font symlinks cannot substitute unchecked outside bytes',async t=>{const dir=await fixture(t),file=path.join(dir,relative,'NotoSansCJKsc-Regular.otf');await rm(file);await symlink(path.join(root,relative,'NotoSansCJKsc-Regular.otf'),file);await assert.rejects(verifyFont(dir,{required:[0x4e2d]}),/ordinary files/);});
test('browser job installs pinned local font without apt CJK download or glyph suppression',async()=>{const workflow=await readFile('.github/workflows/ci.yml','utf8');assert.ok(workflow.includes('node scripts/prepare-test-font.mjs --install'));assert.ok(workflow.includes('FONTCONFIG_FILE='));assert.ok(!workflow.includes('fonts-noto-cjk'));assert.ok(workflow.includes('npm run test:browser'));});
