import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import {mount,validateDocument,compileHtml} from '../dist/index.js';
import {validateDocument as browserValidate} from '../dist/browser.js';
import Ajv from 'ajv/dist/2020.js';
const fixture=JSON.parse(await readFile(new URL('../examples/supplied-trackers.json',import.meta.url)));
const input=(index,change=()=>{})=>{const spec=structuredClone(fixture);if(index!==undefined)spec.body=[spec.body[index]];change(spec.body[0]);return spec;};
function setup(spec=input(),markup='<main></main>',options={}){const dom=new JSDOM(`<html lang="en"><body>${markup}</body></html>`,{url:'https://example.org/'}),host=dom.window.document.querySelector('main'),controller=mount(host,spec,options);return{dom,host,controller,root:host.querySelector('.iui-tracker'),end(){controller.dispose();dom.window.close();}};}
const change=(x,select,value)=>{select.value=value;select.dispatchEvent(new x.dom.window.Event('change',{bubbles:true}));};
const shown=root=>[...root.querySelectorAll('.iui-tracker-record:not([hidden])')].map(x=>x.dataset.recordId);
const flush=async()=>{await Promise.resolve();await Promise.resolve();};

test('public validation and mounted snapshots preserve literal values, offsets and source order',()=>{const original=JSON.stringify(fixture);assert.equal(validateDocument(fixture).ok,true);assert.equal(browserValidate(fixture).ok,true);const x=setup();assert.equal(x.host.querySelectorAll('.iui-tracker').length,2);assert.deepEqual(shown(x.root),['label','hub','delivery']);const flight=x.host.querySelector('.iui-flight-tracker');assert.deepEqual(shown(flight),['boarding','gate','delay']);assert.equal(flight.querySelectorAll('.iui-tracker-missing').length,2);assert.match(flight.textContent,/2028-02-29T07:20-05:00/);assert.match(x.root.textContent,/No carrier connection/);assert.match(flight.textContent,/not live or verified/);assert.equal(JSON.stringify(fixture),original);x.end();});
test('schema definitions have one Base owner and strict standalone/document closure',async()=>{const full=JSON.parse(await readFile('src/schema/iui.schema.json','utf8')),index=JSON.parse(await readFile('src/schema/fragments/index.json','utf8'));for(const name of ['package-tracker','flight-tracker'])assert.equal(index.nodeOwners[name],'base');for(const p of ['src/schema/fragments/base.schema.json','src/schema/iui.schema.json']){const schema=JSON.parse(await readFile(p,'utf8'));assert.equal(new Ajv({strict:true}).compile(schema)(fixture),true);}assert.ok(full.$defs.PackageTrackerNode);assert.ok(full.$defs.FlightTrackerNode);});
test('records can be empty or the bounded maximum without placeholder or inferred progress',()=>{for(const index of [0,1])for(const size of [0,40]){const x=setup(input(index,n=>{const key=index?'updates':'milestones',record=n[key][0];n[key]=Array.from({length:size},(_,i)=>({...record,id:'record'+i}));}));assert.equal(x.root.querySelectorAll('.iui-tracker-record').length,size);assert.equal(x.root.querySelector('.iui-tracker-empty').hidden,size>0);assert.equal(x.root.querySelector('[role=progressbar]'),null);assert.equal(x.root.querySelector('img,video,iframe,canvas,svg'),null);x.end();}});
test('local filters keep details, row identity and focus across unrelated state; reset is repeatable',()=>{for(const index of [0,1]){const x=setup(input(index)),select=x.root.querySelector('select'),reset=x.root.querySelector('button'),rows=[...x.root.querySelectorAll('li')],details=x.root.querySelector('details');details.open=true;select.focus();change(x,select,index?'disruption':'pending');assert.equal(shown(x.root).length,1);assert.equal(x.dom.window.document.activeElement,select);x.controller.setState({other:2});assert.equal(select.value,index?'disruption':'pending');assert.equal(details.open,true);assert.deepEqual([...x.root.querySelectorAll('li')],rows);reset.focus();for(let i=0;i<4;i++)reset.click();assert.equal(reset.getAttribute('aria-disabled'),'true');assert.equal(shown(x.root).length,3);assert.equal(x.dom.window.document.activeElement,reset);assert.deepEqual(x.controller.getState(),{other:2});x.end();}});
test('no-match is explicit; invalid, hidden, inert and detached forged actions restore the local filter',()=>{const x=setup(input(0,n=>{n.milestones=n.milestones.slice(0,1);})),select=x.root.querySelector('select'),reset=x.root.querySelector('button');change(x,select,'pending');assert.equal(shown(x.root).length,0);assert.match(x.root.querySelector('.iui-tracker-empty').textContent,/No supplied records match/);change(x,select,'not-a-category');assert.equal(select.value,'pending');for(const flag of ['hidden','inert']){x.root.setAttribute(flag,'');change(x,select,'complete');reset.dispatchEvent(new x.dom.window.MouseEvent('click',{bubbles:true}));assert.equal(select.value,'pending');x.root.removeAttribute(flag);}x.host.remove();change(x,select,'complete');assert.equal(select.value,'pending');x.end();});
test('inherited disabled and native first legend exception are respected',()=>{for(const legend of [false,true]){const x=setup(input(),legend?'<fieldset disabled><legend><main></main></legend></fieldset>':'<fieldset disabled><main></main></fieldset>'),select=x.root.querySelector('select');assert.equal(select.matches(':disabled'),!legend);change(x,select,'current');assert.equal(select.value,legend?'current':'');x.dom.window.document.querySelector('fieldset').disabled=false;change(x,select,'current');assert.equal(select.value,'current');x.end();}});
test('outer reset, cancellation, disabled/inert reset and newer local input preserve coherent visibility',async()=>{for(const index of [0,1]){const x=setup(input(index),'<form><fieldset><main></main></fieldset></form>'),select=x.root.querySelector('select'),form=x.dom.window.document.querySelector('form'),field=x.dom.window.document.querySelector('fieldset'),first=index?'change':'current',second=index?'disruption':'pending';change(x,select,first);form.addEventListener('reset',e=>e.preventDefault(),{once:true});form.reset();await flush();assert.equal(select.value,first);field.disabled=true;form.reset();await flush();assert.equal(select.value,first);field.disabled=false;x.root.setAttribute('inert','');form.reset();await flush();assert.equal(select.value,first);x.root.removeAttribute('inert');form.reset();change(x,select,second);await flush();assert.equal(select.value,second);form.reset();await flush();assert.equal(select.value,'');assert.equal(shown(x.root).length,3);assert.deepEqual([...new x.dom.window.FormData(form).entries()],[]);x.end();}});
test('native resets in shadow roots and a later disabled ancestor remain local',async()=>{const dom=new JSDOM('<div></div>'),shadow=dom.window.document.querySelector('div').attachShadow({mode:'open'});shadow.innerHTML='<form><fieldset><main></main></fieldset></form>';const host=shadow.querySelector('main'),controller=mount(host,input(0)),root=host.querySelector('.iui-tracker'),select=root.querySelector('select'),form=shadow.querySelector('form');select.value='pending';select.dispatchEvent(new dom.window.Event('change'));form.reset();await flush();assert.equal(select.value,'');assert.equal(shown(root).length,3);select.value='pending';select.dispatchEvent(new dom.window.Event('change'));form.addEventListener('reset',()=>shadow.querySelector('fieldset').disabled=true,{once:true});form.reset();await flush();assert.equal(select.value,'pending');assert.equal(shown(root).length,1);controller.dispose();dom.window.close();});
test('document Forms pending blocks forged filters but does not bind tracker data or prevent reading',async()=>{let finish,snapshot;const spec=input();spec.body=[{type:'form',label:'Local',action:'save',children:[{type:'input',kind:'text',label:'Other',bind:'note'},...spec.body]}];spec.state.note='Only bound value';const x=setup(spec,'<main></main>',{actions:{save:ctx=>{snapshot=ctx.values;return new Promise(resolve=>finish=resolve);}}}),form=x.host.querySelector('form'),select=x.root.querySelector('select');change(x,select,'current');form.dispatchEvent(new x.dom.window.Event('submit',{bubbles:true,cancelable:true}));assert.equal(select.matches(':disabled'),true);change(x,select,'pending');x.root.querySelector('button').dispatchEvent(new x.dom.window.MouseEvent('click',{bubbles:true}));assert.equal(select.value,'current');assert.deepEqual(snapshot,{note:'Only bound value'});const link=x.root.querySelector('a');let canceled;link.addEventListener('click',e=>{canceled=e.defaultPrevented;e.preventDefault();});link.dispatchEvent(new x.dom.window.MouseEvent('click',{bubbles:true,cancelable:true}));assert.equal(canceled,false);finish();await flush();assert.equal(select.matches(':disabled'),false);assert.equal(select.value,'current');x.end();});
test('invalid updates are atomic, valid replacement resets filters, and queued disposed callbacks retire',async()=>{for(const action of ['update','dispose']){const x=setup(input(0),'<form><main></main></form>'),select=x.root.querySelector('select');change(x,select,'current');const before=x.host.innerHTML;assert.throws(()=>x.controller.update(input(0,n=>{n.milestones[0].state='bad';})));assert.equal(x.host.innerHTML,before);x.dom.window.document.querySelector('form').reset();if(action==='update')x.controller.update(input(0));else x.controller.dispose();const retired=x.root.outerHTML;select.dispatchEvent(new x.dom.window.Event('change'));x.root.querySelector('button').click();await flush();assert.equal(x.root.outerHTML,retired);if(action==='update')assert.equal(x.host.querySelector('select').value,'');else assert.equal(x.host.childElementCount,0);x.end();}});
test('ownerDocument, namespaced ARIA labels and literal hostile text stay independent across mounts',()=>{const spec=input(0,n=>{n.label='<img onerror=bad()> & literal';n.milestones[0].description='<script>bad()</script>';});const x=setup(spec),second=x.dom.window.document.createElement('div');x.host.after(second);const ctrl=mount(second,spec);assert.equal(x.host.querySelector('img,script'),null);assert.match(x.root.textContent,/<img onerror=bad\(\)>/);const ids=[...x.dom.window.document.querySelectorAll('[id]')].map(el=>el.id);assert.equal(new Set(ids).size,ids.length);for(const el of x.host.querySelectorAll('[aria-labelledby],[aria-describedby],[for]'))for(const attr of ['aria-labelledby','aria-describedby','for'])for(const id of (el.getAttribute(attr)??'').split(/\s+/).filter(Boolean))assert.ok(x.dom.window.document.getElementById(id));const link=x.root.querySelector('a');assert.equal(link.rel,'noopener noreferrer');assert.equal(link.target,'_blank');assert.equal(link.referrerPolicy,'no-referrer');ctrl.dispose();x.end();});
test('Chinese labels, unknown status and missing actual times are explicit, never zero or invented',()=>{const x=setup(input(1,n=>{n.status='unknown';}),'<main lang="zh-CN"></main>');assert.equal(x.root.querySelector('.iui-tracker-status').textContent,'状态未知');assert.equal(x.root.querySelectorAll('.iui-tracker-missing').length,2);assert.match(x.root.textContent,/未提供/);assert.match(x.root.textContent,/不跟踪位置/);x.end();});
test('compiler is deterministic and local filters schedule no provider timer or runtime network',async()=>{const a=await compileHtml(fixture);assert.equal(await compileHtml(fixture),a);assert.match(a,/Example shipment/);const x=setup();for(const method of ['fetch','setInterval','setTimeout'])x.dom.window[method]=()=>{throw Error('Unexpected '+method);};change(x,x.root.querySelector('select'),'pending');x.root.querySelector('button').click();assert.equal(x.root.querySelector('[name],[data-bind]'),null);x.end();});
for(const [name,index,mutate] of [
 ['missing observation',0,n=>delete n.observedAt],['provider endpoint',0,n=>n.endpoint='https://example.org/api'],['unknown action',1,n=>n.action='book'],['binding',1,n=>n.status={$:'status'}],['invalid status',0,n=>n.status='late'],['empty tracking ref',0,n=>n.trackingId=''],['lowercase airport',1,n=>n.departure.airport='lhr'],['newline airport',1,n=>n.departure.airport='LHR\n'],['missing schedule',1,n=>delete n.departure.scheduledAt],['extra endpoint field',1,n=>n.departure.latitude=1],['too many milestones',0,n=>n.milestones=Array(41).fill(n.milestones[0])],['too many updates',1,n=>n.updates=Array(41).fill(n.updates[0])],['unbounded text',0,n=>n.label='😀'.repeat(201)],['invalid offset',1,n=>n.observedAt='2028-02-29T10:00+14:01'],['no offset',0,n=>n.observedAt='2028-02-29T10:00'],['unsafe key',0,n=>n.milestones[0].id='x\n'],['incomplete source',0,n=>n.source={label:'Source'}]
])test('structural rejection: '+name,()=>{const value=input(index,mutate);assert.equal(validateDocument(value).ok,false);assert.equal(browserValidate(value).ok,false);assert.ok(validateDocument(value).issues.some(i=>i.code==='SCHEMA'));});
for(const [name,index,mutate,code,path] of [
 ['invalid observation date',0,n=>n.observedAt='2027-02-29T10:00Z','TRACKER_TIME','/observedAt'],['invalid milestone date',0,n=>n.milestones[0].occurredAt='2028-04-31T10:00Z','TRACKER_TIME','/milestones/0/occurredAt'],['duplicate milestone',0,n=>n.milestones[1].id=n.milestones[0].id,'DUPLICATE_ID','/milestones/1/id'],['two current milestones',0,n=>n.milestones[0].state='current','TRACKER_CURRENT','/milestones/1/state'],['occurred pending milestone',0,n=>n.milestones[0].state='pending','TRACKER_PENDING','/milestones/0/occurredAt'],['duplicate update',1,n=>n.updates[1].id=n.updates[0].id,'DUPLICATE_ID','/updates/1/id'],['invalid update date',1,n=>n.updates[0].at='2028-02-30T10:00Z','TRACKER_TIME','/updates/0/at'],['invalid flight endpoint',1,n=>n.arrival.scheduledAt='2028-02-30T10:00Z','TRACKER_TIME','/arrival/scheduledAt'],['arrival not after departure',1,n=>n.arrival.scheduledAt=n.departure.scheduledAt,'TRACKER_ORDER','/arrival/scheduledAt'],['estimated chronology',1,n=>n.arrival.estimatedAt=n.departure.estimatedAt,'TRACKER_ORDER','/arrival/estimatedAt'],['actual chronology',1,n=>{n.departure.actualAt='2028-02-29T10:00Z';n.arrival.actualAt='2028-02-29T09:00Z';},'TRACKER_ORDER','/arrival/actualAt'],
 ...['javascript:bad()','data:text/plain,x','/relative','mailto:x@example.org','https://u:p@example.org'].map(url=>['unsafe source '+url,0,n=>n.source.url=url,'UNSAFE_URL','/source/url'])
])test('semantic exact path: '+name,()=>{const result=validateDocument(input(index,mutate));assert.equal(result.ok,false);assert.ok(result.issues.some(i=>i.code===code&&i.path==='/body/0'+path),JSON.stringify(result.issues));});
test('source ordering is preserved even for supplied historical or unsorted updates, without current-clock inference',()=>{const x=setup(input(1,n=>{n.observedAt='1000-01-01T00:00Z';n.updates[0].at='9999-12-31T23:59Z';}));assert.deepEqual(shown(x.root),['boarding','gate','delay']);assert.match(x.root.textContent,/1000-01-01T00:00Z/);assert.equal(x.root.querySelector('.iui-tracker-status').textContent,'Boarding');x.end();});

test('hidden/inert control wrappers and individual reset buttons reject forged actions',async()=>{for(const flag of ['hidden','inert']){const x=setup(input(0),'<form><main></main></form>'),select=x.root.querySelector('select'),reset=x.root.querySelector('button'),wrapper=select.parentElement;change(x,select,'current');wrapper.setAttribute(flag,'');change(x,select,'pending');assert.equal(select.value,'current');x.dom.window.document.querySelector('form').reset();await flush();assert.equal(select.value,'current');wrapper.removeAttribute(flag);reset.setAttribute(flag,'');reset.dispatchEvent(new x.dom.window.MouseEvent('click',{bubbles:true}));assert.equal(select.value,'current');reset.removeAttribute(flag);reset.click();assert.equal(select.value,'');x.end();}});
test('tracker styles only consume defined theme tokens and contain no remote assets or motion',async()=>{const css=await readFile('src/renderer/style.css','utf8'),own=css.slice(css.indexOf('/* Original supplied shipment and flight snapshots;'));assert.doesNotMatch(own,/@import|https?:|url\(|animation:/);const defined=new Set([...css.matchAll(/(--iui-[\w-]+)\s*:/g)].map(x=>x[1]));for(const [,token] of own.matchAll(/var\((--iui-[\w-]+)/g))assert.ok(defined.has(token),token);assert.match(own,/\.iui-root \.iui-tracker \[hidden\]/);assert.match(own,/min-block-size:44px/);assert.match(own,/forced-colors/);});

test('independently detached or reparented tracker controls cannot mutate mounted records',()=>{for(const reparent of [false,true]){const x=setup(input(0)),select=x.root.querySelector('select'),reset=x.root.querySelector('button');change(x,select,'current');if(reparent)x.dom.window.document.body.append(select,reset);else{select.remove();reset.remove();}change(x,select,'pending');reset.dispatchEvent(new x.dom.window.MouseEvent('click',{bubbles:true}));assert.equal(select.value,'current');assert.deepEqual(shown(x.root),['hub']);x.end();}});
