/** Original later-batch compiled consumer. Prepared, not yet browser-accepted. */
import assert from 'node:assert/strict';import{readFile,writeFile,mkdir,mkdtemp,rm}from'node:fs/promises';import path from'node:path';import{tmpdir}from'node:os';import{fileURLToPath,pathToFileURL}from'node:url';import{createRequire}from'node:module';import{spawnSync}from'node:child_process';
const root=path.dirname(fileURLToPath(import.meta.url));function arg(flag){const i=process.argv.indexOf(flag);if(i<0)return;const v=process.argv[i+1];assert.ok(v&&!v.startsWith('--'));return v;}
assert.ok(arg('--library'));const library=path.resolve(arg('--library')),revision=arg('--revision');assert.match(revision??'',/^[a-f0-9]{40}$/);const git=spawnSync('git',['-C',library,'rev-parse','HEAD'],{encoding:'utf8'});assert.equal(git.status,0,git.stderr);assert.equal(git.stdout.trim(),revision);
const pkg=JSON.parse(await readFile(path.join(library,'package.json'),'utf8'));const{validateDocument,compileHtml}=await import(pathToFileURL(path.resolve(library,pkg.exports['.'].import)).href);const require=createRequire(path.join(library,'package.json')),{chromium,expect}=require('@playwright/test');
const shots=path.resolve(arg('--screenshots')??path.join(root,'artifacts/browser'));await mkdir(shots,{recursive:true});const temporary=await mkdtemp(path.join(tmpdir(),'inform-pie-consumer-'));const name='known-value-pie',input=JSON.parse(await readFile(path.join(root,'examples',name+'.json'),'utf8'));const checked=validateDocument(input);assert.equal(checked.ok,true,JSON.stringify(checked.issues));let browser,count=0;
try{browser=await chromium.launch({headless:true,...(process.env.IUI_BROWSER_EXECUTABLE?{executablePath:process.env.IUI_BROWSER_EXECUTABLE}:{})});
for(const theme of ['light','dark'])for(const width of [390,768,1100]){
 const label=`${name}-${theme}-${width}`,file=path.join(temporary,label+'.html');await writeFile(file,await compileHtml({...input,theme},{assets:'inline',backend:'portable',lang:'zh-CN'}));
 const page=await browser.newPage({viewport:{width,height:1050},colorScheme:theme,reducedMotion:'reduce'}),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});
 await page.goto(pathToFileURL(file).href);await page.waitForSelector('.iui-root');await page.evaluate(()=>document.fonts.ready);
 const figure=page.locator('[data-iui=chart][id$="-known-pie"]'),graphic=figure.locator('svg'),readout=figure.locator('output'),details=figure.locator('details');
 await expect(graphic.locator('path[data-point]')).toHaveCount(3);await expect(figure.locator('tbody tr')).toHaveCount(5);await expect(figure.locator('.iui-pie-denominator')).toContainText('已知数值之和');
 // Real mouse hit in the first sector, via the actual SVG screen matrix.
 const point=await graphic.evaluate(svg=>{const p=svg.createSVGPoint();p.x=svg.viewBox.baseVal.width/2+30;p.y=112-Math.sqrt(3)*30;const q=p.matrixTransform(svg.getScreenCTM());return{x:q.x,y:q.y};});
 await page.mouse.move(point.x,point.y);await expect(figure.locator('.iui-pie-key-active')).toHaveAttribute('data-item','0');await expect(graphic).not.toBeFocused();
 await graphic.focus();await page.keyboard.press('End');await expect(figure.locator('.iui-pie-key-active')).toHaveAttribute('data-item','4');await expect(readout).toContainText('未提供');await page.keyboard.press('ArrowRight');await expect(figure.locator('.iui-pie-key-active')).toHaveAttribute('data-item','4');
 await page.keyboard.press('ArrowLeft');await expect(readout).toContainText('已知零');await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');await expect(figure.locator('.iui-pie-key-active')).toHaveAttribute('data-item','1');await expect(readout).toContainText('33.3%');
 await figure.locator('summary').click();await expect(details).toHaveAttribute('open','');await graphic.evaluate(el=>{window.consumerPieGraphic=el;window.consumerPieDetails=el.closest('figure').querySelector('details');});
 const slider=page.getByRole('slider',{name:'第一行甲的合成份数',exact:true});await slider.focus();await page.keyboard.press('End');await expect(slider).toBeFocused();await expect(readout).toContainText('18.2%');await expect(figure.locator('.iui-pie-key-active')).toHaveAttribute('data-item','1');
 assert.equal(await graphic.evaluate(el=>el===window.consumerPieGraphic&&el.closest('figure').querySelector('details')===window.consumerPieDetails),true);await expect(details).toHaveAttribute('open','');
 const empty=page.locator('[data-iui=chart][id$="-empty-pie"]');await expect(empty.locator('svg')).toBeHidden();await expect(empty.locator('path')).toHaveCount(0);await empty.locator('summary').click();await expect(empty.locator('tbody tr')).toHaveCount(2);
 await page.getByRole('button',{name:'恢复合成初值',exact:true}).click();await expect(slider).toHaveValue('1');await expect(details).toHaveAttribute('open','');await graphic.focus();await page.keyboard.press('Home');await expect(graphic).toBeFocused();assert.notEqual(await graphic.evaluate(el=>getComputedStyle(el).outlineStyle),'none');
 assert.equal(await graphic.evaluate(el=>/NaN|Infinity/.test(el.innerHTML)),false);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),label+': whole-page overflow');assert.deepEqual(errors,[]);assert.deepEqual(external,[]);await page.screenshot({path:path.join(shots,label+'.png'),fullPage:true});await page.close();count++;console.log(`PASS ${label}`);
}
await writeFile(path.join(shots,'RESULTS.json'),JSON.stringify({revision,exampleLanguages:{"known-value-pie":"zh-CN"},localCompiledViews:count,widths:[390,768,1100],themes:['light','dark'],browser:'chromium',publicCdn:'not-run',screenReader:'not-run',screenshotReview:'pending-human-review'},null,2)+'\n');
}finally{await browser?.close();await rm(temporary,{recursive:true,force:true});}
