import type {Node} from '../schema/document.js';
import type {Issue} from './index.js';

export type VocabCardNode = Extract<Node, {type:'vocab-card'}>;

/** Structural fields are generated by the public schema; sense identity is local. */
export function inspectVocabCard(node:VocabCardNode, path:string, add:(issue:Issue)=>void):void {
  const seen = new Set<string>();
  node.senses.forEach((sense, index) => {
    if (seen.has(sense.id)) add({code:'VOCAB_SENSE_ID', path:`${path}/senses/${index}/id`, message:'Sense ids must be unique within a vocabulary card.'});
    seen.add(sense.id);
  });
}
