/** Project-owned iui/1 schema construction. No external runtime code is used. */
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';

const string = (maxLength = 12000, minLength) => ({ type: 'string', ...(minLength === undefined ? {} : { minLength }), maxLength });
const short = string(200, 1);
const number = { type: 'number' };
const bool = { type: 'boolean' };
const integer = (minimum, maximum) => ({ type: 'integer', minimum, maximum });
const choice = (...values) => ({ enum: values });
const array = (items, minItems = 0, maxItems = 500) => ({ type: 'array', items, minItems, maxItems });
const object = (properties, required = []) => ({ type: 'object', properties, required, additionalProperties: false });
const ref = (name) => ({ $ref: `#/$defs/${name}` });
const key = { type: 'string', pattern: '^[A-Za-z_][A-Za-z0-9_.-]{0,79}$' };
const color = choice('default', 'secondary', 'tertiary', 'success', 'warning', 'danger', 'info', 'accent');
const weight = choice('normal', 'medium', 'semibold', 'bold');
const align = choice('start', 'center', 'end');
const children = array(ref('Node'));
const scalar = { anyOf: [string(), number, bool] };
const nodes = [];
const defs = {};
const node = (name, props = {}, required = []) => {
  const nameInSchema = name.split('-').map((s) => s[0].toUpperCase() + s.slice(1)).join('') + 'Node';
  defs[nameInSchema] = object({ type: { const: name }, id: short, ...props }, ['type', ...required]);
  nodes.push(ref(nameInSchema));
};

defs.Value = { oneOf: [string(), number, bool, { type: 'null' }, object({ $: { ...key, minLength: 1 } }, ['$']), object({ op: choice('add', 'sub', 'mul', 'div', 'max', 'min', 'round', 'abs', 'clamp', 'gt', 'lt', 'eq', 'if', 'format'), args: array(ref('Value'), 1, 12) }, ['op', 'args'])] };
for (const name of ['text', 'title', 'caption']) node(name, { value: ref('Value'), color, weight, align, ...(name === 'title' ? { level: integer(1, 3) } : {}) }, ['value']);
node('markdown', { value: string() }, ['value']);
node('code', { value: string(), language: short }, ['value']);
node('math', { latex: string(6000, 1), block: bool }, ['latex']);
node('badge', { value: ref('Value'), color }, ['value']);
node('divider');
node('spacer', { height: integer(0, 200) });
node('link', { value: ref('Value'), href: string(2048, 1) }, ['value', 'href']);
node('image', { src: string(500000, 1), alt: string(), aspectRatio: choice('1:1', '4:3', '16:9', '3:4'), fit: choice('cover', 'contain') }, ['src', 'alt']);
const layout = { gap: integer(0, 16), padding: integer(0, 16), radius: choice('none', 'sm', 'md', 'lg', 'xl', '2xl'), border: bool, background: choice('none', 'surface', 'surface-secondary', 'surface-tertiary', 'success-soft', 'danger-soft', 'info-soft'), align: choice('start', 'center', 'end', 'stretch'), justify: choice('start', 'center', 'end', 'between', 'around'), width: { anyOf: [integer(30, 1400), choice('100%', 'auto')] }, children };
for (const name of ['box', 'card', 'row', 'col', 'grid']) node(name, { ...layout, ...(name === 'grid' ? { columns: integer(1, 6) } : {}) }, ['children']);
node('section', { heading: string(), children }, ['children']);
node('figure', { children, caption: string() }, ['children']);
node('details', { summary: short, children }, ['summary', 'children']);
node('carousel', { children }, ['children']);
node('list', { ordered: bool, items: array({ anyOf: [ref('Value'), ref('Node')] }, 0, 100) }, ['items']);
node('table', { columns: array(short, 1, 20), rows: array(array(ref('Value'), 0, 20), 0, 200), caption: string() }, ['columns', 'rows']);
node('metric', { label: short, value: ref('Value'), unit: short, hint: string(), precision: integer(0, 6), color }, ['label', 'value']);
node('metric-grid', { children: array(ref('Node'), 1, 12), columns: integer(1, 4) }, ['children']);
node('steps', { items: array(object({ title: short, detail: string(), latex: string() }, ['title']), 1, 20) }, ['items']);
node('callout', { value: string(), tone: choice('neutral', 'info', 'caution') }, ['value']);
node('slider', { label: short, bind: short, min: number, max: number, step: { ...number, exclusiveMinimum: 0 }, unit: short, marks: array(object({ value: number, label: string() }, ['value', 'label']), 0, 30) }, ['label', 'bind', 'min', 'max', 'step']);
node('toggle', { label: short, bind: short }, ['label', 'bind']);
node('select', { label: short, bind: short, options: array(object({ value: { anyOf: [string(), number] }, label: short }, ['value', 'label']), 1, 40) }, ['label', 'bind', 'options']);
node('button', { label: short, action: object({ kind: choice('reset', 'set'), bind: short, value: scalar }, ['kind']) }, ['label', 'action']);
node('topology', { nodes: array(object({ id: short, label: short, subtitle: string() }, ['id', 'label']), 2, 24), links: array(object({ from: short, to: short, label: string(), load: ref('Value') }, ['from', 'to']), 1, 40), highlight: choice('max-load', 'none'), caption: string() }, ['nodes', 'links']);
node('chart', { kind: choice('line', 'bar'), xKey: short, data: array({ type: 'object', additionalProperties: ref('Value') }, 1, 300), series: array(object({ key: short, label: short, color: choice('blue', 'green', 'orange', 'red', 'purple', 'gray') }, ['key', 'label']), 1, 6), yMin: number, yMax: number, unit: string(), title: string(), note: string() }, ['kind', 'xKey', 'data', 'series']);
node('svg', { viewBox: { type: 'string', pattern: '^\\d+\\s+\\d+\\s+\\d+\\s+\\d+$' }, shapes: array(object({ tag: choice('rect', 'line', 'circle', 'path', 'text', 'polyline', 'polygon'), attrs: { type: 'object', maxProperties: 24, additionalProperties: { anyOf: [string(), number] } }, text: string() }, ['tag', 'attrs']), 1, 150), label: string() }, ['viewBox', 'shapes']);
node('native', { name: choice('box', 'row', 'col', 'grid', 'grid-item', 'card', 'text', 'title', 'caption', 'badge', 'divider', 'code', 'blockquote', 'bold', 'italic', 'underline', 'strikethrough', 'spacer', 'list', 'list-item', 'table', 'table-row', 'table-cell', 'flow', 'flow-item'), props: { ...object({ gap: integer(0, 16), padding: integer(0, 16), columns: integer(1, 6), radius: choice('none', 'sm', 'md', 'lg', 'xl', '2xl', '3xl', 'full'), border: bool, color, size: choice('xs', 'sm', 'md', 'lg', 'xl', '2xl', '3xl'), weight, align: choice('start', 'center', 'end', 'stretch'), justify: choice('start', 'center', 'end', 'between', 'around'), width: { anyOf: [integer(20, 1400), choice('100%', 'auto')] }, height: integer(0, 1400), maxWidth: integer(20, 1400), minWidth: integer(0, 1400), background: choice('surface', 'surface-secondary', 'surface-tertiary', 'none'), marker: choice('bullet', 'number', 'none'), variant: choice('soft', 'solid', 'outline', 'ghost'), pill: bool, textAlign: align }), maxProperties: 18 }, children }, ['name', 'children']);
defs.Node = { oneOf: nodes };
const schema = { $schema: 'https://json-schema.org/draft/2020-12/schema', $id: 'urn:micraow:intelligent-ui:schema:iui:1', title: 'IUIDocument', description: 'The project-defined iui/1 wire contract. Semantic validation additionally enforces safe expressions, data and URLs. Native nodes are recognized but unsupported by the portable renderer.', ...object({ version: { const: 'iui/1' }, title: string(), description: string(), theme: choice('auto', 'light', 'dark'), state: { type: 'object', propertyNames: key, maxProperties: 80, additionalProperties: scalar }, computed: { type: 'object', propertyNames: key, maxProperties: 80, additionalProperties: ref('Value') }, body: array(ref('Node'), 1, 150) }, ['version', 'body']), $defs: defs };
const dir = fileURLToPath(new URL('../src/schema/', import.meta.url));
await mkdir(dir, { recursive: true });
await writeFile(`${dir}/iui.schema.json`, JSON.stringify(schema, null, 2) + '\n');
const types = await compile(schema, 'IUIDocument', { bannerComment: '/** Generated by scripts/generate-schema.mjs. Edit the generator, not this file. */', additionalProperties: false, strictIndexSignatures: false, maxItems: -1 });
await writeFile(`${dir}/document.d.ts`, types);
console.log(`Generated iui/1 schema and TypeScript declarations (${nodes.length} node types).`);
// Generate the validation function ahead of time: CSP-safe browsers never compile schemas.
const { default: Ajv2020 } = await import('ajv/dist/2020.js');
const { default: standaloneCode } = await import('ajv/dist/standalone/index.js');
const ajv = new Ajv2020({ allErrors: true, strict: true, code: { source: true, optimize: true }, ownProperties: true, discriminator: true });
const validationSchema = structuredClone(schema);
validationSchema.$defs.Node.type = "object";
validationSchema.$defs.Node.discriminator = { propertyName: 'type' };
const validate = ajv.compile(validationSchema);
await writeFile(`${dir}/validator.cjs`, '/* Generated by scripts/generate-schema.mjs. Do not edit. */\n' + standaloneCode(ajv, validate));
await writeFile(`${dir}/validator.d.cts`, "import type { ValidateFunction } from 'ajv';\ndeclare const validate: ValidateFunction;\nexport = validate;\n");
