/** Original later-batch compiled consumer. Prepared, not yet browser-accepted. */
import assert from 'node:assert/strict';import{readFile,writeFile,mkdir,mkdtemp,rm}from'node:fs/promises';import path from'node:path';import{tmpdir}from'node:os';import{fileURLToPath,pathToFileURL}from'node:url';import{createRequire}from'node:module';import{spawnSync}from'node:child_process';
const root=path.dirname(fileURLToPath(import.meta.url));function arg(flag){const i=process.argv.indexOf(flag);if(i<0)return;const v=process.argv[i+1];assert.ok(v&&!v.startsWith('--'));return v;}
assert.ok(arg('--library'));const library=path.resolve(arg('--library')),revision=arg('--revision');assert.match(revision??'',/^[a-f0-9]{40}$/);const git=spawnSync('git',['-C',library,'rev-parse','HEAD'],{encoding:'utf8'});assert.equal(git.status,0,git.stderr);assert.equal(git.stdout.trim(),revision);
const pkg=JSON.parse(await readFile(path.join(library,'package.json'),'utf8'));const{validateDocument,compileHtml}=await import(pathToFileURL(path.resolve(library,pkg.exports['.'].import)).href);const require=createRequire(path.join(library,'package.json')),{chromium,expect}=require('@playwright/test');
const shots=path.resolve(arg('--screenshots')??path.join(root,'artifacts/browser'));await mkdir(shots,{recursive:true});const temporary=await mkdtemp(path.join(tmpdir(),'inform-checkbox-consumer-'));const name='local-checkbox-review',input=JSON.parse(await readFile(path.join(root,'examples',name+'.json'),'utf8'));const checked=validateDocument(input);assert.equal(checked.ok,true,JSON.stringify(checked.issues));let browser,count=0;
try{browser=await chromium.launch({headless:true,...(process.env.IUI_BROWSER_EXECUTABLE?{executablePath:process.env.IUI_BROWSER_EXECUTABLE}:{})});
for(const theme of ['light','dark'])for(const width of [390,768,1100]){
 const label=`${name}-${theme}-${width}`,file=path.join(temporary,label+'.html');await writeFile(file,await compileHtml({...input,theme},{assets:'inline',backend:'portable',lang:'zh-CN'}));
 const page=await browser.newPage({viewport:{width,height:1050},colorScheme:theme,reducedMotion:'reduce'}),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});
 await page.goto(pathToFileURL(file).href);await page.waitForSelector('.iui-root');await page.evaluate(()=>document.fonts.ready);
 const form=page.locator('form'),box=page.getByRole('checkbox',{name:/本地练习开关/}),extras=page.getByRole('checkbox',{name:'包含演示附注',exact:true}),number=page.getByLabel('合成偶数样本数',{exact:false}),booleanMetric=page.locator('.iui-metric-value > span:first-child').nth(0),numericMetric=page.locator('.iui-metric-value > span:first-child').nth(1);
 await expect(box).not.toBeChecked();await expect(extras).toBeChecked();await page.getByRole('button',{name:'仅检查本页',exact:true}).click();await expect(form).toHaveAttribute('data-status','invalid');await expect(box).toBeFocused();await expect(box).toHaveAttribute('aria-invalid','true');
 await page.keyboard.press('Space');await expect(box).toBeChecked();await expect(booleanMetric).toHaveText('true（已勾选）');await expect(box).toBeFocused();
 await number.fill('3');await expect(number).toHaveValue('3');await expect(numericMetric).toHaveText('2');await page.getByRole('button',{name:'宿主明确写回false',exact:true}).click();await expect(box).not.toBeChecked();await expect(booleanMetric).toHaveText('false（未勾选）');await expect(number).toHaveValue('3');await expect(numericMetric).toHaveText('2');
 await page.getByRole('button',{name:'恢复表单初值',exact:true}).click();await expect(box).not.toBeChecked();await expect(extras).toBeChecked();await expect(number).toHaveValue('2');await expect(form.locator('.iui-field-error')).toHaveText(['','','']);
 // Click the actual visible associated label, with browser-generated events.
 const id=await box.getAttribute('id'),labelNode=form.locator(`label[for="${id}"]`);await labelNode.click();await expect(box).toBeChecked();await expect(box).toBeFocused();await expect(booleanMetric).toHaveText('true（已勾选）');
 await page.getByRole('button',{name:'仅检查本页',exact:true}).click();await expect(form).toHaveAttribute('data-status','success');await box.focus();await page.keyboard.press('Space');await expect(box).not.toBeChecked();await expect(form).toHaveAttribute('data-status','idle');await expect(booleanMetric).toHaveText('false（未勾选）');await expect(box).toBeFocused();
 await page.keyboard.press('Space');await expect(box).toBeChecked();await page.getByRole('button',{name:'仅检查本页',exact:true}).click();await expect(form).toHaveAttribute('data-status','success');
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),label+': whole-page overflow');assert.deepEqual(errors,[]);assert.deepEqual(external,[]);await page.screenshot({path:path.join(shots,label+'.png'),fullPage:true});await page.close();count++;console.log(`PASS ${label}`);
}
await writeFile(path.join(shots,'RESULTS.json'),JSON.stringify({revision,localCompiledViews:count,widths:[390,768,1100],themes:['light','dark'],browser:'chromium',publicCdn:'not-run',screenReader:'not-run',screenshotReview:'pending-human-review'},null,2)+'\n');
}finally{await browser?.close();await rm(temporary,{recursive:true,force:true});}
