import type {EmailPreviewNode} from '../schema/document.js';import type {RendererContext} from './context.js';import type {MailFilesLabels} from './mail-files-labels.js';import {readerBlocked,readerNativeReset} from './reader-controls.js';import {readerLink,readerSource,readerTime,readerMetadata} from './mail-files-shared.js';
let serial=0;
export function renderEmailPreview(c:RendererContext,n:EmailPreviewNode,t:MailFilesLabels):HTMLElement{
 const e=c.element,root=e('article','iui-email-preview iui-supplied-reader'),base=`iui-mail-internal-${c.prefix}${++serial}`;root.dir='auto';const title=e('h2','iui-email-subject',n.subject);title.id=base+'-title';root.setAttribute('aria-labelledby',title.id);root.append(title);const note=e('p','iui-reader-note',t.emailNote);note.id=base+'-note';root.setAttribute('aria-describedby',note.id);root.append(note);
 const person=(value:{name?:string;address:string})=>{const span=e('span','iui-email-person');if(value.name!==undefined)span.append(e('span','iui-email-person-name',value.name),c.doc.createTextNode(' · '));const address=e('bdi','iui-email-address',value.address);address.dir='ltr';span.append(address);return span;};const from=e('p','iui-email-from');from.append(c.doc.createTextNode(t.from+': '),person(n.from));root.append(from);const sent=e('p','iui-email-sent');sent.append(c.doc.createTextNode(t.sent+': '),n.sentAt===undefined?e('span','',t.notSupplied):readerTime(c,n.sentAt));root.append(sent);
 const recipients=e('details','iui-email-recipients');recipients.append(e('summary','',`${t.recipients} (${n.to.length+(n.cc?.length??0)})`));for(const [label,people] of [[t.to,n.to],[t.cc,n.cc??[]]] as const){if(!people.length)continue;const heading=e('h3','',label),list=e('ul');for(const value of people){const item=e('li');item.append(person(value));list.append(item);}recipients.append(heading,list);}if(!n.to.length&&!n.cc?.length)recipients.append(e('p','',t.noRecipients));root.append(recipients);
 const heading=e('h3','iui-email-body-title',t.body);root.append(heading);const full=e('div','iui-email-body',n.body);full.id=base+'-body';const codepoints=[...n.body],long=codepoints.length>600,short=long?e('div','iui-email-body iui-email-excerpt',codepoints.slice(0,600).join('')+'…'):undefined,toggle=long?e('button','iui-email-expand',t.showFull):undefined;let alive=true,expanded=!long;
 if(short)root.append(short);full.hidden=!expanded;root.append(full);if(toggle){toggle.type='button';toggle.setAttribute('aria-controls',full.id);toggle.setAttribute('aria-expanded','false');root.append(toggle);c.on(toggle,'click',()=>{if(readerBlocked(root,toggle,alive))return;expanded=!expanded;full.hidden=!expanded;short!.hidden=expanded;toggle.textContent=expanded?t.showLess:t.showFull;toggle.setAttribute('aria-expanded',String(expanded));});}
 if(n.quotedText!==undefined){const quoted=e('details','iui-email-quoted');quoted.append(e('summary','',t.quoted),e('div','iui-email-body',n.quotedText));root.append(quoted);}
 const files=n.attachments??[];root.append(e('h3','iui-email-attachments-title',t.attachments));const label=e('label','',t.searchAttachments),search=e('input','iui-reader-search');search.type='search';search.id=base+'-search';search.maxLength=200;label.htmlFor=search.id;const toolbar=e('div','iui-reader-toolbar');toolbar.append(label,search);root.append(toolbar);
 const count=e('p','iui-reader-count');count.setAttribute('role','status');count.setAttribute('aria-live','polite');const empty=e('p','iui-reader-empty'),list=e('ul','iui-reader-files');root.append(count,empty,list);const rows=files.map(file=>{const row=e('li','iui-reader-file');row.dataset.fileId=file.id;row.append(e('h4','iui-reader-name',file.name),readerMetadata(c,file,t));if(file.url!==undefined)row.append(readerLink(c,file.url,t.open,t));list.append(row);return{row,name:file.name.toLowerCase()};});let query='',revision=0;
 const restore=()=>{if(alive&&root.contains(search))search.value=query;};
 const paint=()=>{if(!alive)return;restore();let shown=0;for(const item of rows){item.row.hidden=!item.name.includes(query.toLowerCase());if(!item.row.hidden)shown++;}count.textContent=t.count(shown,rows.length);empty.hidden=shown>0;empty.textContent=rows.length?t.noMatch:t.emptyAttachments;};
 c.on(search,'input',()=>{if(!alive)return;if(readerBlocked(root,search,alive)||search.value.length>200){restore();return;}query=search.value;revision++;paint();});readerNativeReset(c,root,[search],()=>revision,restore,()=>{query='';revision++;paint();});if(n.source)root.append(readerSource(c,n.source,t));c.cleanup(()=>{alive=false;});paint();return root;
}
