import type {FileNavListNode} from '../schema/document.js';import type {RendererContext} from './context.js';import type {MailFilesLabels} from './mail-files-labels.js';import {readerBlocked,readerNativeReset} from './reader-controls.js';import {readerLink,readerSource,readerMetadata} from './mail-files-shared.js';
let serial=0;
export function renderFileNav(c:RendererContext,n:FileNavListNode,t:MailFilesLabels):HTMLElement{
 const e=c.element,root=e('section','iui-file-nav iui-supplied-reader'),base=`iui-files-internal-${c.prefix}${++serial}`;root.dir='auto';const title=e('h2','iui-file-nav-title',n.label);title.id=base+'-title';root.setAttribute('aria-labelledby',title.id);root.append(title);if(n.description!==undefined)root.append(e('p','iui-reader-description',n.description));const note=e('p','iui-reader-note',t.filesNote);note.id=base+'-note';root.setAttribute('aria-describedby',note.id);root.append(note);
 const entries=new Map(n.entries.map(item=>[item.id,item]));let folder=n.initialFolderId??'',query='',category='',revision=0,alive=true;const nav=e('nav','iui-file-breadcrumbs');nav.setAttribute('aria-label',t.breadcrumb);const crumbs=new Map<string,HTMLButtonElement>();
 const folderTitle=e('h3','iui-file-folder-title');folderTitle.tabIndex=-1;folderTitle.id=base+'-folder';
 const navigate=(control:HTMLElement,id:string)=>{if(readerBlocked(root,control,alive)||folder===id)return;folder=id;query='';category='';revision++;paint();if(alive&&folderTitle.isConnected)folderTitle.focus();};
 for(const [id,text] of [['',t.root],...n.entries.filter(x=>x.kind==='folder').map(x=>[x.id,x.name])] as [string,string][]){const button=e('button','iui-file-crumb',text);button.type='button';crumbs.set(id,button);nav.append(button);c.on(button,'click',()=>navigate(button,id));}root.append(nav,folderTitle);
 const back=e('button','iui-file-back',t.back);back.type='button';root.append(back);c.on(back,'click',()=>{if(folder==='')return;navigate(back,entries.get(folder)?.parentId??'');});
 const toolbar=e('div','iui-reader-toolbar'),searchLabel=e('label','',t.searchFiles),search=e('input','iui-reader-search'),categoryLabel=e('label','',t.category),filter=e('select','iui-file-category'),reset=e('button','iui-file-reset',t.reset);search.type='search';search.maxLength=200;search.id=base+'-search';searchLabel.htmlFor=search.id;filter.id=base+'-category';categoryLabel.htmlFor=filter.id;reset.type='button';
 for(const [value,text] of [['',t.allCategories],...Object.entries(t.categories)]){const option=e('option','',text);option.value=value;option.defaultSelected=value==='';filter.append(option);}toolbar.append(searchLabel,search,categoryLabel,filter,reset);root.append(toolbar);
 const count=e('p','iui-reader-count');count.setAttribute('role','status');count.setAttribute('aria-live','polite');const empty=e('p','iui-reader-empty'),list=e('ul','iui-reader-files');list.setAttribute('aria-labelledby',folderTitle.id);root.append(count,empty,list);
 const rows=n.entries.map(entry=>{const row=e('li','iui-reader-file');row.dataset.entryId=entry.id;row.dataset.kind=entry.kind;const icon=e('span','iui-file-icon');icon.setAttribute('aria-hidden','true');const content=e('div','iui-file-content');
  if(entry.kind==='folder'){const button=e('button','iui-file-open-folder',entry.name);button.type='button';button.setAttribute('aria-label',`${t.folder}: ${entry.name}`);content.append(button,e('span','iui-file-kind',t.folder));c.on(button,'click',()=>navigate(button,entry.id));if(entry.description!==undefined){const details=e('details','iui-reader-details');details.append(e('summary','',t.details),e('p','',entry.description));content.append(details);}}
  else{content.append(e('h4','iui-reader-name',entry.name),e('span','iui-file-kind',t.categories[entry.category??'unknown']),readerMetadata(c,entry,t));if(entry.url!==undefined)content.append(readerLink(c,entry.url,t.open,t));}row.append(icon,content);list.append(row);return{row,entry,name:entry.name.toLowerCase()};});
 const restore=()=>{if(!alive)return;if(root.contains(search))search.value=query;if(root.contains(filter))filter.value=category;};
 function paint(){if(!alive)return;restore();folderTitle.textContent=folder===''?t.root:entries.get(folder)!.name;back.setAttribute('aria-disabled',String(folder===''));reset.setAttribute('aria-disabled',String(query===''&&category===''));
  const path:string[]=[''];let id=folder;const ancestors:string[]=[];while(id!==''){ancestors.unshift(id);id=entries.get(id)?.parentId??'';}path.push(...ancestors);for(const [id,button] of crumbs){button.hidden=!path.includes(id);if(id===folder)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');}for(const id of path)nav.append(crumbs.get(id)!);
  let total=0,shown=0;for(const item of rows){const inFolder=(item.entry.parentId??'')===folder;if(inFolder)total++;item.row.hidden=!inFolder||!item.name.includes(query.toLowerCase())||(item.entry.kind==='file'&&category!==''&&(item.entry.category??'unknown')!==category);if(!item.row.hidden)shown++;}count.textContent=t.count(shown,total);empty.hidden=shown>0;empty.textContent=total?t.noMatch:n.entries.length?t.emptyFolder:t.noFiles;
 }
 c.on(search,'input',()=>{if(!alive)return;if(readerBlocked(root,search,alive)||search.value.length>200){restore();return;}query=search.value;revision++;paint();});
 c.on(filter,'change',()=>{if(!alive)return;if(readerBlocked(root,filter,alive)||filter.selectedIndex<0||(filter.value!==''&&!Object.hasOwn(t.categories,filter.value))){restore();return;}category=filter.value;revision++;paint();});
 const resetFilters=()=>{query='';category='';revision++;paint();};c.on(reset,'click',()=>{if(readerBlocked(root,reset,alive)||(query===''&&category===''))return;resetFilters();});readerNativeReset(c,root,[search,filter],()=>revision,restore,resetFilters);if(n.source)root.append(readerSource(c,n.source,t));c.cleanup(()=>{alive=false;});paint();return root;
}
