import type{FinanceHeatmapNode}from'../schema/document.js';import type{RendererContext}from'./context.js';
interface Weighted{index:number;weight:number}interface Tile{index:number;x:number;y:number;width:number;height:number}
/** Original squarified area layout. Scale weights before summation to keep finite extremes usable. */
export function heatmapTiles(items:Weighted[],width:number,height:number):Tile[]{
 const max=Math.max(0,...items.map(i=>i.weight));if(!max||width<=0||height<=0)return[];const sum=items.reduce((s,i)=>s+i.weight/max,0),queue=items.map(i=>({index:i.index,area:i.weight/max/sum*width*height})).filter(i=>i.area>0).sort((a,b)=>b.area-a.area||a.index-b.index),out:Tile[]=[];let x=0,y=0,w=width,h=height;
 const worst=(row:typeof queue,side:number)=>{const total=row.reduce((s,i)=>s+i.area,0),lo=Math.min(...row.map(i=>i.area)),hi=Math.max(...row.map(i=>i.area));return Math.max(side*side*hi/(total*total),total*total/(side*side*lo));};
 const place=(row:typeof queue)=>{const total=row.reduce((s,i)=>s+i.area,0);if(w>=h){const strip=Math.min(w,total/h);let at=y;for(const item of row){const size=item.area/strip;out.push({index:item.index,x,y:at,width:strip,height:size});at+=size;}x+=strip;w=Math.max(0,w-strip);}else{const strip=Math.min(h,total/w);let at=x;for(const item of row){const size=item.area/strip;out.push({index:item.index,x:at,y,width:size,height:strip});at+=size;}y+=strip;h=Math.max(0,h-strip);}};
 let row:typeof queue=[];while(queue.length){const candidate=queue[0],next=[...row,candidate];if(!row.length||worst(next,Math.min(w,h))<=worst(row,Math.min(w,h))){row=next;queue.shift();}else{place(row);row=[];}}if(row.length)place(row);return out.filter(r=>[r.x,r.y,r.width,r.height].every(Number.isFinite)&&r.width>0&&r.height>0);
}
let serial=0;
export function renderHeatmap(c:RendererContext,n:FinanceHeatmapNode):HTMLElement{
 const e=c.element,svg=c.svg,l=c.labels(),zh=l.missing==='缺测',locale=zh?'zh-CN':'en-US',t=zh?{title:'行情热图',symbol:'代码',currency:'币种',sector:'行业',all:'全部行业',area:'面积',change:'变动基准',legend:'色阶：−10% 或更低 / 0 / +10% 或更高；原始幅度保留在详情与表格。',omitted:'零、缺测或精度不足的权重不分配面积，全部记录仍在数据表中。',empty:'没有可绘制的正权重记录',none:'没有符合筛选条件的记录',selected:'选中项',table:'完整热图数据',weight:'权重',price:'价格',percent:'变动',delay:'声明延迟',minutes:'分钟',instruction:'左右方向键选择记录，Home/End跳至首尾；Enter展开数据表。',open:'开市',closed:'休市',pre:'盘前',post:'盘后',halted:'暂停交易',unknown:'状态未知'}:{title:'Market heatmap',symbol:'Symbol',currency:'Currency',sector:'Sector',all:'All sectors',area:'Area',change:'Change basis',legend:'Color scale: −10% or lower / 0 / +10% or higher; exact changes remain in details and the table.',omitted:'Zero, missing or unrepresentable weights receive no area. Every record remains in the table.',empty:'No positive weights to draw',none:'No records match the filter',selected:'Selected',table:'Full heatmap data',weight:'Weight',price:'Price',percent:'Change',delay:'Reported delay',minutes:'min',instruction:'Use Left/Right to select records and Home/End for endpoints. Enter opens the data table.',open:'Market open',closed:'Market closed',pre:'Pre-market',post:'After-hours',halted:'Trading halted',unknown:'Unknown status'};
 const root=e('section','iui-heatmap'),id=`${c.prefix}heatmap-${++serial}`,title=e('h2','iui-heatmap-title',n.title??t.title);title.id=id+'-title';root.setAttribute('aria-labelledby',title.id);const status=e('p','iui-heatmap-status'),body=e('div','iui-heatmap-body'),toolbar=e('label','iui-heatmap-filter'),select=e('select');select.setAttribute('aria-label',t.sector);const sectors=[...new Set(n.cells.map(v=>v.sector))];[t.all,...sectors].forEach((s,i)=>{const option=e('option','',s);option.value=String(i);select.append(option);});let sector=n.initialSector??'',activeId:string|undefined;select.value=String(sector?sectors.indexOf(sector)+1:0);toolbar.append(e('span','',t.sector),select);
 const graphic=svg('svg',{class:'iui-heatmap-graphic',tabindex:0,role:'img','aria-label':n.title??t.title,'aria-describedby':id+'-instruction'}),instruction=e('p','iui-caption',t.instruction);instruction.id=id+'-instruction';const legend=e('p','iui-caption',t.legend),empty=e('p','iui-heatmap-empty'),omitted=e('p','iui-caption',t.omitted),readout=e('output','iui-heatmap-readout');readout.setAttribute('aria-live','polite');readout.setAttribute('aria-atomic','true');const details=e('details'),summary=e('summary','',t.table),tableHost=e('div','iui-heatmap-table');tableHost.tabIndex=0;tableHost.setAttribute('role','region');tableHost.setAttribute('aria-label',t.table);details.append(summary,tableHost);
 body.append(e('p','iui-caption',`${t.area}: ${n.weightLabel} · ${t.change}: ${n.changeBasis}`),toolbar,legend,graphic,instruction,empty,omitted,readout,details);const footer=e('footer','iui-heatmap-source'),time=new Intl.DateTimeFormat(locale,{timeZone:n.timezone,year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23',timeZoneName:'shortOffset'});footer.append(e('time','',`${l.updated}: ${time.format(new Date(n.asOf))} · ${n.timezone}`));footer.querySelector('time')!.dateTime=n.asOf;const source=e('span','',`${l.source}: `);if(n.source.url){const a=e('a','',n.source.label);a.href=n.source.url;a.target='_blank';a.rel='noopener noreferrer';a.referrerPolicy='no-referrer';source.append(a);}else source.append(c.doc.createTextNode(n.source.label));footer.append(source);if(n.source.synthetic)footer.append(e('strong','',l.synthetic));root.append(title,status,body,footer);
 let filtered:FinanceHeatmapNode['cells']=[],currentTiles:Tile[]=[],chartWidth=640;
 const selection=svg('rect',{class:'iui-heatmap-selection',fill:'none','pointer-events':'none','aria-hidden':'true'});
 const drawSelection=()=>{
  const tile=currentTiles.find(tile=>filtered[tile.index]?.id===activeId),bounds=graphic.getBoundingClientRect(),fallbackScale=bounds.width>0?bounds.width/chartWidth:1,matrix=(graphic as SVGSVGElement).getScreenCTM?.(),scaleX=matrix?.a??fallbackScale,scaleY=matrix?.d??fallbackScale,originX=matrix?.e??bounds.left,originY=matrix?.f??bounds.top,dpr=c.doc.defaultView?.devicePixelRatio||1,keyboard=graphic.dataset.inputMode==='keyboard'&&c.doc.activeElement===graphic,thickness=keyboard?3:2;
  graphic.dataset.activeTile='false';selection.style.display='none';if(!tile)return;
  // Snap the independent final overlay to device pixels inside the tile. Data rectangles remain unchanged.
  const left=Math.ceil((originX+tile.x*scaleX+2)*dpr)/dpr,right=Math.floor((originX+(tile.x+tile.width)*scaleX-2)*dpr)/dpr,top=Math.ceil((originY+tile.y*scaleY+2)*dpr)/dpr,bottom=Math.floor((originY+(tile.y+tile.height)*scaleY-2)*dpr)/dpr;
  if(right-left<=thickness||bottom-top<=thickness)return;
  for(const[key,value]of Object.entries({x:(left+thickness/2-originX)/scaleX,y:(top+thickness/2-originY)/scaleY,width:(right-left-thickness)/scaleX,height:(bottom-top-thickness)/scaleY,'stroke-width':thickness}))selection.setAttribute(key,String(value));
  selection.style.display='block';selection.setAttribute('data-selected-cell',activeId!);graphic.dataset.activeTile='true';
 };
 const fmt=(v:number|null)=>v===null?l.missing:c.display(v),percent=(v:number|null)=>v===null?l.missing:`${v>0?'+':''}${c.display(v)}%`,describe=(cell:FinanceHeatmapNode['cells'][number])=>`${cell.symbol} · ${cell.name} · ${cell.sector} · ${n.weightLabel}: ${fmt(cell.weight)} · ${t.price}: ${fmt(cell.price)} ${cell.currency} · ${percent(cell.changePercent)} (${n.changeBasis}) · ${t[cell.marketStatus]} · ${t.delay} ${cell.delayMinutes} ${t.minutes} · ${time.format(new Date(cell.asOf))}`;
 const focus=(index:number)=>{if(!filtered.length){activeId=undefined;readout.value='';return;}const cell=filtered[Math.max(0,Math.min(filtered.length-1,index))];activeId=cell.id;readout.value=describe(cell);graphic.querySelectorAll('[data-heatmap-cell]').forEach(g=>g.classList.toggle('iui-heatmap-active',g.getAttribute('data-heatmap-cell')===activeId));drawSelection();};
 const paint=()=>{const state=n.status??'ready';root.dataset.status=state;root.setAttribute('aria-busy',String(state==='loading'));status.textContent=state==='loading'?n.message??l.loading:state==='error'?n.message??l.loadError:'';status.hidden=!status.textContent;status.setAttribute('role',state==='error'?'alert':'status');body.hidden=state!=='ready';if(state!=='ready')return;filtered=n.cells.filter(v=>!sector||v.sector===sector);const width=Math.max(260,root.clientWidth||640),height=width<500?320:360,weights=filtered.flatMap((cell,index)=>cell.weight!==null&&cell.weight>0?[{index,weight:cell.weight}]:[]),tiles=heatmapTiles(weights,width,height);currentTiles=tiles;chartWidth=width;graphic.setAttribute('viewBox',`0 0 ${width} ${height}`);graphic.replaceChildren();graphic.style.display=tiles.length?'block':'none';empty.textContent=filtered.length?n.message??t.empty:n.message??t.none;empty.hidden=tiles.length>0;omitted.hidden=tiles.length===filtered.length;instruction.hidden=!tiles.length;legend.hidden=!tiles.length;
  for(const tile of tiles){const cell=filtered[tile.index],group=svg('g',{'data-heatmap-cell':cell.id}),color=cell.changePercent===null||cell.changePercent===0?'var(--iui-surface-tertiary)':`color-mix(in srgb,var(--iui-series-${cell.changePercent>0?'green':'red'}) ${Math.min(50,12+Math.abs(cell.changePercent)/10*38)}%,var(--iui-bg))`;group.append(svg('rect',{x:tile.x,y:tile.y,width:tile.width,height:tile.height,fill:color,class:'iui-heatmap-tile','data-weight':cell.weight}));const tip=svg('title');tip.textContent=describe(cell);group.append(tip);if(tile.width>=70&&tile.height>=46){const clip=svg('clipPath',{id:id+'-clip-'+tile.index});clip.append(svg('rect',{x:tile.x+8,y:tile.y+4,width:Math.max(0,tile.width-16),height:Math.max(0,tile.height-12)}));graphic.append(clip);const labels=svg('g',{'clip-path':`url(#${id}-clip-${tile.index})`});group.append(labels);const label=svg('text',{x:tile.x+8,y:tile.y+20,class:'iui-heatmap-label'});label.textContent=Array.from(cell.symbol).slice(0,Math.max(2,Math.floor((tile.width-16)/9))).join('');labels.append(label);const value=svg('text',{x:tile.x+8,y:tile.y+39,class:'iui-heatmap-change'});value.textContent=percent(cell.changePercent);if(tile.height>=50&&value.textContent.length*8<tile.width-16)labels.append(value);}graphic.append(group);}
  graphic.append(selection);
  const table=e('table'),caption=e('caption','',`${t.table} · ${n.weightLabel} · ${n.changeBasis}`),head=e('thead'),row=e('tr');for(const label of [t.symbol,t.sector,n.weightLabel,`${t.price} / ${t.currency}`,t.percent,l.updated]){const th=e('th','',label);th.scope='col';row.append(th);}head.append(row);const tbody=e('tbody');filtered.forEach(cell=>{const tr=e('tr');tr.dataset.heatmapRow=cell.id;const label=e('th','',`${cell.symbol} · ${cell.name}`);label.scope='row';tr.append(label);for(const value of [cell.sector,fmt(cell.weight),`${fmt(cell.price)} ${cell.currency}`,percent(cell.changePercent),`${time.format(new Date(cell.asOf))} · ${t[cell.marketStatus]} · ${t.delay} ${cell.delayMinutes} ${t.minutes}`])tr.append(e('td','',value));tbody.append(tr);});table.append(caption,head,tbody);const left=tableHost.scrollLeft;tableHost.replaceChildren(table);tableHost.scrollLeft=left;details.hidden=!filtered.length;focus(Math.max(0,filtered.findIndex(v=>v.id===activeId)));};
 c.on(graphic,'focus',()=>{graphic.dataset.inputMode=graphic.matches(':focus-visible')?'keyboard':'pointer';drawSelection();});c.on(graphic,'blur',()=>{graphic.dataset.inputMode='pointer';drawSelection();});c.on(graphic,'pointerdown',()=>{graphic.dataset.inputMode='pointer';drawSelection();});
 c.on(select,'change',()=>{sector=Number(select.value)===0?'':sectors[Number(select.value)-1];activeId=undefined;paint();});c.on(graphic,'keydown',event=>{const key=(event as KeyboardEvent).key;if(['ArrowLeft','ArrowRight','Home','End'].includes(key)){graphic.dataset.inputMode='keyboard';event.preventDefault();const i=filtered.findIndex(v=>v.id===activeId);focus(key==='Home'?0:key==='End'?filtered.length-1:i+(key==='ArrowRight'?1:-1));}else if(key==='Enter'){event.preventDefault();details.open=true;summary.focus();}});c.on(graphic,'click',event=>{graphic.dataset.inputMode='pointer';const target=(event.target as Element|null)?.closest('[data-heatmap-cell]');if(target)focus(filtered.findIndex(v=>v.id===target.getAttribute('data-heatmap-cell')));else drawSelection();});c.bind(paint);return root;
}
