import type {JobsNode} from '../schema/document.js';import type {RendererContext} from './context.js';import type {DecisionLabels} from './decision-labels.js';import {readerBlocked,readerNativeReset} from './reader-controls.js';
export interface JobShortlistDetail{readonly componentId:string|null;readonly jobId:string;readonly shortlisted:boolean;}
let serial=0;
export function renderJobs(c:RendererContext,n:JobsNode,t:DecisionLabels):HTMLElement{
 const e=c.element,root=e('section','iui-jobs iui-decision-card'),base=`iui-jobs-internal-${c.prefix}${++serial}`;root.dir='auto';const title=e('h2','',n.label);title.id=base+'-title';root.setAttribute('aria-labelledby',title.id);root.append(title);if(n.description!==undefined)root.append(e('p','iui-decision-description',n.description));const note=e('p','iui-decision-note',t.jobsNote);note.id=base+'-note';root.setAttribute('aria-describedby',note.id);root.append(note);
 const toolbar=e('div','iui-jobs-toolbar'),search=e('input','iui-jobs-search');search.type='search';search.maxLength=200;search.id=base+'-search';const searchLabel=e('label','',t.search);searchLabel.htmlFor=search.id;toolbar.append(searchLabel,search);
 const select=(key:string,label:string,values:Record<string,string>)=>{const field=e('select','iui-jobs-'+key),caption=e('label','',label);field.id=base+'-'+key;caption.htmlFor=field.id;for(const [value,text] of [['',t.all],...Object.entries(values)]){const option=e('option','',text);option.value=value;option.defaultSelected=value==='';field.append(option);}toolbar.append(caption,field);return field;};const workplace=select('workplace',t.workplace,t.workplaces),employment=select('employment',t.employment,t.employments),only=e('input');only.type='checkbox';only.id=base+'-only';const onlyLabel=e('label','iui-jobs-only');onlyLabel.htmlFor=only.id;onlyLabel.append(only,e('span','',t.shortlistedOnly));const reset=e('button','iui-jobs-reset',t.reset);reset.type='button';toolbar.append(onlyLabel,reset);root.append(toolbar);
 const count=e('p','iui-jobs-count');count.setAttribute('role','status');count.setAttribute('aria-live','polite');const empty=e('p','iui-jobs-empty'),status=e('p','iui-jobs-status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');const list=e('ul','iui-jobs-list');root.append(count,empty,list,status);
 let alive=true,dispatching=false,query='',work='',employmentType='',onlySaved=false,revision=0;const saved=new Set<string>();
 const link=(url:string,text:string)=>{const a=e('a','',`${text} (${t.newTab})`);a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.referrerPolicy='no-referrer';return a;};
 const rows=n.jobs.map(job=>{const row=e('li','iui-job');row.dataset.jobId=job.id;row.append(e('h3','iui-job-title',job.title),e('p','iui-job-organization',job.organization),e('p','iui-job-location',job.location));const badges=e('p','iui-job-badges');badges.append(e('span','',t.workplaces[job.workplace]),e('span','',t.employments[job.employment]));row.append(badges);
  const pay=job.salary?`${t.pay}: ${job.salary.minimum}–${job.salary.maximum} ${job.salary.currency} / ${t.periods[job.salary.period]}`:t.payUnknown;row.append(e('p','iui-job-pay',pay));for(const [key,label] of [['postedDate',t.posted],['deadlineDate',t.deadline]] as const)if(job[key]!==undefined){const p=e('p','iui-job-date'),time=e('time','',job[key]);time.dateTime=job[key]!;time.dir='ltr';p.append(c.doc.createTextNode(label+': '),time);row.append(p);}if(job.description!==undefined){const details=e('details');details.append(e('summary','',t.description),e('p','iui-decision-description',job.description));row.append(details);}const button=e('button','iui-job-shortlist',t.shortlist);button.type='button';row.append(button);if(job.url!==undefined)row.append(link(job.url,t.openJob));list.append(row);c.on(button,'click',()=>choose(job.id,button,row));return{job,row,button,search:(job.title+' '+job.organization+' '+job.location).toLowerCase()};});
 const restore=()=>{if(!alive)return;if(root.contains(search))search.value=query;if(root.contains(workplace))workplace.value=work;if(root.contains(employment))employment.value=employmentType;if(root.contains(only))only.checked=onlySaved;};
 const put=(element:HTMLElement,text:string)=>{if(alive&&root.contains(element))element.textContent=text;};
 function paint(){if(!alive)return;restore();let shown=0;for(const item of rows){if(!root.contains(item.row))continue;item.row.hidden=!item.search.includes(query.toLowerCase())||(work!==''&&item.job.workplace!==work)||(employmentType!==''&&item.job.employment!==employmentType)||(onlySaved&&!saved.has(item.job.id));if(!item.row.hidden)shown++;if(root.contains(item.button)){item.button.textContent=saved.has(item.job.id)?t.removeShortlist:t.shortlist;item.button.setAttribute('aria-pressed',String(saved.has(item.job.id)));}}put(count,t.count(shown,rows.length,saved.size));if(root.contains(empty)){empty.hidden=shown>0;empty.textContent=rows.length?t.noMatch:t.emptyJobs;}if(root.contains(reset))reset.setAttribute('aria-disabled',String(!query&&!work&&!employmentType&&!onlySaved));}
 function choose(id:string,button:HTMLButtonElement,row:HTMLElement){if(dispatching||readerBlocked(root,button,alive))return;dispatching=true;try{const next=!saved.has(id),detail:JobShortlistDetail=Object.freeze({componentId:n.id??null,jobId:id,shortlisted:next}),Constructor=c.doc.defaultView?.CustomEvent;if(readerBlocked(root,button,alive))return;let event:CustomEvent<JobShortlistDetail>;if(typeof Constructor==='function')event=new Constructor('iui:job-shortlist',{detail,bubbles:true,cancelable:true,composed:false});else{event=c.doc.createEvent('CustomEvent');event.initCustomEvent('iui:job-shortlist',true,true,detail);}if(readerBlocked(root,button,alive))return;const accepted=root.dispatchEvent(event);if(readerBlocked(root,button,alive))return;const hadFocus=c.doc.activeElement===button;if(accepted){if(next)saved.add(id);else saved.delete(id);revision++;}put(status,accepted?(next?t.localSaved:t.localRemoved):t.rejected);paint();if(accepted&&row.hidden&&hadFocus&&!readerBlocked(root,only,alive))only.focus();}catch{if(!readerBlocked(root,button,alive))put(status,t.error);}finally{dispatching=false;}}
 c.on(search,'input',()=>{if(!alive)return;if(dispatching||readerBlocked(root,search,alive)||search.value.length>200){restore();return;}query=search.value;revision++;paint();});
 for(const [field,values,set] of [[workplace,t.workplaces,(value:string)=>{work=value;}],[employment,t.employments,(value:string)=>{employmentType=value;}]] as const)c.on(field,'change',()=>{if(!alive)return;if(dispatching||readerBlocked(root,field,alive)||field.selectedIndex<0||(field.value!==''&&!Object.hasOwn(values,field.value))){restore();return;}set(field.value);revision++;paint();});
 c.on(only,'change',()=>{if(!alive)return;if(dispatching||readerBlocked(root,only,alive)){restore();return;}onlySaved=only.checked;revision++;paint();});const resetFilters=()=>{query='';work='';employmentType='';onlySaved=false;revision++;paint();};c.on(reset,'click',()=>{if(dispatching||readerBlocked(root,reset,alive)||(!query&&!work&&!employmentType&&!onlySaved))return;resetFilters();});readerNativeReset(c,root,[search,workplace,employment,only],()=>revision,restore,resetFilters);if(n.source){const source=e('p','iui-decision-source');source.append(c.doc.createTextNode(t.source+': '),link(n.source.url,n.source.label));root.append(source);}c.cleanup(()=>{alive=false;});paint();return root;
}
