import type {LearningNode} from '../core/learning.js';
import type {RendererContext} from './context.js';
let serial=0;
/** Local, deterministic self-study. Answers are supplied teaching data, not protected exam secrets. */
export function renderLearning(c:RendererContext,n:LearningNode):HTMLElement{
 const e=c.element,zh=c.labels().missing==='缺测',id=`${c.prefix}learning-${++serial}`;
 const t=zh?{quiz:'自测',cards:'闪卡',single:'单选题',multiple:'多选题（全部选对得分）',check:'确认答案',next:'下一题',previous:'上一题',result:'查看结果',retry:'重新开始',review:'回看内容',correct:'回答正确',incorrect:'再想一想',answer:'参考答案',score:'得分',complete:'本轮完成',progress:'进度',reveal:'查看答案',front:'返回正面',prevCard:'上一张',nextCard:'下一张',mastered:'已掌握',again:'再练一次',unrated:'未评估',rated:'已评估',hint:'提示',privacy:'本地自测，答案包含在文档中；不保存成绩。',local:'掌握标记仅在本页本轮有效。',emptyQuiz:'暂无题目',emptyCards:'暂无闪卡',question:'题目',card:'卡片'}:{quiz:'Self-check',cards:'Flashcards',single:'Single choice',multiple:'Multiple choice (exact match)',check:'Check answer',next:'Next question',previous:'Previous question',result:'View results',retry:'Start again',review:'Review content',correct:'Correct',incorrect:'Try thinking it through',answer:'Reference answer',score:'Score',complete:'Round complete',progress:'Progress',reveal:'Reveal answer',front:'Show front',prevCard:'Previous card',nextCard:'Next card',mastered:'Mastered',again:'Practice again',unrated:'Not rated',rated:'Rated',hint:'Hint',privacy:'Local self-check: answers are in this document; scores are not saved.',local:'Ratings apply only to this page and round.',emptyQuiz:'No questions available',emptyCards:'No flashcards available',question:'Question',card:'Card'};
 const root=e('section',`iui-learning iui-${n.type}`);root.setAttribute('aria-label',n.title);const header=e('header','iui-learning-header');header.append(e('span','iui-caption',n.type==='quiz'?t.quiz:t.cards),e('h2','iui-learning-title',n.title));if(n.description)header.append(e('p','',n.description));const body=e('div','iui-learning-body'),live=e('p','iui-learning-live');live.setAttribute('role','status');live.setAttribute('aria-live','polite');live.setAttribute('aria-atomic','true');root.append(header,body,live,e('p','iui-caption',n.type==='quiz'?t.privacy:t.local));
 let index=0,summary=false,revealed=false;const selections=new Map<string,Set<string>>(),results=new Map<string,boolean>(),ratings=new Map<string,'mastered'|'again'>();
 const action=(name:string,label:string,disabled=false)=>{const b=e('button','',label);b.type='button';b.dataset.learningAction=name;b.disabled=disabled;return b;};
 const formula=(parent:HTMLElement,latex:string|undefined)=>{if(latex)parent.append(c.render({type:'math',latex,block:true}));};
 const progress=(value:number,max:number,label:string)=>{const wrap=e('div','iui-learning-progress'),p=e('progress');p.max=max;p.value=value;p.setAttribute('aria-label',label);wrap.append(e('span','',`${label}: ${value} / ${max}`),p);return wrap;};
 function heading(text:string){const h=e('h3','iui-learning-heading',text);h.tabIndex=-1;h.id=id+'-prompt';return h;}
 function quiz(){if(n.type!=='quiz')return;const total=n.questions.length;if(!total){body.append(e('p','iui-learning-empty',t.emptyQuiz));return;}const possible=n.questions.reduce((sum,q)=>sum+(q.points??1),0),earned=n.questions.reduce((sum,q)=>sum+(results.get(q.id)?q.points??1:0),0);body.append(progress(results.size,total,t.progress));
  if(summary){const result=e('div','iui-learning-result');result.append(heading(t.complete),e('p','iui-learning-score',`${t.score}: ${earned} / ${possible}`));const list=e('ol');n.questions.forEach((q,i)=>list.append(e('li','',`${i+1}. ${q.prompt} · ${results.get(q.id)?t.correct:t.incorrect}`)));result.append(list,action('review',t.review),action('retry',t.retry));body.append(result);return;}
  const q=n.questions[index],submitted=results.has(q.id),selected=selections.get(q.id)??new Set<string>(),fieldset=e('fieldset','iui-learning-question');fieldset.setAttribute('aria-describedby',id+'-kind');const legend=e('legend');legend.append(heading(`${index+1} / ${total} · ${q.prompt}`));fieldset.append(legend);const kind=e('p','iui-caption',q.kind==='single'?t.single:t.multiple);kind.id=id+'-kind';fieldset.append(kind);formula(fieldset,q.latex);
  q.choices.forEach((choice,i)=>{const label=e('label','iui-learning-choice'),input=e('input');input.type=q.kind==='single'?'radio':'checkbox';input.name=id+'-'+q.id;input.value=choice.id;input.id=id+'-choice-'+i;input.dataset.learningChoice=choice.id;input.checked=selected.has(choice.id);input.disabled=submitted;label.append(input,e('span','',choice.label));if(submitted){label.dataset.correct=String(q.correct.includes(choice.id));if(q.correct.includes(choice.id))label.append(e('span','iui-learning-choice-note',t.answer));}fieldset.append(label);});body.append(fieldset);
  if(submitted){const feedback=e('div','iui-learning-feedback');feedback.dataset.correct=String(results.get(q.id));feedback.append(e('strong','',results.get(q.id)?t.correct:t.incorrect),e('p','',`${t.answer}: ${q.choices.filter(v=>q.correct.includes(v.id)).map(v=>v.label).join('；')}`),e('p','',q.explanation));formula(feedback,q.explanationLatex);body.append(feedback);}
  const nav=e('nav','iui-learning-nav');nav.setAttribute('aria-label',t.question);nav.append(action('previous',t.previous,index===0),action('check',t.check,submitted||selected.size===0),action('next',index===total-1?t.result:t.next,!submitted));body.append(nav);
 }
 function cards(){if(n.type!=='flashcards')return;const total=n.cards.length;if(!total){body.append(e('p','iui-learning-empty',t.emptyCards));return;}const mastered=[...ratings.values()].filter(v=>v==='mastered').length;body.append(progress(ratings.size,total,t.rated),e('p','iui-caption',`${t.mastered}: ${mastered} / ${total}`));
  if(summary){body.append(heading(t.complete),e('p','iui-learning-score',`${t.mastered}: ${mastered} / ${total}`),action('review',t.review),action('retry',t.retry));return;}
  const card=n.cards[index],panel=e('div','iui-flashcard');panel.dataset.side=revealed?'back':'front';panel.append(heading(`${t.card} ${index+1} / ${total}`));const text=e('p','iui-flashcard-text',revealed?card.back:card.front);panel.append(text);formula(panel,revealed?card.backLatex:card.frontLatex);if(!revealed&&card.hint)panel.append(e('p','iui-caption',`${t.hint}: ${card.hint}`));const flip=action('flip',revealed?t.front:t.reveal);flip.setAttribute('aria-expanded',String(revealed));flip.setAttribute('aria-controls',id+'-face');text.id=id+'-face';panel.append(flip,e('p','iui-caption',ratings.has(card.id)?t[ratings.get(card.id)!]:t.unrated));body.append(panel);
  const rating=e('div','iui-learning-rating');rating.append(action('mastered',t.mastered,!revealed),action('again',t.again,!revealed));for(const b of rating.querySelectorAll('button'))b.setAttribute('aria-pressed',String(ratings.get(card.id)===b.dataset.learningAction));body.append(rating);
  const nav=e('nav','iui-learning-nav');nav.setAttribute('aria-label',t.card);nav.append(action('previous',t.prevCard,index===0),action('next',t.nextCard,index===total-1));if(ratings.size===total)nav.append(action('result',t.result));body.append(nav);
 }
 function paint(){const active=c.doc.activeElement,focused=active&&root.contains(active)?{choice:(active as HTMLElement).dataset.learningChoice,action:(active as HTMLElement).dataset.learningAction}:null;body.replaceChildren();const status=n.status??'ready';root.dataset.status=status;root.setAttribute('aria-busy',String(status==='loading'));if(status!=='ready'){const message=e('p','iui-learning-empty',n.message??(status==='loading'?c.labels().loading:c.labels().loadError));message.setAttribute('role',status==='error'?'alert':'status');body.append(message);return;}if(n.type==='quiz')quiz();else cards();if(focused){const selector=focused.choice?`[data-learning-choice="${focused.choice}"]`:focused.action?`[data-learning-action="${focused.action}"]`:null;if(selector)body.querySelector<HTMLElement>(selector)?.focus();}}
 const focusHeading=()=>body.querySelector<HTMLElement>('.iui-learning-heading')?.focus();
 c.on(root,'change',event=>{const target=event.target as HTMLInputElement;if(n.type!=='quiz'||target.tagName!=='INPUT'||!target.hasAttribute('data-learning-choice'))return;const q=n.questions[index];if(!q||results.has(q.id))return;const selected=q.kind==='single'?new Set<string>():new Set(selections.get(q.id));if(target.checked)selected.add(target.value);else selected.delete(target.value);selections.set(q.id,selected);paint();});
 c.on(root,'click',event=>{const target=event.target as Element;if(!('closest'in target))return;const button=target.closest<HTMLButtonElement>('button[data-learning-action]');if(!button||button.disabled||!root.contains(button))return;const name=button.dataset.learningAction;if(name==='retry'){index=0;summary=false;revealed=false;selections.clear();results.clear();ratings.clear();live.textContent='';paint();focusHeading();return;}if(name==='review'){summary=false;index=0;revealed=false;live.textContent='';paint();focusHeading();return;}if(name==='result'){summary=true;paint();focusHeading();return;}
  if(n.type==='quiz'){const q=n.questions[index];if(!q)return;if(name==='check'){const selected=selections.get(q.id);if(results.has(q.id)||!selected?.size)return;const correct=selected.size===q.correct.length&&q.correct.every(id=>selected.has(id));results.set(q.id,correct);live.textContent=`${correct?t.correct:t.incorrect} · ${q.explanation}`;paint();body.querySelector<HTMLElement>('[data-learning-action="next"]')?.focus();}else if(name==='next'&&results.has(q.id)){if(index===n.questions.length-1)summary=true;else index++;live.textContent='';paint();focusHeading();}else if(name==='previous'&&index>0){index--;live.textContent='';paint();focusHeading();}}
  else{const card=n.cards[index];if(!card)return;if(name==='flip'){revealed=!revealed;live.textContent=revealed?card.back:card.front;paint();}else if((name==='mastered'||name==='again')&&revealed){ratings.set(card.id,name);live.textContent=t[name];paint();}else if(name==='next'&&index<n.cards.length-1){index++;revealed=false;live.textContent='';paint();focusHeading();}else if(name==='previous'&&index>0){index--;revealed=false;live.textContent='';paint();focusHeading();}}
 });
 c.bind(paint);return root;
}
