import type {F1RacesNode,F1StandingsNode} from '../schema/document.js';
import type {RendererContext} from './context.js';
import type {MotorsportLabels} from './motorsport-labels.js';
import {readerBlocked,readerNativeReset} from './reader-controls.js';
export interface MotorsportSessionDetail {readonly componentId:string|null;readonly raceId:string|null;readonly sessionId:string|null;}
let serial=0;
function shell(c:RendererContext,label:string,description:string|undefined,t:MotorsportLabels,kind:string) {
 const root=c.element('section','iui-motorsport '+kind),base=`iui-motorsport-${c.prefix}${++serial}`,title=c.element('h2','',label);
 root.dir='auto';title.id=base+'-title';root.setAttribute('aria-labelledby',title.id);root.append(title,c.element('p','iui-motorsport-note',t.note));
 if(description!==undefined)root.append(c.element('p','iui-motorsport-text',description));return {root,base};
}
function source(c:RendererContext,parent:HTMLElement,s:{label:string;url:string}|undefined,t:MotorsportLabels) {
 if(!s)return;const a=c.element('a','',s.label+` (${t.newTab})`);a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';a.referrerPolicy='no-referrer';const p=c.element('p','iui-motorsport-source',t.source+': ');p.append(a);parent.append(p);
}
function select(c:RendererContext,parent:HTMLElement,id:string,label:string,choices:readonly (readonly [string,string])[],initial='') {
 const caption=c.element('label','',label),control=c.element('select');caption.htmlFor=control.id=id;
 for(const [value,text]of choices){const option=c.element('option','',text);option.value=value;option.defaultSelected=value===initial;control.append(option);}parent.append(caption,control);return control;
}
function search(c:RendererContext,parent:HTMLElement,id:string,t:MotorsportLabels){const caption=c.element('label','',t.search),control=c.element('input');caption.htmlFor=control.id=id;control.type='search';control.maxLength=200;parent.append(caption,control);return control;}
function time(c:RendererContext,parent:HTMLElement,label:string,value:string|null|undefined,t:MotorsportLabels){const p=c.element('p','',label+': ');if(value){const stamp=c.element('time','',value);stamp.dateTime=value;stamp.dir='ltr';p.append(stamp);}else p.append(c.doc.createTextNode(t.unknown));parent.append(p);}
export function renderMotorsportRaces(c:RendererContext,n:F1RacesNode,t:MotorsportLabels):HTMLElement {
 const e=c.element,{root,base}=shell(c,n.label,n.description,t,'iui-f1-races'),fieldset=e('fieldset'),toolbar=e('div','iui-motorsport-toolbar');fieldset.disabled=n.disabled??false;fieldset.append(e('legend','',n.label),toolbar);root.append(fieldset);
 const seasons=[...new Set(n.races.map(r=>r.season))].sort((a,b)=>a-b),query=search(c,toolbar,base+'-query',t),season=select(c,toolbar,base+'-season',t.season,[['',t.all],...seasons.map(s=>[String(s),String(s)]as const)]),kind=select(c,toolbar,base+'-kind',t.kind,[['',t.all],...Object.entries(t.kinds)]),state=select(c,toolbar,base+'-status',t.status,[['',t.all],...Object.entries(t.statuses)]),reset=e('button','iui-motorsport-reset',t.reset),clear=e('button','iui-motorsport-clear',t.clear),count=e('p','iui-motorsport-count'),empty=e('p','iui-motorsport-empty'),list=e('ol','iui-motorsport-races'),selection=e('p','iui-motorsport-selection'),status=e('p','iui-motorsport-status');reset.type=clear.type='button';toolbar.append(reset);count.setAttribute('role','status');selection.setAttribute('role','status');status.setAttribute('role','status');fieldset.append(count,empty,list,selection,clear,status);
 let alive=true,busy=false,revision=0,values=['','','',''],selected:{raceId:string;sessionId:string}|null=null;
 const controls=[query,season,kind,state],allowed=[[],['',...seasons.map(String)],['',...Object.keys(t.kinds)],['',...Object.keys(t.statuses)]];
 const rows=n.races.map(race=>{const row=e('li','iui-motorsport-race');row.dataset.raceId=race.id;row.append(e('h3','',`${race.season} · ${t.round} ${race.round} · ${race.label}`),e('p','',`${t.circuit}: ${race.circuit} · ${t.location}: ${race.location}`));const disclosure=e('details');disclosure.open=true;disclosure.append(e('summary','',t.sessions));const sessions=e('ul');if(!race.sessions.length)disclosure.append(e('p','',t.noSessions));disclosure.append(sessions);row.append(disclosure);source(c,row,race.source,t);list.append(row);
  const sessionRows=race.sessions.map(session=>{const item=e('li','iui-motorsport-session');item.dataset.sessionId=session.id;const title=e('h4','',session.label),button=e('button','iui-motorsport-session-choice',t.choose+': '+session.label);button.type='button';item.append(title,e('p','',`${t.kinds[session.kind]} · ${t.statuses[session.status]}`));time(c,item,t.starts,session.startsAt,t);if(session.endsAt!==undefined)time(c,item,t.ends,session.endsAt,t);if(session.note!==undefined)item.append(e('p','iui-motorsport-text',session.note));item.append(button);sessions.append(item);const itemOwned=()=>item.parentElement===sessions&&sessions.parentElement===disclosure&&disclosure.parentElement===row&&row.parentElement===list&&list.parentElement===fieldset;const owned=()=>button.parentElement===item&&itemOwned();c.on(button,'click',()=>choose({raceId:race.id,sessionId:session.id},button,()=>owned()&&disclosure.open));return {session,item,button,owned,itemOwned};});return {race,row,sessionRows,haystack:`${race.label} ${race.circuit} ${race.location} ${race.season}`.toLowerCase()};
 });
 const restore=()=>{if(alive)controls.forEach((control,i)=>{if(root.contains(control))control.value=values[i];});};
 const put=(el:HTMLElement,text:string)=>{if(alive&&root.contains(el))el.textContent=text;};
 const paint=()=>{if(!alive)return;restore();let shown=0,selectedVisible=false;for(const row of rows){let matchedSessions=0;for(const item of row.sessionRows){const matches=(!values[2]||item.session.kind===values[2])&&(!values[3]||item.session.status===values[3]);if(matches)matchedSessions++;if(root.contains(item.item)&&item.itemOwned())item.item.hidden=!matches;const chosen=selected?.raceId===row.race.id&&selected.sessionId===item.session.id;if(root.contains(item.button)&&item.owned())item.button.setAttribute('aria-pressed',String(chosen));if(chosen)selectedVisible=matches&&(!values[1]||String(row.race.season)===values[1])&&row.haystack.includes(values[0].toLowerCase());}
   const visible=(!values[1]||String(row.race.season)===values[1])&&row.haystack.includes(values[0].toLowerCase())&&((!values[2]&&!values[3])||matchedSessions>0);if(root.contains(row.row)&&row.row.parentElement===list&&list.parentElement===fieldset){row.row.hidden=!visible;if(visible)shown++;}}
  put(count,t.count(shown,rows.length));if(root.contains(empty)){empty.hidden=shown>0;empty.textContent=rows.length?t.noMatches:t.noRaces;}const chosen=selected?rows.find(r=>r.race.id===selected?.raceId):undefined;put(selection,!selected?t.none:`${t.selected}: ${chosen?.race.label??''} / ${chosen?.sessionRows.find(s=>s.session.id===selected?.sessionId)?.session.label??''}${selectedVisible?'':' · '+t.filtered}`);if(root.contains(clear))clear.setAttribute('aria-disabled',String(!selected));if(root.contains(reset))reset.setAttribute('aria-disabled',String(values.every(v=>!v)));
 };
 function choose(next:typeof selected,button:HTMLButtonElement,owned:()=>boolean=()=>button.parentElement===fieldset){if(busy||!owned()||readerBlocked(root,button,alive)||(!next&&!selected))return;busy=true;const blocked=()=>!owned()||readerBlocked(root,button,alive);try{const detail:MotorsportSessionDetail=Object.freeze({componentId:n.id??null,raceId:next?.raceId??null,sessionId:next?.sessionId??null}),Ctor=c.doc.defaultView?.CustomEvent;if(blocked())return;let event:CustomEvent<MotorsportSessionDetail>;if(typeof Ctor==='function')event=new Ctor('iui:motorsport-session',{detail,bubbles:true,cancelable:true,composed:false});else{event=c.doc.createEvent('CustomEvent');event.initCustomEvent('iui:motorsport-session',true,true,detail);}if(blocked())return;const accepted=root.dispatchEvent(event);if(blocked())return;if(accepted){selected=next;revision++;}put(status,accepted?t.selected:t.cancelled);paint();}catch{if(!blocked())put(status,t.failed);}finally{busy=false;}}
 controls.forEach((control,i)=>c.on(control,i===0?'input':'change',()=>{if(!alive)return;const valid=i===0?control.value.length<=200:(control as HTMLSelectElement).selectedIndex>=0&&allowed[i].includes(control.value);if(busy||readerBlocked(root,control,alive)||!valid){restore();return;}values[i]=control.value;revision++;paint();}));
 const resetFilters=()=>{values=['','','',''];revision++;paint();};c.on(reset,'click',()=>{if(!busy&&![reset,...controls].some(control=>readerBlocked(root,control,alive)))resetFilters();});c.on(clear,'click',()=>choose(null,clear));readerNativeReset(c,root,controls,()=>revision,restore,resetFilters);c.cleanup(()=>{alive=false;});paint();return root;
}
export function renderMotorsportStandings(c:RendererContext,n:F1StandingsNode,t:MotorsportLabels):HTMLElement {
 const e=c.element,{root,base}=shell(c,n.label,n.description,t,'iui-f1-standings');root.append(e('p','',`${t.season}: ${n.season}`));if(n.observedAt!==undefined)time(c,root,t.observed,n.observedAt,t);
 const toolbar=e('div','iui-motorsport-toolbar');root.append(toolbar);const initial=n.standings.some(s=>s.kind==='driver')?'driver':'constructor',query=search(c,toolbar,base+'-query',t),category=select(c,toolbar,base+'-category',t.category,[['driver',t.driver],['constructor',t.constructor]],initial),order=select(c,toolbar,base+'-order',t.order,[['source',t.sourceOrder],['rank',t.rankOrder],['points',t.pointsOrder],['name',t.nameOrder]],'source'),reset=e('button','iui-motorsport-reset',t.reset);reset.type='button';toolbar.append(reset);
 const count=e('p','iui-motorsport-count'),empty=e('p','iui-motorsport-empty'),wrap=e('div','iui-motorsport-table-scroll'),table=e('table'),caption=e('caption','',n.label),head=e('thead'),heading=e('tr'),body=e('tbody');count.setAttribute('role','status');const heads=[t.rank,t.name,t.team,t.points,t.wins,t.context].map(label=>{const th=e('th','',label);th.scope='col';heading.append(th);return th;});head.append(heading);table.append(caption,head,body);wrap.append(table);root.append(count,empty,wrap);
 let alive=true,revision=0,values=['',initial,'source'];const controls=[query,category,order],allowed=[[],['driver','constructor'],['source','rank','points','name']];
 const rows=n.standings.map((standing,index)=>{const row=e('tr');row.dataset.standingId=standing.id;const rank=e('td','',standing.rank??t.unknown),name=e('th','',standing.label),team=e('td','',standing.team??t.unknown),points=e('td','',standing.points??t.unknown),wins=e('td','',standing.wins??t.unknown),context=e('td');name.scope='row';rank.className=points.className=wins.className='iui-motorsport-number';if(standing.note!==undefined||standing.source){const detail=e('details');detail.append(e('summary','',t.context));if(standing.note!==undefined)detail.append(e('p','iui-motorsport-text',standing.note));source(c,detail,standing.source,t);context.append(detail);}else context.textContent=t.emptyContext;row.append(rank,name,team,points,wins,context);body.append(row);return {standing,index,row,haystack:(standing.label+' '+(standing.team??'')).toLowerCase()};});
 const restore=()=>{if(alive)controls.forEach((control,i)=>{if(root.contains(control))control.value=values[i];});};
 const paint=()=>{if(!alive)return;restore();const sorted=[...rows].sort((a,b)=>{const metric=values[2];if(metric==='source')return a.index-b.index;if(metric==='name'){const x=a.standing.label.toLowerCase(),y=b.standing.label.toLowerCase();return (x<y?-1:x>y?1:0)||a.index-b.index;}const x=metric==='rank'?a.standing.rank:a.standing.points,y=metric==='rank'?b.standing.rank:b.standing.points;return (x===null?(y===null?0:1):y===null?-1:metric==='rank'?x-y:y-x)||a.index-b.index;});let shown=0;
  for(const item of sorted){if(!root.contains(body)||item.row.parentElement!==body)continue;item.row.hidden=item.standing.kind!==values[1]||!item.haystack.includes(values[0].toLowerCase());if(!item.row.hidden)shown++;if(root.contains(body)&&item.row.parentElement===body)body.append(item.row);}
  heads.forEach((th,i)=>{if(!root.contains(th))return;const active=(values[2]==='rank'&&i===0)||(values[2]==='name'&&i===1)||(values[2]==='points'&&i===3);if(active)th.setAttribute('aria-sort',values[2]==='points'?'descending':'ascending');else th.removeAttribute('aria-sort');});
  if(root.contains(count))count.textContent=t.count(shown,n.standings.filter(s=>s.kind===values[1]).length);if(root.contains(empty)){empty.hidden=shown>0;empty.textContent=n.standings.length?t.noMatches:t.noStandings;}if(root.contains(reset))reset.setAttribute('aria-disabled',String(!values[0]&&values[1]===initial&&values[2]==='source'));
 };
 controls.forEach((control,i)=>c.on(control,i===0?'input':'change',()=>{if(!alive)return;const valid=i===0?control.value.length<=200:(control as HTMLSelectElement).selectedIndex>=0&&allowed[i].includes(control.value);if(readerBlocked(root,control,alive)||!valid){restore();return;}values[i]=control.value;revision++;paint();}));const resetFilters=()=>{values=['',initial,'source'];revision++;paint();};c.on(reset,'click',()=>{if(![reset,...controls].some(control=>readerBlocked(root,control,alive)))resetFilters();});readerNativeReset(c,root,controls,()=>revision,restore,resetFilters);c.cleanup(()=>{alive=false;});paint();return root;
}
