export const motorsportEnglish={
 note:'Supplied snapshot only. No live feed, inferred race result, scoring rule or current-time status.',search:'Search supplied records',season:'Season',kind:'Session type',status:'Supplied status',all:'All',reset:'Reset filters',unknown:'Not supplied',noMatches:'No matching records.',noRaces:'No races supplied.',noStandings:'No standings supplied.',sessions:'Supplied sessions',noSessions:'No sessions supplied.',choose:'Select session locally',clear:'Clear local selection',none:'No session selected.',selected:'Locally selected',cancelled:'Local selection canceled.',failed:'Local selection unavailable.',filtered:'The selected session is outside the current filters.',source:'Source',newTab:'opens a new tab',round:'Round',circuit:'Circuit',location:'Location',starts:'Start',ends:'End',category:'Standing category',driver:'Drivers',constructor:'Constructors',order:'Display order',sourceOrder:'Supplied order',rankOrder:'Supplied rank, lowest first',pointsOrder:'Supplied points, highest first',nameOrder:'Name',rank:'Supplied rank',points:'Supplied points',name:'Name',team:'Team',wins:'Supplied wins',context:'Context',observed:'Supplied observation',emptyContext:'No extra context supplied.',
 kinds:{practice:'Practice',qualifying:'Qualifying',sprint:'Sprint',race:'Race',other:'Other'},statuses:{scheduled:'Scheduled',complete:'Complete',cancelled:'Canceled',postponed:'Postponed',unknown:'Unknown'},count:(shown:number,total:number)=>`${shown} of ${total} supplied records`
};
export type MotorsportLabels=typeof motorsportEnglish;
export const motorsportChinese:MotorsportLabels={
 note:'仅展示已提供快照。不连接实时来源，不推断赛果、积分规则或当前状态。',search:'搜索已提供记录',season:'赛季',kind:'赛段类型',status:'已提供状态',all:'全部',reset:'重置筛选',unknown:'未提供',noMatches:'没有匹配记录。',noRaces:'未提供赛事。',noStandings:'未提供排名。',sessions:'已提供赛段',noSessions:'未提供赛段。',choose:'本地选择赛段',clear:'清除本地选择',none:'尚未选择赛段。',selected:'已本地选择',cancelled:'已取消本地选择。',failed:'本地选择不可用。',filtered:'已选赛段不在当前筛选结果中。',source:'来源',newTab:'在新标签页打开',round:'轮次',circuit:'赛道',location:'地点',starts:'开始',ends:'结束',category:'排名类别',driver:'车手',constructor:'车队',order:'展示顺序',sourceOrder:'提供顺序',rankOrder:'已提供名次，从低到高',pointsOrder:'已提供积分，从高到低',nameOrder:'名称',rank:'已提供名次',points:'已提供积分',name:'名称',team:'车队',wins:'已提供胜场',context:'详情',observed:'提供的观测时间',emptyContext:'未提供其他详情。',
 kinds:{practice:'练习',qualifying:'排位',sprint:'冲刺',race:'正赛',other:'其他'},statuses:{scheduled:'已安排',complete:'已完成',cancelled:'已取消',postponed:'已推迟',unknown:'未知'},count:(shown,total)=>`${shown} / ${total} 条已提供记录`
};
