import type {CreateInteractivePollNode} from '../schema/document.js';
import type {RendererContext} from './context.js';
import type {PollLabels} from './poll-labels.js';
export interface PollReadyDetail {readonly componentId:string|null;readonly question:string;readonly options:readonly Readonly<{id:string;label:string}>[];readonly multiple:boolean;}
interface DraftOption {id:string;label:string}
let serial=0;
/** A bounded local composer, not a voting provider or publish action. */
export function renderPoll(c:RendererContext,n:CreateInteractivePollNode,t:PollLabels):HTMLElement {
 const e=c.element,root=e('fieldset','iui-poll'),base=`iui-poll-internal-${c.prefix}${++serial}`;root.dir='auto';root.disabled=n.disabled??false;root.append(e('legend','iui-poll-title',n.label));
 if(n.description!==undefined)root.append(e('p','iui-poll-description',n.description));const note=e('p','iui-poll-note',t.note);note.id=base+'-note';root.append(note);root.setAttribute('aria-describedby',note.id);
 const questionLabel=e('label','iui-poll-question-label',t.question),question=e('textarea','iui-poll-question');question.id=base+'-question';questionLabel.htmlFor=question.id;question.rows=3;question.maxLength=1000;question.setAttribute('form',base+'-local-only');question.value=question.defaultValue=n.question??'';root.append(questionLabel,question);
 const optionLegend=e('h3','iui-poll-options-title',t.options);optionLegend.id=base+'-options';const list=e('div','iui-poll-options');list.setAttribute('aria-labelledby',optionLegend.id);root.append(optionLegend,list);
 const counts=e('p','iui-poll-count'),add=e('button','iui-poll-add',t.add);add.type='button';root.append(counts,add);
 const modeLabel=e('label','iui-poll-mode'),mode=e('input');mode.type='checkbox';mode.id=base+'-multiple';mode.setAttribute('form',base+'-local-only');modeLabel.htmlFor=mode.id;modeLabel.append(mode,e('span','',t.multiple));root.append(modeLabel);
 const actions=e('div','iui-poll-actions'),previewButton=e('button','iui-poll-preview-button',t.preview),prepare=e('button','iui-poll-prepare',t.prepare),reset=e('button','iui-poll-reset',t.reset);for(const button of [previewButton,prepare,reset])button.type='button';actions.append(previewButton,prepare,reset);root.append(actions);
 const preview=e('section','iui-poll-preview');preview.id=base+'-preview';preview.hidden=true;previewButton.setAttribute('aria-controls',preview.id);previewButton.setAttribute('aria-expanded','false');root.append(preview);
 const status=e('p','iui-poll-status');status.id=base+'-status';status.setAttribute('role','status');status.setAttribute('aria-live','polite');status.setAttribute('aria-atomic','true');prepare.setAttribute('aria-describedby',status.id);root.append(status);
 let alive=true,dispatching=false,questionDraft=n.question??'',multiple=n.multiple??false,options:DraftOption[]=n.options.map(x=>({...x})),nextId=0;
 type Row={element:HTMLDivElement;input:HTMLInputElement;label:HTMLLabelElement;up:HTMLButtonElement;down:HTMLButtonElement;remove:HTMLButtonElement;retire:()=>void};const rows=new Map<string,Row>();
 const owned=(control:HTMLElement)=>root.contains(control);
 const blocked=(control:HTMLElement)=>!alive||!root.isConnected||!control.isConnected||!root.contains(control)||control.matches(':disabled')||!!control.closest('[hidden],[inert]');
 const feedback=(kind:string,text:string)=>{if(!alive)return;root.dataset.status=kind;status.textContent=text;};
 const hidePreview=()=>{preview.hidden=true;if(owned(previewButton)){previewButton.textContent=t.preview;previewButton.setAttribute('aria-expanded','false');}};
 const edited=()=>{hidePreview();feedback('draft','');for(const row of rows.values())if(owned(row.input))row.input.removeAttribute('aria-invalid');if(owned(question))question.removeAttribute('aria-invalid');};
 function mutate(control:HTMLElement,fn:()=>void){if(blocked(control)||dispatching){paint();return;}fn();edited();paint();}
 function rowFor(option:DraftOption):Row {
  const element=e('div','iui-poll-option'),label=e('label','iui-poll-option-label'),input=e('input','iui-poll-option-input'),buttons=e('div','iui-poll-option-actions');input.type='text';input.maxLength=400;input.id=base+'-choice-'+(++nextId);input.setAttribute('form',base+'-local-only');label.htmlFor=input.id;element.dataset.optionId=option.id;
  const up=e('button','',t.up),down=e('button','',t.down),remove=e('button','',t.remove);for(const button of [up,down,remove])button.type='button';buttons.append(up,down,remove);element.append(label,input,buttons);const cleanups:(()=>void)[]=[];const on=(target:EventTarget,name:string,handler:EventListener)=>{target.addEventListener(name,handler);cleanups.push(()=>target.removeEventListener(name,handler));};const row={element,input,label,up,down,remove,retire:()=>{for(const cleanup of cleanups)cleanup();cleanups.length=0;}};
  on(input,'input',()=>mutate(input,()=>{const target=options.find(x=>x.id===option.id);if(target)target.label=input.value;}));
  const move=(button:HTMLButtonElement,direction:number)=>{if(blocked(button)||dispatching)return;const index=options.findIndex(x=>x.id===option.id),next=index+direction;if(index<0||next<0||next>=options.length)return;[options[index],options[next]]=[options[next],options[index]];edited();paint();if(!blocked(button))button.focus();};
  on(up,'click',()=>move(up,-1));on(down,'click',()=>move(down,1));
  on(remove,'click',()=>{if(blocked(remove)||dispatching||options.length<=2)return;const index=options.findIndex(x=>x.id===option.id);if(index<0)return;options.splice(index,1);edited();paint();const next=rows.get(options[Math.min(index,options.length-1)].id)?.input;if(next&&!blocked(next))next.focus();});
  return row;
 }
 function paint(){if(!alive)return;if(owned(question)){if(question.value!==questionDraft)question.value=questionDraft;question.defaultValue=questionDraft;}if(owned(mode))mode.checked=mode.defaultChecked=multiple;
  const ids=new Set(options.map(x=>x.id));for(const [id,row] of rows)if(!ids.has(id)){row.retire();if(owned(row.element))row.element.remove();rows.delete(id);}
  options.forEach((option,index)=>{let row=rows.get(option.id);if(!row){row=rowFor(option);rows.set(option.id,row);list.append(row.element);}if(!owned(row.element))return;if(owned(row.label))row.label.textContent=t.option(index+1);if(owned(row.input)){if(row.input.value!==option.label)row.input.value=option.label;row.input.defaultValue=option.label;}for(const [button,text] of [[row.up,t.up],[row.down,t.down],[row.remove,t.remove]] as const)if(owned(button))button.setAttribute('aria-label',`${text}: ${t.option(index+1)}`);if(owned(row.up))row.up.setAttribute('aria-disabled',String(index===0));if(owned(row.down))row.down.setAttribute('aria-disabled',String(index===options.length-1));if(owned(row.remove))row.remove.setAttribute('aria-disabled',String(options.length<=2));if(list.children[index]!==row.element)list.insertBefore(row.element,list.children[index]??null);});counts.textContent=t.count(options.length);if(owned(add))add.setAttribute('aria-disabled',String(options.length>=8));
 }
 c.on(question,'input',()=>mutate(question,()=>{questionDraft=question.value;}));c.on(mode,'change',()=>mutate(mode,()=>{multiple=mode.checked;}));
 c.on(add,'click',()=>{if(blocked(add)||dispatching||options.length>=8)return;let id:string;do{id='choice-'+(++nextId);}while(options.some(x=>x.id===id));options.push({id,label:''});edited();paint();const next=rows.get(id)?.input;if(next&&!blocked(next))next.focus();});
 c.on(reset,'click',()=>{if(blocked(reset)||dispatching)return;questionDraft=n.question??'';multiple=n.multiple??false;options=n.options.map(x=>({...x}));edited();paint();});
 c.on(previewButton,'click',()=>{if(blocked(previewButton)||dispatching)return;if(!preview.hidden){hidePreview();return;}preview.replaceChildren(e('h3','',questionDraft.trim()?questionDraft:t.emptyPreview),e('p','',t.previewMode(multiple)));const choices=e('ol');for(const option of options)choices.append(e('li','',option.label.trim()?option.label:t.emptyPreview));preview.append(choices);preview.hidden=false;previewButton.textContent=t.hidePreview;previewButton.setAttribute('aria-expanded','true');});
 function invalid(control:HTMLTextAreaElement|HTMLInputElement,message:string){control.setAttribute('aria-invalid','true');control.setAttribute('aria-describedby',status.id);feedback('invalid',message);control.focus();}
 const readyBlocked=()=>blocked(prepare)||blocked(question)||blocked(mode)||options.some(option=>{const row=rows.get(option.id);return !row||blocked(row.input);});
 c.on(prepare,'click',()=>{if(readyBlocked()||dispatching)return;question.removeAttribute('aria-invalid');for(const row of rows.values())row.input.removeAttribute('aria-invalid');
  if(!questionDraft.trim()){invalid(question,t.questionRequired);return;}if([...questionDraft].length>500){invalid(question,t.questionLong);return;}const labels=new Set<string>();for(const option of options){const control=rows.get(option.id)!.input;if(!option.label.trim()){invalid(control,t.optionRequired);return;}if([...option.label].length>200){invalid(control,t.optionLong);return;}if(labels.has(option.label.trim())){invalid(control,t.duplicate);return;}labels.add(option.label.trim());}
  dispatching=true;try{const detail:PollReadyDetail=Object.freeze({componentId:n.id??null,question:questionDraft,options:Object.freeze(options.map(option=>Object.freeze({...option}))),multiple});const Constructor=c.doc.defaultView?.CustomEvent;if(readyBlocked())return;let event:CustomEvent<PollReadyDetail>;if(typeof Constructor==='function')event=new Constructor('iui:poll-ready',{detail,bubbles:true,cancelable:true,composed:false});else{event=c.doc.createEvent('CustomEvent');event.initCustomEvent('iui:poll-ready',true,true,detail);}if(readyBlocked())return;const accepted=root.dispatchEvent(event);if(readyBlocked())return;feedback(accepted?'ready':'not-accepted',accepted?t.ready:t.rejected);}catch{if(!readyBlocked())feedback('error',t.error);}finally{dispatching=false;}
 });
 c.cleanup(()=>{alive=false;for(const row of rows.values())row.retire();});paint();feedback('draft','');return root;
}
