import type {ProductCardNode} from '../schema/document.js';import type {RendererContext} from './context.js';import type {DecisionLabels} from './decision-labels.js';import {readerBlocked} from './reader-controls.js';import {ledgerSubtotal} from '../core/ledger.js';
export interface ProductChoiceDetail{readonly componentId:string|null;readonly productId:string;readonly variantId:string|null;readonly quantity:number;readonly availability:'available'|'unavailable'|'unknown';readonly unitPrice:Readonly<{amount:number;currency:string}>|null;readonly itemSubtotal:string|null;}
let serial=0;
export function renderProductCard(c:RendererContext,n:ProductCardNode,t:DecisionLabels):HTMLElement{
 const e=c.element,root=e('section','iui-product-card iui-decision-card'),base=`iui-product-internal-${c.prefix}${++serial}`;root.dir='auto';const title=e('h2','iui-product-title',n.name);title.id=base+'-title';root.setAttribute('aria-labelledby',title.id);root.append(title);if(n.brand!==undefined)root.append(e('p','iui-product-brand',n.brand));if(n.seller!==undefined)root.append(e('p','iui-product-seller',n.seller));const note=e('p','iui-decision-note',t.productNote);note.id=base+'-note';root.setAttribute('aria-describedby',note.id);root.append(note);if(n.description!==undefined){const details=e('details');details.append(e('summary','',t.description),e('p','iui-decision-description',n.description));root.append(details);}
 let alive=true,dispatching=false,variant=n.initialVariantId??'',quantityDraft=String(n.initialQuantity??1);const variants=n.variants??[],initialVariant=variant,initialQuantity=quantityDraft;
 if(n.image){const image=e('img','iui-product-image'),fallback=e('p','iui-product-image-error',t.imageError);image.alt=n.image.alt;image.loading='lazy';image.decoding='async';image.draggable=false;fallback.hidden=true;root.append(image,fallback);c.on(image,'error',()=>{if(!alive||!root.isConnected||!root.contains(image))return;image.hidden=true;if(root.contains(fallback))fallback.hidden=false;});image.src=n.image.src;}
 const priceText=e('p','iui-product-price'),availabilityText=e('p','iui-product-availability'),subtotal=e('p','iui-product-subtotal');root.append(priceText,availabilityText);
 const controls=e('fieldset','iui-product-controls');controls.disabled=n.disabled??false;controls.append(e('legend','',t.review));let select:HTMLSelectElement|undefined;
 if(variants.length){const label=e('label','',t.variant);select=e('select','iui-product-variant');select.id=base+'-variant';select.setAttribute('form',base+'-local-only');label.htmlFor=select.id;for(const [value,text] of [['',t.chooseVariant],...variants.map(item=>[item.id,`${item.label} — ${t.availabilityLabels[item.availability]}`])]){const option=e('option','',text);option.value=value;option.defaultSelected=value===initialVariant;select.append(option);}controls.append(label,select);}
 const quantityLabel=e('label','',t.quantity),quantity=e('input','iui-product-quantity');quantity.type='number';quantity.min='1';quantity.max='20';quantity.step='1';quantity.inputMode='numeric';quantity.id=base+'-quantity';quantity.setAttribute('form',base+'-local-only');quantityLabel.htmlFor=quantity.id;const counter=e('div','iui-product-counter'),decrease=e('button','',t.decrease),increase=e('button','',t.increase);decrease.type=increase.type='button';counter.append(decrease,quantity,increase);controls.append(quantityLabel,counter,subtotal,e('p','iui-decision-note',t.subtotalNote));const review=e('button','iui-product-review',t.review),reset=e('button','iui-product-reset',t.productReset);review.type=reset.type='button';controls.append(review,reset);root.append(controls);const status=e('p','iui-product-status');status.id=base+'-status';status.setAttribute('role','status');status.setAttribute('aria-live','polite');review.setAttribute('aria-describedby',status.id);root.append(status);
 const put=(element:HTMLElement,text:string)=>{if(alive&&root.contains(element))element.textContent=text;};const amount=()=>{if(quantityDraft.length>64||!/^0*(?:[1-9]|1\d|20)(?:\.0+)?$/.test(quantityDraft))return null;const value=Number(quantityDraft);return Number.isFinite(value)&&Number.isInteger(value)&&value>=1&&value<=20?value:null;};const chosen=()=>variants.find(item=>item.id===variant);const offered=()=>chosen()?.price??n.price;const available=()=>chosen()?.availability??n.availability;
 const restore=()=>{if(!alive)return;if(root.contains(quantity)){quantity.value=quantityDraft;quantity.defaultValue=quantityDraft;}if(select&&root.contains(select)){select.value=variant;for(const option of select.options)option.defaultSelected=option.value===variant;}};
 const paint=()=>{if(!alive)return;restore();const price=offered(),count=amount(),availability=available();put(priceText,price?`${t.productPrice}: ${price.amount} ${price.currency}`:t.priceUnknown);put(availabilityText,`${t.availability}: ${t.availabilityLabels[availability]}`);put(subtotal,count===null?t.quantityError:variants.length&&!variant?t.chooseVariant:price?`${t.subtotal}: ${ledgerSubtotal(Array(count).fill(price.amount))} ${price.currency}`:t.priceUnknown);if(root.contains(decrease))decrease.setAttribute('aria-disabled',String(count===1||count===null));if(root.contains(increase))increase.setAttribute('aria-disabled',String(count===20||count===null));if(root.contains(review))review.setAttribute('aria-disabled',String(availability==='unavailable'));};
 const edit=()=>{put(status,'');if(root.contains(quantity))quantity.removeAttribute('aria-invalid');paint();};
 c.on(quantity,'input',()=>{if(!alive)return;if(dispatching||readerBlocked(root,quantity,alive)){restore();return;}quantityDraft=quantity.value;edit();});if(select){const field=select;c.on(field,'change',()=>{if(!alive)return;if(dispatching||readerBlocked(root,field,alive)||field.selectedIndex<0||(field.value!==''&&!variants.some(item=>item.id===field.value))){restore();return;}if(variant===field.value)return;variant=field.value;edit();});}
 const adjust=(button:HTMLButtonElement,direction:number)=>{if(dispatching||readerBlocked(root,button,alive)||readerBlocked(root,quantity,alive))return;const count=amount();if(count===null){put(status,t.quantityError);quantity.focus();return;}if(count+direction<1||count+direction>20)return;quantityDraft=String(count+direction);edit();};c.on(decrease,'click',()=>adjust(decrease,-1));c.on(increase,'click',()=>adjust(increase,1));
 c.on(reset,'click',()=>{if(dispatching||readerBlocked(root,reset,alive)||readerBlocked(root,quantity,alive)||(select&&readerBlocked(root,select,alive)))return;variant=initialVariant;quantityDraft=initialQuantity;edit();});
 const unavailable=()=>readerBlocked(root,review,alive)||readerBlocked(root,quantity,alive)||!!select&&readerBlocked(root,select,alive);
 c.on(review,'click',()=>{if(dispatching||unavailable())return;const count=amount();if(count===null){quantity.setAttribute('aria-invalid','true');put(status,t.quantityError);quantity.focus();return;}if(variants.length&&!variant){put(status,t.variantError);select!.focus();return;}if(available()==='unavailable'){put(status,t.unavailableError);return;}dispatching=true;try{const price=offered(),detail:ProductChoiceDetail=Object.freeze({componentId:n.id??null,productId:n.productId,variantId:variant||null,quantity:count,availability:available(),unitPrice:price?Object.freeze({...price}):null,itemSubtotal:price?ledgerSubtotal(Array(count).fill(price.amount)):null}),Constructor=c.doc.defaultView?.CustomEvent;if(unavailable())return;let event:CustomEvent<ProductChoiceDetail>;if(typeof Constructor==='function')event=new Constructor('iui:product-choice',{detail,bubbles:true,cancelable:true,composed:false});else{event=c.doc.createEvent('CustomEvent');event.initCustomEvent('iui:product-choice',true,true,detail);}if(unavailable())return;const accepted=root.dispatchEvent(event);if(unavailable())return;put(status,accepted?t.ready:t.rejected);}catch{if(!unavailable())put(status,t.error);}finally{dispatching=false;}});
 if(n.source){const source=e('p','iui-decision-source'),link=e('a','',`${n.source.label} (${t.newTab})`);link.href=n.source.url;link.target='_blank';link.rel='noopener noreferrer';link.referrerPolicy='no-referrer';source.append(c.doc.createTextNode(t.source+': '),link);root.append(source);}c.cleanup(()=>{alive=false;});paint();return root;
}
