import type {SidebarPeopleAlsoAskNode} from '../schema/document.js';
import type {RendererContext} from './context.js';
import type {RelatedQuestionsLabels} from './related-questions-labels.js';
import {readerBlocked,readerNativeReset} from './reader-controls.js';
let serial=0;
export function renderRelatedQuestions(c:RendererContext,n:SidebarPeopleAlsoAskNode,t:RelatedQuestionsLabels):HTMLElement {
 const e=c.element,root=e('section','iui-related-questions'),base=`iui-questions-internal-${c.prefix}${++serial}`,title=e('h2','iui-questions-title',n.label);title.id=base+'-title';root.setAttribute('aria-labelledby',title.id);root.dir='auto';root.append(title);if(n.description!==undefined)root.append(e('p','iui-questions-description',n.description));const note=e('p','iui-questions-note',t.note);note.id=base+'-note';root.setAttribute('aria-describedby',note.id);root.append(note);
 const toolbar=e('div','iui-questions-toolbar'),label=e('label','',t.search),search=e('input','iui-questions-search'),clear=e('button','',t.clear);search.type='search';search.maxLength=200;search.id=base+'-search';label.htmlFor=search.id;clear.type='button';toolbar.append(label,search,clear);root.append(toolbar);
 const count=e('p','iui-questions-count'),empty=e('p','iui-questions-empty'),list=e('div','iui-questions-list');count.setAttribute('role','status');count.setAttribute('aria-live','polite');root.append(count,empty,list);const expanded=new Set(n.expanded??[]);
 const rows=n.items.map(item=>{const details=e('details','iui-question'),summary=e('summary','iui-question-summary',item.question);details.dataset.questionId=item.id;details.open=expanded.has(item.id);details.append(summary);const answer=e('div','iui-question-answer',item.answer??t.unanswered);answer.classList.toggle('iui-question-unanswered',item.answer===null);details.append(answer);if(item.sources?.length){const heading=e('h3','iui-question-sources-title',t.sources),sources=e('ul','iui-question-sources');for(const source of item.sources){const row=e('li'),link=e('a','',source.label),hint=e('span','iui-question-link-hint',` (${t.newTab})`);link.href=source.url;link.target='_blank';link.rel='noopener noreferrer';link.referrerPolicy='no-referrer';link.append(hint);row.append(link);sources.append(row);}details.append(heading,sources);}else details.append(e('p','iui-question-unsourced',t.unsourced));list.append(details);return{details,text:(item.question+'\n'+(item.answer??'')).toLowerCase()};});
 let query='',revision=0,alive=true;const restore=()=>{if(alive&&root.contains(search))search.value=query;};
 const paint=()=>{if(!alive)return;restore();let shown=0;for(const row of rows){const match=row.text.includes(query.toLowerCase());if(root.contains(row.details))row.details.hidden=!match;if(match)shown++;}if(root.contains(clear))clear.setAttribute('aria-disabled',String(query===''));count.textContent=t.count(shown,rows.length);empty.hidden=shown>0;empty.textContent=rows.length?t.noMatch:t.empty;};
 c.on(search,'input',()=>{if(readerBlocked(root,search,alive)||search.value.length>200){restore();return;}query=search.value;revision++;paint();});c.on(clear,'click',()=>{if(readerBlocked(root,clear,alive)||query==='')return;query='';revision++;paint();});readerNativeReset(c,root,[search],()=>revision,restore,()=>{query='';revision++;paint();});c.cleanup(()=>{alive=false;});paint();return root;
}
