import type {SportsGame,SportsStanding} from '../schema/document.js';
import type {SportsNode} from '../core/sports.js';
import type {RendererContext} from './context.js';
import {dateInZone,timestamp} from '../core/extensions.js';
let serial=0;
/** Three local views over one supplied sports model. No live connection, timer or ranking inference. */
export function renderSports(c:RendererContext,n:SportsNode):HTMLElement{
  const {element:e,on}=c,d=n.data,l=c.labels(),zh=l.missing==='缺测',locale=zh?'zh-CN':'en-US';
  const t=zh?{schedule:'赛程',scoreboard:'记分牌',standings:'积分榜',all:'全部',date:'比赛日期',team:'球队',stage:'阶段',group:'分组',game:'选择比赛',rank:'名次',played:'场次',won:'胜',drawn:'平',lost:'负',points:'积分',for:'得分',against:'失分',note:'说明',home:'主队',away:'客队',neutral:'中立场地',period:'分节比分',stats:'比赛数据',winner:'获胜',missing:'比分缺测',sort:'排序',empty:'没有符合筛选条件的比赛',noStandings:'暂无积分榜数据',snapshot:'数据快照，不自动刷新',showDetails:'比赛详情',scheduled:'未开赛',live:'进行中',final:'已结束',postponed:'延期',cancelled:'已取消',providedRank:'名次来自数据源，排序不重算排名',football:'足球',basketball:'篮球',baseball:'棒球',hockey:'冰球',other:'体育'}:{schedule:'Schedule',scoreboard:'Scoreboard',standings:'Standings',all:'All',date:'Game date',team:'Team',stage:'Stage',group:'Group',game:'Choose a game',rank:'Rank',played:'Played',won:'Won',drawn:'Drawn',lost:'Lost',points:'Points',for:'For',against:'Against',note:'Note',home:'Home',away:'Away',neutral:'Neutral venue',period:'Period scores',stats:'Game stats',winner:'Winner',missing:'Score missing',sort:'Sort',empty:'No games match the filters',noStandings:'No standings available',snapshot:'Supplied snapshot; does not refresh automatically',showDetails:'Game details',scheduled:'Scheduled',live:'Live',final:'Final',postponed:'Postponed',cancelled:'Cancelled',providedRank:'Ranks are supplied, not recomputed by sorting',football:'Football',basketball:'Basketball',baseball:'Baseball',hockey:'Hockey',other:'Sports'};
  const view=n.type.slice('sports-'.length) as 'schedule'|'scoreboard'|'standings',id=`${c.prefix}sports-${++serial}`,root=e('section',`iui-sports iui-sports-${view}`);root.setAttribute('aria-label',`${d.league.name} · ${t[view]}`);root.dataset.league=d.league.id;
  const header=e('header','iui-sports-header'),title=e('div');title.append(e('p','iui-caption',[t[d.league.sport],d.league.season].filter(Boolean).join(' · ')),e('h2','iui-sports-title',d.league.name));header.append(title,e('span','iui-badge',t[view]));
  const toolbar=e('div','iui-sports-toolbar'),status=e('p','iui-sports-status'),body=e('div','iui-sports-body');status.setAttribute('role','status');
  const footer=e('footer','iui-sports-source'),source=e('p');source.append(c.doc.createTextNode(`${l.source}: `));if(d.source.url){const link=e('a','',d.source.label);link.href=d.source.url;link.target='_blank';link.rel='noopener noreferrer';link.referrerPolicy='no-referrer';source.append(link);}else source.append(c.doc.createTextNode(d.source.label));if(d.source.synthetic)source.append(e('strong','iui-sports-synthetic',l.synthetic));
  const fullTime=(value:string)=>new Intl.DateTimeFormat(locale,{timeZone:d.timezone,year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23',timeZoneName:'longOffset'}).format(new Date(value));
  const localClock=(value:string)=>new Intl.DateTimeFormat(locale,{timeZone:d.timezone,hour:'2-digit',minute:'2-digit',hourCycle:'h23',timeZoneName:'shortOffset'}).format(new Date(value));
  const dayLabel=(date:string)=>new Intl.DateTimeFormat(locale,{timeZone:'UTC',year:'numeric',month:'short',day:'numeric',weekday:'short'}).format(new Date(date+'T12:00:00Z'));
  const updated=e('time','',`${l.updated}: ${fullTime(d.updatedAt)}`);updated.dateTime=d.updatedAt;footer.append(source,updated,e('p','',`${d.timezone} · ${t.snapshot}`));root.append(header,toolbar,status,body,footer);
  const teams=new Map(d.teams.map(team=>[team.id,team])),games=[...d.games].sort((a,b)=>timestamp(a.startAt)-timestamp(b.startAt));
  let date=n.type==='sports-schedule'?n.initialDate??'':'',team='initialTeamId'in n?n.initialTeamId??'':'',stage=n.type==='sports-schedule'?n.initialStage??'':'',group=n.type==='sports-standings'?n.initialGroup??'':'',gameId=n.type==='sports-scoreboard'?n.gameId??games.find(g=>g.status==='live')?.id??games[0]?.id??'':'';
  let sortKey:keyof SportsStanding='rank',descending=false;const expanded=new Set<string>();
  const selects=new Map<string,{select:HTMLSelectElement,values:string[]}>();
  const select=(key:string,label:string,choices:{value:string,label:string}[],selected:string)=>{const wrap=e('label','iui-sports-filter'),input=e('select');input.id=id+'-'+key;input.setAttribute('aria-label',label);if(key==='game')input.dataset.sportsGame='';else input.dataset.sportsFilter=key;choices.forEach((o,i)=>{const option=e('option','',o.label);option.value=String(i);input.append(option);});input.value=String(choices.findIndex(o=>o.value===selected));wrap.append(e('span','',label),input);toolbar.append(wrap);selects.set(key,{select:input,values:choices.map(o=>o.value)});};
  if(view==='schedule'){
    const dates=[...new Set([...games.map(g=>dateInZone(g.startAt,d.timezone)),...(date?[date]:[])])].sort();select('date',t.date,[{value:'',label:t.all},...dates.map(value=>({value,label:dayLabel(value)}))],date);
    const stages=[...new Set(games.flatMap(g=>g.stage?[g.stage]:[]))];if(stages.length)select('stage',t.stage,[{value:'',label:t.all},...stages.map(value=>({value,label:value}))],stage);
  }
  if(view==='schedule'||view==='standings')select('team',t.team,[{value:'',label:t.all},...d.teams.map(v=>({value:v.id,label:v.name}))],team);
  if(view==='scoreboard'&&games.length)select('game',t.game,games.map(g=>({value:g.id,label:`${teams.get(g.homeTeam)!.shortName??teams.get(g.homeTeam)!.name} – ${teams.get(g.awayTeam)!.shortName??teams.get(g.awayTeam)!.name} · ${fullTime(g.startAt)}`})),gameId);
  if(view==='standings'){const groups=[...new Set(d.standings?.flatMap(row=>row.group?[row.group]:[])??[])];if(groups.length)select('group',t.group,[{value:'',label:t.all},...groups.map(value=>({value,label:value}))],group);}
  function teamLabel(teamId:string,side?:'home'|'away'){
    const value=teams.get(teamId)!,out=e('div','iui-sports-team'),mark=e('span','iui-sports-monogram',Array.from(value.shortName??value.name).slice(0,2).join(''));mark.setAttribute('aria-hidden','true');mark.dataset.color=value.color??'gray';const name=e('span','iui-sports-name',value.name);out.append(mark,name);if(side)out.append(e('span','iui-sports-side',t[side]));return out;
  }
  function score(value:number|null,teamId:string){const out=e('span','iui-sports-score',value===null?'—':c.display(value));out.setAttribute('aria-label',`${teams.get(teamId)!.name}: ${value===null?t.missing:c.display(value)}`);if(value!==null)out.dataset.rawValue=String(value);else out.dataset.missing='true';return out;}
  function detailTable(caption:string,rows:{label:string,home:string|number|null,away:string|number|null}[],game:SportsGame){const wrap=e('div','iui-sports-table-wrap'),table=e('table');table.append(e('caption','',caption));const head=e('thead'),r=e('tr');for(const text of [caption,teams.get(game.homeTeam)!.name,teams.get(game.awayTeam)!.name]){const th=e('th','',text);th.scope='col';r.append(th);}head.append(r);const tbody=e('tbody');for(const row of rows){const tr=e('tr'),label=e('th','',row.label);label.scope='row';tr.append(label);for(const value of [row.home,row.away]){const td=e('td');c.showValue(td,value===null?l.missing:value);tr.append(td);}tbody.append(tr);}table.append(head,tbody);wrap.append(table);return wrap;}
  function details(game:SportsGame){const out=e('div','iui-sports-game-detail'),time=e('time','iui-caption',fullTime(game.startAt));time.dateTime=game.startAt;out.append(time);if(game.venue)out.append(e('p','',game.venue+(game.neutral?` · ${t.neutral}`:'')));if(game.detail)out.append(e('p','',game.detail));if(game.periodScores?.length)out.append(detailTable(t.period,game.periodScores,game));if(game.tieBreak)out.append(detailTable(game.tieBreak.label,[game.tieBreak],game));if(game.stats?.length)out.append(detailTable(t.stats,game.stats,game));return out;}
  function badge(game:SportsGame){const b=e('span','iui-sports-state',t[game.status]);b.dataset.status=game.status;return b;}
  function gameLine(game:SportsGame){const row=e('details','iui-sports-game');row.dataset.gameId=game.id;row.open=expanded.has(game.id);const summary=e('summary'),meta=e('div','iui-sports-game-meta'),time=e('time','',localClock(game.startAt));time.dateTime=game.startAt;time.title=fullTime(game.startAt);meta.append(time,badge(game));if(game.stage)meta.append(e('span','',game.stage));const versus=e('div','iui-sports-versus');versus.append(teamLabel(game.homeTeam),score(game.homeScore,game.homeTeam),e('span','iui-sports-separator','–'),score(game.awayScore,game.awayTeam),teamLabel(game.awayTeam));summary.append(meta,versus);if(game.period||game.clock)summary.append(e('p','iui-caption',[game.period,game.clock].filter(Boolean).join(' · ')));summary.append(e('span','iui-sports-details-label',t.showDetails));row.append(summary,details(game));return row;}
  function paintSchedule(){const list=games.filter(g=>(!date||dateInZone(g.startAt,d.timezone)===date)&&(!team||g.homeTeam===team||g.awayTeam===team)&&(!stage||g.stage===stage));if(!list.length){body.append(e('p','iui-sports-empty',n.message??t.empty));return;}let previous='';for(const game of list){const day=dateInZone(game.startAt,d.timezone);if(day!==previous){body.append(e('h3','iui-sports-day',dayLabel(day)));previous=day;}body.append(gameLine(game));}}
  function paintScoreboard(){const game=games.find(g=>g.id===gameId);if(!game){body.append(e('p','iui-sports-empty',n.message??l.empty));return;}const board=e('article','iui-sports-board');board.dataset.gameId=game.id;const status=e('div','iui-sports-board-status');status.append(badge(game),e('span','',game.stage??''));const sides=e('div','iui-sports-board-sides');for(const side of ['home','away'] as const){const teamId=side==='home'?game.homeTeam:game.awayTeam,panel=e('div','iui-sports-board-team');panel.append(teamLabel(teamId,side),score(side==='home'?game.homeScore:game.awayScore,teamId));if(game.winnerTeamId===teamId)panel.append(e('strong','iui-sports-winner',t.winner));sides.append(panel);}board.append(status,sides);if(game.period||game.clock)board.append(e('p','iui-sports-clock',[game.period,game.clock].filter(Boolean).join(' · ')));board.append(details(game));body.append(board);}
  function paintStandings(){const rows=(d.standings??[]).map((row,index)=>({row,index})).filter(({row})=>(!team||row.teamId===team)&&(!group||row.group===group));if(!rows.length){body.append(e('p','iui-sports-empty',n.message??t.noStandings));return;}
    rows.sort((a,b)=>{const av=a.row[sortKey],bv=b.row[sortKey];if(av===null||av===undefined)return bv===null||bv===undefined?a.index-b.index:1;if(bv===null||bv===undefined)return-1;const result=typeof av==='number'&&typeof bv==='number'?(av===bv?0:av<bv?-1:1):String(av).localeCompare(String(bv),locale);return(descending?-result:result)||a.index-b.index;});
    const wrap=e('div','iui-sports-table-wrap');wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label',t.standings);const table=e('table','iui-sports-standing-table');table.dataset.sportsTable='';table.append(e('caption','',t.providedRank));const head=e('thead'),tr=e('tr');
    const columns:('team'|keyof SportsStanding)[]=['rank','team',...(d.standings?.some(r=>r.group)?['group' as const]:[]),'played','won','drawn','lost','points',...(d.standings?.some(r=>r.for!==undefined)?['for' as const]:[]),...(d.standings?.some(r=>r.against!==undefined)?['against' as const]:[]),...(d.standings?.some(r=>r.note)?['note' as const]:[])];
    for(const key of columns){const th=e('th');th.scope='col';const label=t[key as keyof typeof t]??key;if(!['team','group','note'].includes(key)){const button=e('button','iui-sports-sort',label);button.type='button';button.dataset.sortKey=key;button.setAttribute('aria-label',`${t.sort}: ${label}`);th.setAttribute('aria-sort',sortKey===key?(descending?'descending':'ascending'):'none');th.append(button);}else th.textContent=label;tr.append(th);}head.append(tr);const tbody=e('tbody');for(const{row}of rows){const tr=e('tr');tr.dataset.teamId=row.teamId;for(const key of columns){const cell=e(key==='team'?'th':'td');if(key==='team'){(cell as HTMLTableCellElement).scope='row';cell.append(teamLabel(row.teamId));}else{const value=row[key as keyof SportsStanding];c.showValue(cell,value===null||value===undefined?l.missing:value);}tr.append(cell);}tbody.append(tr);}table.append(head,tbody);wrap.append(table);body.append(wrap);
  }
  const paint=()=>{for(const detail of body.querySelectorAll<HTMLDetailsElement>('details[data-game-id]')){if(detail.open)expanded.add(detail.dataset.gameId!);else expanded.delete(detail.dataset.gameId!);}body.replaceChildren();const mode=n.status??'ready';root.dataset.status=mode;root.setAttribute('aria-busy',String(mode==='loading'));status.textContent=mode==='loading'?n.message??l.loading:mode==='error'?n.message??l.loadError:'';status.setAttribute('role',mode==='error'?'alert':'status');status.hidden=mode==='ready';toolbar.hidden=mode!=='ready';body.hidden=mode!=='ready';if(mode!=='ready')return;if(view==='schedule')paintSchedule();else if(view==='scoreboard')paintScoreboard();else paintStandings();};
  on(root,'change',event=>{const target=event.target as HTMLSelectElement;if(target.tagName!=='SELECT')return;const key=target.hasAttribute('data-sports-game')?'game':target.dataset.sportsFilter;if(!key)return;const control=selects.get(key);const value=control?.values[Number(target.value)];if(value===undefined)return;if(key==='date')date=value;else if(key==='team')team=value;else if(key==='stage')stage=value;else if(key==='group')group=value;else gameId=value;paint();});
  on(root,'click',event=>{const target=(event.target as Element).closest<HTMLButtonElement>('button[data-sort-key]');if(!target||!root.contains(target))return;const key=target.dataset.sortKey as keyof SportsStanding;if(key===sortKey)descending=!descending;else{sortKey=key;descending=key!=='rank';}paint();body.querySelector<HTMLButtonElement>(`button[data-sort-key="${key}"]`)?.focus();});
  c.bind(paint);return root;
}
