/** Generated by scripts/generate-schema.mjs. Edit the generator, not this file. */

export type Value =
  | string
  | number
  | boolean
  | null
  | {
      $: string;
    }
  | {
      op:
        | "add"
        | "sub"
        | "mul"
        | "div"
        | "max"
        | "min"
        | "round"
        | "abs"
        | "clamp"
        | "gt"
        | "lt"
        | "eq"
        | "if"
        | "format";
      /**
       * @minItems 1
       * @maxItems 12
       */
      args: [Value, ...Value[]];
    };
export type Node =
  | TextNode
  | TitleNode
  | CaptionNode
  | MarkdownNode
  | CodeNode
  | MathNode
  | BadgeNode
  | DividerNode
  | SpacerNode
  | LinkNode
  | ImageNode
  | BoxNode
  | CardNode
  | RowNode
  | ColNode
  | GridNode
  | SectionNode
  | FigureNode
  | DetailsNode
  | CarouselNode
  | ListNode
  | TableNode
  | MetricNode
  | MetricGridNode
  | StepsNode
  | CalloutNode
  | SliderNode
  | ToggleNode
  | SelectNode
  | ButtonNode
  | TopologyNode
  | ChartNode
  | SvgNode
  | NativeNode;

/**
 * The project-defined iui/1 wire contract. Semantic validation additionally enforces safe expressions, data and URLs. Native nodes are recognized but unsupported by the portable renderer.
 */
export interface IUIDocument {
  version: "iui/1";
  title?: string;
  description?: string;
  theme?: "auto" | "light" | "dark";
  state?: {
    [k: string]: string | number | boolean;
  };
  computed?: {
    [k: string]: Value;
  };
  /**
   * @minItems 1
   * @maxItems 150
   */
  body: [Node, ...Node[]];
}
export interface TextNode {
  type: "text";
  id?: string;
  value: Value;
  color?: "default" | "secondary" | "tertiary" | "success" | "warning" | "danger" | "info" | "accent";
  weight?: "normal" | "medium" | "semibold" | "bold";
  align?: "start" | "center" | "end";
}
export interface TitleNode {
  type: "title";
  id?: string;
  value: Value;
  color?: "default" | "secondary" | "tertiary" | "success" | "warning" | "danger" | "info" | "accent";
  weight?: "normal" | "medium" | "semibold" | "bold";
  align?: "start" | "center" | "end";
  level?: number;
}
export interface CaptionNode {
  type: "caption";
  id?: string;
  value: Value;
  color?: "default" | "secondary" | "tertiary" | "success" | "warning" | "danger" | "info" | "accent";
  weight?: "normal" | "medium" | "semibold" | "bold";
  align?: "start" | "center" | "end";
}
export interface MarkdownNode {
  type: "markdown";
  id?: string;
  value: string;
}
export interface CodeNode {
  type: "code";
  id?: string;
  value: string;
  language?: string;
}
export interface MathNode {
  type: "math";
  id?: string;
  latex: string;
  block?: boolean;
}
export interface BadgeNode {
  type: "badge";
  id?: string;
  value: Value;
  color?: "default" | "secondary" | "tertiary" | "success" | "warning" | "danger" | "info" | "accent";
}
export interface DividerNode {
  type: "divider";
  id?: string;
}
export interface SpacerNode {
  type: "spacer";
  id?: string;
  height?: number;
}
export interface LinkNode {
  type: "link";
  id?: string;
  value: Value;
  href: string;
}
export interface ImageNode {
  type: "image";
  id?: string;
  src: string;
  alt: string;
  aspectRatio?: "1:1" | "4:3" | "16:9" | "3:4";
  fit?: "cover" | "contain";
}
export interface BoxNode {
  type: "box";
  id?: string;
  gap?: number;
  padding?: number;
  radius?: "none" | "sm" | "md" | "lg" | "xl" | "2xl";
  border?: boolean;
  background?:
    "none" | "surface" | "surface-secondary" | "surface-tertiary" | "success-soft" | "danger-soft" | "info-soft";
  align?: "start" | "center" | "end" | "stretch";
  justify?: "start" | "center" | "end" | "between" | "around";
  width?: number | ("100%" | "auto");
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
}
export interface CardNode {
  type: "card";
  id?: string;
  gap?: number;
  padding?: number;
  radius?: "none" | "sm" | "md" | "lg" | "xl" | "2xl";
  border?: boolean;
  background?:
    "none" | "surface" | "surface-secondary" | "surface-tertiary" | "success-soft" | "danger-soft" | "info-soft";
  align?: "start" | "center" | "end" | "stretch";
  justify?: "start" | "center" | "end" | "between" | "around";
  width?: number | ("100%" | "auto");
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
}
export interface RowNode {
  type: "row";
  id?: string;
  gap?: number;
  padding?: number;
  radius?: "none" | "sm" | "md" | "lg" | "xl" | "2xl";
  border?: boolean;
  background?:
    "none" | "surface" | "surface-secondary" | "surface-tertiary" | "success-soft" | "danger-soft" | "info-soft";
  align?: "start" | "center" | "end" | "stretch";
  justify?: "start" | "center" | "end" | "between" | "around";
  width?: number | ("100%" | "auto");
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
}
export interface ColNode {
  type: "col";
  id?: string;
  gap?: number;
  padding?: number;
  radius?: "none" | "sm" | "md" | "lg" | "xl" | "2xl";
  border?: boolean;
  background?:
    "none" | "surface" | "surface-secondary" | "surface-tertiary" | "success-soft" | "danger-soft" | "info-soft";
  align?: "start" | "center" | "end" | "stretch";
  justify?: "start" | "center" | "end" | "between" | "around";
  width?: number | ("100%" | "auto");
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
}
export interface GridNode {
  type: "grid";
  id?: string;
  gap?: number;
  padding?: number;
  radius?: "none" | "sm" | "md" | "lg" | "xl" | "2xl";
  border?: boolean;
  background?:
    "none" | "surface" | "surface-secondary" | "surface-tertiary" | "success-soft" | "danger-soft" | "info-soft";
  align?: "start" | "center" | "end" | "stretch";
  justify?: "start" | "center" | "end" | "between" | "around";
  width?: number | ("100%" | "auto");
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
  columns?: number;
}
export interface SectionNode {
  type: "section";
  id?: string;
  heading?: string;
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
}
export interface FigureNode {
  type: "figure";
  id?: string;
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
  caption?: string;
}
export interface DetailsNode {
  type: "details";
  id?: string;
  summary: string;
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
}
export interface CarouselNode {
  type: "carousel";
  id?: string;
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
}
export interface ListNode {
  type: "list";
  id?: string;
  ordered?: boolean;
  /**
   * @minItems 0
   * @maxItems 100
   */
  items: (Value | Node)[];
}
export interface TableNode {
  type: "table";
  id?: string;
  /**
   * @minItems 1
   * @maxItems 20
   */
  columns: [string, ...string[]];
  /**
   * @minItems 0
   * @maxItems 200
   */
  rows: Value[][];
  caption?: string;
}
export interface MetricNode {
  type: "metric";
  id?: string;
  label: string;
  value: Value;
  unit?: string;
  hint?: string;
  precision?: number;
  color?: "default" | "secondary" | "tertiary" | "success" | "warning" | "danger" | "info" | "accent";
}
export interface MetricGridNode {
  type: "metric-grid";
  id?: string;
  /**
   * @minItems 1
   * @maxItems 12
   */
  children: [Node, ...Node[]];
  columns?: number;
}
export interface StepsNode {
  type: "steps";
  id?: string;
  /**
   * @minItems 1
   * @maxItems 20
   */
  items: [
    {
      title: string;
      detail?: string;
      latex?: string;
    },
    ...{
      title: string;
      detail?: string;
      latex?: string;
    }[]
  ];
}
export interface CalloutNode {
  type: "callout";
  id?: string;
  value: string;
  tone?: "neutral" | "info" | "caution";
}
export interface SliderNode {
  type: "slider";
  id?: string;
  label: string;
  bind: string;
  min: number;
  max: number;
  step: number;
  unit?: string;
  /**
   * @minItems 0
   * @maxItems 30
   */
  marks?: {
    value: number;
    label: string;
  }[];
}
export interface ToggleNode {
  type: "toggle";
  id?: string;
  label: string;
  bind: string;
}
export interface SelectNode {
  type: "select";
  id?: string;
  label: string;
  bind: string;
  /**
   * @minItems 1
   * @maxItems 40
   */
  options: [
    {
      value: string | number;
      label: string;
    },
    ...{
      value: string | number;
      label: string;
    }[]
  ];
}
export interface ButtonNode {
  type: "button";
  id?: string;
  label: string;
  action: {
    kind: "reset" | "set";
    bind?: string;
    value?: string | number | boolean;
  };
}
export interface TopologyNode {
  type: "topology";
  id?: string;
  /**
   * @minItems 2
   * @maxItems 24
   */
  nodes: [
    {
      id: string;
      label: string;
      subtitle?: string;
    },
    {
      id: string;
      label: string;
      subtitle?: string;
    },
    ...{
      id: string;
      label: string;
      subtitle?: string;
    }[]
  ];
  /**
   * @minItems 1
   * @maxItems 40
   */
  links: [
    {
      from: string;
      to: string;
      label?: string;
      load?: Value;
    },
    ...{
      from: string;
      to: string;
      label?: string;
      load?: Value;
    }[]
  ];
  highlight?: "max-load" | "none";
  caption?: string;
}
export interface ChartNode {
  type: "chart";
  id?: string;
  kind: "line" | "bar";
  xKey: string;
  /**
   * @minItems 1
   * @maxItems 300
   */
  data: [
    {
      [k: string]: Value;
    },
    ...{
      [k: string]: Value;
    }[]
  ];
  /**
   * @minItems 1
   * @maxItems 6
   */
  series: [
    {
      key: string;
      label: string;
      color?: "blue" | "green" | "orange" | "red" | "purple" | "gray";
    },
    ...{
      key: string;
      label: string;
      color?: "blue" | "green" | "orange" | "red" | "purple" | "gray";
    }[]
  ];
  yMin?: number;
  yMax?: number;
  unit?: string;
  title?: string;
  note?: string;
}
export interface SvgNode {
  type: "svg";
  id?: string;
  viewBox: string;
  /**
   * @minItems 1
   * @maxItems 150
   */
  shapes: [
    {
      tag: "rect" | "line" | "circle" | "path" | "text" | "polyline" | "polygon";
      attrs: {
        [k: string]: string | number;
      };
      text?: string;
    },
    ...{
      tag: "rect" | "line" | "circle" | "path" | "text" | "polyline" | "polygon";
      attrs: {
        [k: string]: string | number;
      };
      text?: string;
    }[]
  ];
  label?: string;
}
export interface NativeNode {
  type: "native";
  id?: string;
  name:
    | "box"
    | "row"
    | "col"
    | "grid"
    | "grid-item"
    | "card"
    | "text"
    | "title"
    | "caption"
    | "badge"
    | "divider"
    | "code"
    | "blockquote"
    | "bold"
    | "italic"
    | "underline"
    | "strikethrough"
    | "spacer"
    | "list"
    | "list-item"
    | "table"
    | "table-row"
    | "table-cell"
    | "flow"
    | "flow-item";
  props?: {
    gap?: number;
    padding?: number;
    columns?: number;
    radius?: "none" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "full";
    border?: boolean;
    color?: "default" | "secondary" | "tertiary" | "success" | "warning" | "danger" | "info" | "accent";
    size?: "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    weight?: "normal" | "medium" | "semibold" | "bold";
    align?: "start" | "center" | "end" | "stretch";
    justify?: "start" | "center" | "end" | "between" | "around";
    width?: number | ("100%" | "auto");
    height?: number;
    maxWidth?: number;
    minWidth?: number;
    background?: "surface" | "surface-secondary" | "surface-tertiary" | "none";
    marker?: "bullet" | "number" | "none";
    variant?: "soft" | "solid" | "outline" | "ghost";
    pill?: boolean;
    textAlign?: "start" | "center" | "end";
  };
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
}
