/** Generated by scripts/generate-schema.mjs. Edit the generator, not this file. */

export type Value =
  | string
  | number
  | boolean
  | null
  | {
      $: string;
    }
  | {
      op:
        | "add"
        | "sub"
        | "mul"
        | "div"
        | "max"
        | "min"
        | "round"
        | "abs"
        | "clamp"
        | "gt"
        | "lt"
        | "eq"
        | "if"
        | "format";
      /**
       * @minItems 1
       * @maxItems 12
       */
      args: [Value, ...Value[]];
    };
export type Node =
  | TextNode
  | TitleNode
  | CaptionNode
  | MarkdownNode
  | CodeNode
  | MathNode
  | BadgeNode
  | DividerNode
  | SpacerNode
  | LinkNode
  | ImageNode
  | BoxNode
  | CardNode
  | RowNode
  | ColNode
  | GridNode
  | GridItemNode
  | BlockquoteNode
  | SectionNode
  | FigureNode
  | DetailsNode
  | CarouselNode
  | ListNode
  | TableNode
  | MetricNode
  | MetricGridNode
  | StepsNode
  | CalloutNode
  | SliderNode
  | ToggleNode
  | SelectNode
  | InputNode
  | TextareaNode
  | RadioNode
  | SegmentedNode
  | FieldNode
  | FormNode
  | ButtonNode
  | TopologyNode
  | ChartNode
  | WeatherNode
  | SportsScheduleNode
  | SportsScoreboardNode
  | SportsStandingsNode
  | QuizNode
  | FlashcardsNode
  | FinanceQuoteNode
  | FinanceChartNode
  | FinanceComparisonNode
  | FinanceHeatmapNode
  | UnitConverterNode
  | CurrencyConverterNode
  | SvgNode
  | NativeNode;
export type TextNode = {
  type: "text";
  id?: string;
  value?: Value;
  /**
   * @minItems 1
   * @maxItems 100
   */
  runs?: [TextRun, ...TextRun[]];
  color?: "default" | "secondary" | "tertiary" | "success" | "warning" | "danger" | "info" | "accent";
  weight?: "normal" | "medium" | "semibold" | "bold";
  align?: "start" | "center" | "end";
  italic?: boolean;
  underline?: boolean;
  strike?: boolean;
  shimmer?: boolean;
} & TextNode1;
export type TextNode1 =
  | {
      type?: "text";
      id?: string;
      value: Value;
      /**
       * @minItems 1
       * @maxItems 100
       */
      runs?: [TextRun, ...TextRun[]];
      color?: "default" | "secondary" | "tertiary" | "success" | "warning" | "danger" | "info" | "accent";
      weight?: "normal" | "medium" | "semibold" | "bold";
      align?: "start" | "center" | "end";
      italic?: boolean;
      underline?: boolean;
      strike?: boolean;
      shimmer?: boolean;
    }
  | {
      type?: "text";
      id?: string;
      value?: Value;
      /**
       * @minItems 1
       * @maxItems 100
       */
      runs: [TextRun, ...TextRun[]];
      color?: "default" | "secondary" | "tertiary" | "success" | "warning" | "danger" | "info" | "accent";
      weight?: "normal" | "medium" | "semibold" | "bold";
      align?: "start" | "center" | "end";
      italic?: boolean;
      underline?: boolean;
      strike?: boolean;
      shimmer?: boolean;
    };
export type TableNode = {
  type: "table";
  id?: string;
  /**
   * @minItems 1
   * @maxItems 20
   */
  columns: [string, ...string[]];
  /**
   * @minItems 0
   * @maxItems 200
   */
  rows?: TableCell[][];
  /**
   * @minItems 1
   * @maxItems 12
   */
  sections?: [TableSection, ...TableSection[]];
  caption?: string;
  status?: "ready" | "loading" | "error";
  message?: string;
} & TableNode1;
export type TableCell = Value | TableCellObject;
export type TableNode1 =
  | {
      type?: "table";
      id?: string;
      /**
       * @minItems 1
       * @maxItems 20
       */
      columns?: [string, ...string[]];
      /**
       * @minItems 0
       * @maxItems 200
       */
      rows: TableCell[][];
      /**
       * @minItems 1
       * @maxItems 12
       */
      sections?: [TableSection, ...TableSection[]];
      caption?: string;
      status?: "ready" | "loading" | "error";
      message?: string;
    }
  | {
      type?: "table";
      id?: string;
      /**
       * @minItems 1
       * @maxItems 20
       */
      columns?: [string, ...string[]];
      /**
       * @minItems 0
       * @maxItems 200
       */
      rows?: TableCell[][];
      /**
       * @minItems 1
       * @maxItems 12
       */
      sections: [TableSection, ...TableSection[]];
      caption?: string;
      status?: "ready" | "loading" | "error";
      message?: string;
    };

/**
 * The project-defined iui/1 wire contract. Semantic validation additionally enforces safe expressions, data and URLs. Native nodes are recognized but unsupported by the portable renderer.
 */
export interface IUIDocument {
  version: "iui/1";
  title?: string;
  description?: string;
  theme?: "auto" | "light" | "dark";
  state?: {
    [k: string]: string | number | boolean;
  };
  computed?: {
    [k: string]: Value;
  };
  /**
   * @minItems 1
   * @maxItems 150
   */
  body: [Node, ...Node[]];
}
export interface TextRun {
  value: Value;
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  strike?: boolean;
  code?: boolean;
  href?: string;
}
export interface TitleNode {
  type: "title";
  id?: string;
  value: Value;
  color?: "default" | "secondary" | "tertiary" | "success" | "warning" | "danger" | "info" | "accent";
  weight?: "normal" | "medium" | "semibold" | "bold";
  align?: "start" | "center" | "end";
  italic?: boolean;
  underline?: boolean;
  strike?: boolean;
  shimmer?: boolean;
  level?: number;
}
export interface CaptionNode {
  type: "caption";
  id?: string;
  value: Value;
  color?: "default" | "secondary" | "tertiary" | "success" | "warning" | "danger" | "info" | "accent";
  weight?: "normal" | "medium" | "semibold" | "bold";
  align?: "start" | "center" | "end";
  italic?: boolean;
  underline?: boolean;
  strike?: boolean;
  shimmer?: boolean;
}
export interface MarkdownNode {
  type: "markdown";
  id?: string;
  value: string;
}
export interface CodeNode {
  type: "code";
  id?: string;
  value: string;
  language?: string;
  inline?: boolean;
}
export interface MathNode {
  type: "math";
  id?: string;
  latex: string;
  block?: boolean;
}
export interface BadgeNode {
  type: "badge";
  id?: string;
  value: Value;
  color?: "default" | "secondary" | "tertiary" | "success" | "warning" | "danger" | "info" | "accent";
}
export interface DividerNode {
  type: "divider";
  id?: string;
}
export interface SpacerNode {
  type: "spacer";
  id?: string;
  height?: number;
}
export interface LinkNode {
  type: "link";
  id?: string;
  value: Value;
  href: string;
}
export interface ImageNode {
  type: "image";
  id?: string;
  src: string;
  alt: string;
  aspectRatio?: "1:1" | "4:3" | "16:9" | "3:4";
  fit?: "cover" | "contain";
}
export interface BoxNode {
  type: "box";
  id?: string;
  gap?: number;
  padding?: number;
  radius?: "none" | "sm" | "md" | "lg" | "xl" | "2xl";
  border?: boolean;
  background?:
    "none" | "surface" | "surface-secondary" | "surface-tertiary" | "success-soft" | "danger-soft" | "info-soft";
  align?: "start" | "center" | "end" | "stretch";
  justify?: "start" | "center" | "end" | "between" | "around";
  width?: number | ("100%" | "auto");
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
}
export interface CardNode {
  type: "card";
  id?: string;
  gap?: number;
  padding?: number;
  radius?: "none" | "sm" | "md" | "lg" | "xl" | "2xl";
  border?: boolean;
  background?:
    "none" | "surface" | "surface-secondary" | "surface-tertiary" | "success-soft" | "danger-soft" | "info-soft";
  align?: "start" | "center" | "end" | "stretch";
  justify?: "start" | "center" | "end" | "between" | "around";
  width?: number | ("100%" | "auto");
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
}
export interface RowNode {
  type: "row";
  id?: string;
  gap?: number;
  padding?: number;
  radius?: "none" | "sm" | "md" | "lg" | "xl" | "2xl";
  border?: boolean;
  background?:
    "none" | "surface" | "surface-secondary" | "surface-tertiary" | "success-soft" | "danger-soft" | "info-soft";
  align?: "start" | "center" | "end" | "stretch";
  justify?: "start" | "center" | "end" | "between" | "around";
  width?: number | ("100%" | "auto");
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
}
export interface ColNode {
  type: "col";
  id?: string;
  gap?: number;
  padding?: number;
  radius?: "none" | "sm" | "md" | "lg" | "xl" | "2xl";
  border?: boolean;
  background?:
    "none" | "surface" | "surface-secondary" | "surface-tertiary" | "success-soft" | "danger-soft" | "info-soft";
  align?: "start" | "center" | "end" | "stretch";
  justify?: "start" | "center" | "end" | "between" | "around";
  width?: number | ("100%" | "auto");
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
}
export interface GridNode {
  type: "grid";
  id?: string;
  gap?: number;
  padding?: number;
  radius?: "none" | "sm" | "md" | "lg" | "xl" | "2xl";
  border?: boolean;
  background?:
    "none" | "surface" | "surface-secondary" | "surface-tertiary" | "success-soft" | "danger-soft" | "info-soft";
  align?: "start" | "center" | "end" | "stretch";
  justify?: "start" | "center" | "end" | "between" | "around";
  width?: number | ("100%" | "auto");
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
  columns?: number;
  mobileColumns?: number;
}
export interface GridItemNode {
  type: "grid-item";
  id?: string;
  colSpan?: number;
  rowSpan?: number;
  mobileColSpan?: number;
  /**
   * @minItems 1
   * @maxItems 30
   */
  children: [Node, ...Node[]];
}
export interface BlockquoteNode {
  type: "blockquote";
  id?: string;
  /**
   * @minItems 1
   * @maxItems 30
   */
  children: [Node, ...Node[]];
  attribution?: string;
  cite?: string;
}
export interface SectionNode {
  type: "section";
  id?: string;
  heading?: string;
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
}
export interface FigureNode {
  type: "figure";
  id?: string;
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
  caption?: string;
}
export interface DetailsNode {
  type: "details";
  id?: string;
  summary: string;
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
}
export interface CarouselNode {
  type: "carousel";
  id?: string;
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
}
export interface ListNode {
  type: "list";
  id?: string;
  ordered?: boolean;
  /**
   * @minItems 0
   * @maxItems 100
   */
  items: (Value | Node)[];
}
export interface TableCellObject {
  value: Value;
  rowSpan?: number;
  colSpan?: number;
  header?: boolean;
  scope?: "row" | "col" | "rowgroup";
  align?: "start" | "center" | "end";
}
export interface TableSection {
  kind: "head" | "body" | "foot";
  /**
   * @minItems 0
   * @maxItems 200
   */
  rows: TableCell[][];
}
export interface MetricNode {
  type: "metric";
  id?: string;
  variant?: "plain" | "card";
  label: string;
  value: Value;
  unit?: string;
  hint?: string;
  precision?: number;
  color?: "default" | "secondary" | "tertiary" | "success" | "warning" | "danger" | "info" | "accent";
}
export interface MetricGridNode {
  type: "metric-grid";
  id?: string;
  /**
   * @minItems 1
   * @maxItems 12
   */
  children: [Node, ...Node[]];
  columns?: number;
}
export interface StepsNode {
  type: "steps";
  id?: string;
  /**
   * @minItems 1
   * @maxItems 20
   */
  items: [
    {
      title: string;
      detail?: string;
      latex?: string;
    },
    ...{
      title: string;
      detail?: string;
      latex?: string;
    }[]
  ];
}
export interface CalloutNode {
  type: "callout";
  id?: string;
  value: string;
  tone?: "neutral" | "info" | "caution";
}
export interface SliderNode {
  type: "slider";
  id?: string;
  label: string;
  bind: string;
  min: number;
  max: number;
  step: number;
  unit?: string;
  /**
   * @minItems 0
   * @maxItems 30
   */
  marks?: {
    value: number;
    label: string;
  }[];
}
export interface ToggleNode {
  type: "toggle";
  id?: string;
  label: string;
  bind: string;
}
export interface SelectNode {
  type: "select";
  id?: string;
  label: string;
  bind: string;
  /**
   * @minItems 1
   * @maxItems 40
   */
  options: [
    {
      value: string | number;
      label: string;
    },
    ...{
      value: string | number;
      label: string;
    }[]
  ];
}
export interface InputNode {
  type: "input";
  id?: string;
  label: string;
  bind: string;
  hint?: string;
  error?: Value;
  required?: boolean;
  disabled?: Value;
  kind: "text" | "number" | "email";
  placeholder?: string;
  min?: number;
  max?: number;
  step?: number;
  minLength?: number;
  maxLength?: number;
}
export interface TextareaNode {
  type: "textarea";
  id?: string;
  label: string;
  bind: string;
  hint?: string;
  error?: Value;
  required?: boolean;
  disabled?: Value;
  placeholder?: string;
  rows?: number;
  minLength?: number;
  maxLength?: number;
}
export interface RadioNode {
  type: "radio";
  id?: string;
  label: string;
  bind: string;
  hint?: string;
  error?: Value;
  required?: boolean;
  disabled?: Value;
  /**
   * @minItems 1
   * @maxItems 40
   */
  options: [
    {
      value: string | number;
      label: string;
      disabled?: boolean;
    },
    ...{
      value: string | number;
      label: string;
      disabled?: boolean;
    }[]
  ];
}
export interface SegmentedNode {
  type: "segmented";
  id?: string;
  label: string;
  bind: string;
  hint?: string;
  error?: Value;
  required?: boolean;
  disabled?: Value;
  /**
   * @minItems 1
   * @maxItems 40
   */
  options: [
    {
      value: string | number;
      label: string;
      disabled?: boolean;
    },
    ...{
      value: string | number;
      label: string;
      disabled?: boolean;
    }[]
  ];
}
export interface FieldNode {
  type: "field";
  id?: string;
  label: string;
  hint?: string;
  /**
   * @minItems 1
   * @maxItems 20
   */
  children: [Node, ...Node[]];
  disabled?: Value;
}
export interface FormNode {
  type: "form";
  id?: string;
  label: string;
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
  submitLabel?: string;
  cancelLabel?: string;
  action?: string;
  disabled?: Value;
  successMessage?: string;
  errorMessage?: string;
}
export interface ButtonNode {
  type: "button";
  id?: string;
  label: string;
  action: {
    kind: "reset" | "set";
    bind?: string;
    value?: string | number | boolean;
  };
}
export interface TopologyNode {
  type: "topology";
  id?: string;
  /**
   * @minItems 2
   * @maxItems 24
   */
  nodes: [
    {
      id: string;
      label: string;
      subtitle?: string;
    },
    {
      id: string;
      label: string;
      subtitle?: string;
    },
    ...{
      id: string;
      label: string;
      subtitle?: string;
    }[]
  ];
  /**
   * @minItems 1
   * @maxItems 40
   */
  links: [
    {
      from: string;
      to: string;
      label?: string;
      load?: Value;
    },
    ...{
      from: string;
      to: string;
      label?: string;
      load?: Value;
    }[]
  ];
  highlight?: "max-load" | "none";
  caption?: string;
}
export interface ChartNode {
  type: "chart";
  id?: string;
  kind: "line" | "bar" | "scatter" | "area" | "donut";
  xKey: string;
  xScale?: "category" | "linear" | "time";
  xLabel?: string;
  xMin?: number;
  xMax?: number;
  timezone?: string;
  /**
   * @minItems 0
   * @maxItems 300
   */
  data: {
    [k: string]: Value;
  }[];
  /**
   * @minItems 1
   * @maxItems 6
   */
  series: [
    {
      key: string;
      label: string;
      color?: "blue" | "green" | "orange" | "red" | "purple" | "gray";
    },
    ...{
      key: string;
      label: string;
      color?: "blue" | "green" | "orange" | "red" | "purple" | "gray";
    }[]
  ];
  yMin?: number;
  yMax?: number;
  unit?: string;
  title?: string;
  note?: string;
  status?: "ready" | "loading" | "error";
  message?: string;
}
export interface WeatherNode {
  type: "weather";
  id?: string;
  location: {
    name: string;
    timezone: string;
  };
  updatedAt: string;
  source: {
    label: string;
    url?: string;
    synthetic: boolean;
  };
  units: {
    temperature: "celsius" | "fahrenheit";
  };
  current: {
    time: string;
    temperature: number | null;
    feelsLike?: number | null;
    condition: "clear" | "partly-cloudy" | "cloudy" | "rain" | "snow" | "storm" | "fog" | "unknown";
    humidity?: number | null;
  };
  /**
   * @minItems 0
   * @maxItems 16
   */
  daily: {
    date: string;
    low: number | null;
    high: number | null;
    condition: "clear" | "partly-cloudy" | "cloudy" | "rain" | "snow" | "storm" | "fog" | "unknown";
    precipitationProbability: number | null;
  }[];
  /**
   * @minItems 0
   * @maxItems 384
   */
  hourly: {
    time: string;
    temperature: number | null;
    precipitationProbability: number | null;
  }[];
  initialDate?: string;
  status?: "ready" | "loading" | "error";
  message?: string;
}
export interface SportsScheduleNode {
  type: "sports-schedule";
  id?: string;
  data: SportsData;
  status?: "ready" | "loading" | "error";
  message?: string;
  initialDate?: string;
  initialTeamId?: string;
  initialStage?: string;
}
export interface SportsData {
  league: {
    id: string;
    name: string;
    sport: "football" | "basketball" | "baseball" | "hockey" | "other";
    season?: string;
  };
  timezone: string;
  updatedAt: string;
  source: {
    label: string;
    synthetic: boolean;
    url?: string;
  };
  /**
   * @minItems 0
   * @maxItems 100
   */
  teams: SportsTeam[];
  /**
   * @minItems 0
   * @maxItems 300
   */
  games: SportsGame[];
  /**
   * @minItems 0
   * @maxItems 100
   */
  standings?: SportsStanding[];
}
export interface SportsTeam {
  id: string;
  name: string;
  shortName?: string;
  color?: "blue" | "green" | "orange" | "red" | "purple" | "gray";
}
export interface SportsGame {
  id: string;
  startAt: string;
  homeTeam: string;
  awayTeam: string;
  status: "scheduled" | "live" | "final" | "postponed" | "cancelled";
  homeScore: number | null;
  awayScore: number | null;
  period?: string;
  clock?: string;
  stage?: string;
  venue?: string;
  neutral?: boolean;
  winnerTeamId?: string;
  detail?: string;
  /**
   * @minItems 0
   * @maxItems 30
   */
  periodScores?: {
    label: string;
    home: number | null;
    away: number | null;
  }[];
  tieBreak?: {
    label: string;
    home: number | null;
    away: number | null;
  };
  /**
   * @minItems 0
   * @maxItems 30
   */
  stats?: {
    label: string;
    home: string | number | null;
    away: string | number | null;
  }[];
}
export interface SportsStanding {
  teamId: string;
  group?: string;
  rank: number;
  played: number | null;
  won: number | null;
  drawn: number | null;
  lost: number | null;
  points: number | null;
  for?: number | null;
  against?: number | null;
  note?: string;
}
export interface SportsScoreboardNode {
  type: "sports-scoreboard";
  id?: string;
  data: SportsData;
  status?: "ready" | "loading" | "error";
  message?: string;
  gameId?: string;
}
export interface SportsStandingsNode {
  type: "sports-standings";
  id?: string;
  data: SportsData;
  status?: "ready" | "loading" | "error";
  message?: string;
  initialTeamId?: string;
  initialGroup?: string;
}
export interface QuizNode {
  type: "quiz";
  id?: string;
  title: string;
  description?: string;
  /**
   * @minItems 0
   * @maxItems 100
   */
  questions: QuizQuestion[];
  status?: "ready" | "loading" | "error";
  message?: string;
}
export interface QuizQuestion {
  id: string;
  kind: "single" | "multiple";
  prompt: string;
  latex?: string;
  /**
   * @minItems 2
   * @maxItems 20
   */
  choices: [
    {
      id: string;
      label: string;
    },
    {
      id: string;
      label: string;
    },
    ...{
      id: string;
      label: string;
    }[]
  ];
  /**
   * @minItems 1
   * @maxItems 20
   */
  correct: [string, ...string[]];
  explanation: string;
  explanationLatex?: string;
  points?: number;
}
export interface FlashcardsNode {
  type: "flashcards";
  id?: string;
  title: string;
  description?: string;
  /**
   * @minItems 0
   * @maxItems 100
   */
  cards: Flashcard[];
  status?: "ready" | "loading" | "error";
  message?: string;
}
export interface Flashcard {
  id: string;
  front: string;
  back: string;
  frontLatex?: string;
  backLatex?: string;
  hint?: string;
}
export interface FinanceQuoteNode {
  type: "finance-quote";
  id?: string;
  title?: string;
  source: FinanceSource;
  status?: "ready" | "loading" | "error";
  message?: string;
  instrument: FinanceInstrument;
}
export interface FinanceSource {
  label: string;
  synthetic: boolean;
  url?: string;
}
export interface FinanceInstrument {
  id: string;
  symbol: string;
  name: string;
  currency: string;
  exchange?: string;
  timezone: string;
  asOf: string;
  marketStatus: "open" | "closed" | "pre" | "post" | "halted" | "unknown";
  delayMinutes: number;
  price: number | null;
  previousClose: number | null;
  /**
   * @minItems 0
   * @maxItems 500
   */
  history: {
    time: string;
    price: number | null;
  }[];
}
export interface FinanceChartNode {
  type: "finance-chart";
  id?: string;
  title?: string;
  source: FinanceSource;
  status?: "ready" | "loading" | "error";
  message?: string;
  instrument: FinanceInstrument;
  /**
   * @minItems 0
   * @maxItems 12
   */
  ranges: FinanceRange[];
  initialRange?: string;
}
export interface FinanceRange {
  id: string;
  label: string;
  from: string;
  to: string;
}
export interface FinanceComparisonNode {
  type: "finance-comparison";
  id?: string;
  title?: string;
  source: FinanceSource;
  status?: "ready" | "loading" | "error";
  message?: string;
  /**
   * @minItems 2
   * @maxItems 6
   */
  instruments: [FinanceInstrument, FinanceInstrument, ...FinanceInstrument[]];
  baselineAt: string;
  timezone?: string;
  /**
   * @minItems 0
   * @maxItems 12
   */
  ranges: FinanceRange[];
  initialRange?: string;
}
export interface FinanceHeatmapNode {
  type: "finance-heatmap";
  id?: string;
  title?: string;
  source: FinanceSource;
  asOf: string;
  timezone: string;
  weightLabel: string;
  changeBasis: string;
  /**
   * @minItems 0
   * @maxItems 200
   */
  cells: {
    id: string;
    symbol: string;
    name: string;
    sector: string;
    weight: number | null;
    price: number | null;
    currency: string;
    changePercent: number | null;
    asOf: string;
    marketStatus: "open" | "closed" | "pre" | "post" | "halted" | "unknown";
    delayMinutes: number;
  }[];
  initialSector?: string;
  status?: "ready" | "loading" | "error";
  message?: string;
}
export interface UnitConverterNode {
  type: "unit-converter";
  id?: string;
  title?: string;
  category: "length" | "mass" | "temperature" | "speed" | "area" | "volume" | "time" | "pressure" | "data";
  amount: number;
  /**
   * length: m, cm, mm, km, in, ft, yd, mi, nmi; mass: kg, g, mg, t, lb, oz; temperature: K, C, F; speed: m-s, km-h, ft-s, mph, kn; area: m2, cm2, km2, ft2, ha, acre; volume: L, mL, m3, gal-us, gal-imp; time: s, ms, min, h, d; pressure: Pa, kPa, MPa, bar, atm, psi; data: B, bit, kB, MB, GB, KiB, MiB, GiB
   */
  from:
    | "m"
    | "cm"
    | "mm"
    | "km"
    | "in"
    | "ft"
    | "yd"
    | "mi"
    | "nmi"
    | "kg"
    | "g"
    | "mg"
    | "t"
    | "lb"
    | "oz"
    | "K"
    | "C"
    | "F"
    | "m-s"
    | "km-h"
    | "ft-s"
    | "mph"
    | "kn"
    | "m2"
    | "cm2"
    | "km2"
    | "ft2"
    | "ha"
    | "acre"
    | "L"
    | "mL"
    | "m3"
    | "gal-us"
    | "gal-imp"
    | "s"
    | "ms"
    | "min"
    | "h"
    | "d"
    | "Pa"
    | "kPa"
    | "MPa"
    | "bar"
    | "atm"
    | "psi"
    | "B"
    | "bit"
    | "kB"
    | "MB"
    | "GB"
    | "KiB"
    | "MiB"
    | "GiB";
  /**
   * length: m, cm, mm, km, in, ft, yd, mi, nmi; mass: kg, g, mg, t, lb, oz; temperature: K, C, F; speed: m-s, km-h, ft-s, mph, kn; area: m2, cm2, km2, ft2, ha, acre; volume: L, mL, m3, gal-us, gal-imp; time: s, ms, min, h, d; pressure: Pa, kPa, MPa, bar, atm, psi; data: B, bit, kB, MB, GB, KiB, MiB, GiB
   */
  to:
    | "m"
    | "cm"
    | "mm"
    | "km"
    | "in"
    | "ft"
    | "yd"
    | "mi"
    | "nmi"
    | "kg"
    | "g"
    | "mg"
    | "t"
    | "lb"
    | "oz"
    | "K"
    | "C"
    | "F"
    | "m-s"
    | "km-h"
    | "ft-s"
    | "mph"
    | "kn"
    | "m2"
    | "cm2"
    | "km2"
    | "ft2"
    | "ha"
    | "acre"
    | "L"
    | "mL"
    | "m3"
    | "gal-us"
    | "gal-imp"
    | "s"
    | "ms"
    | "min"
    | "h"
    | "d"
    | "Pa"
    | "kPa"
    | "MPa"
    | "bar"
    | "atm"
    | "psi"
    | "B"
    | "bit"
    | "kB"
    | "MB"
    | "GB"
    | "KiB"
    | "MiB"
    | "GiB";
  /**
   * Maximum significant digits, default 8; raw values are retained.
   */
  precision?: number;
  /**
   * Temperature only. Absolute includes scale offsets and must be >= 0 K; difference converts signed intervals without offsets.
   */
  temperatureMode?: "absolute" | "difference";
}
export interface CurrencyConverterNode {
  type: "currency-converter";
  id?: string;
  title?: string;
  source: FinanceSource;
  asOf: string;
  base: string;
  /**
   * @minItems 0
   * @maxItems 200
   */
  rates: {
    currency: string;
    /**
     * Units of this currency per one base-currency unit; null means unavailable.
     */
    rate: number | null;
  }[];
  amount: number;
  from?: string;
  to?: string;
  precision?: number;
  status?: "ready" | "loading" | "error";
  message?: string;
}
export interface SvgNode {
  type: "svg";
  id?: string;
  viewBox: string;
  /**
   * @minItems 1
   * @maxItems 150
   */
  shapes: [
    {
      tag: "rect" | "line" | "circle" | "path" | "text" | "polyline" | "polygon";
      attrs: {
        [k: string]: string | number;
      };
      text?: string;
    },
    ...{
      tag: "rect" | "line" | "circle" | "path" | "text" | "polyline" | "polygon";
      attrs: {
        [k: string]: string | number;
      };
      text?: string;
    }[]
  ];
  label?: string;
}
export interface NativeNode {
  type: "native";
  id?: string;
  name:
    | "box"
    | "row"
    | "col"
    | "grid"
    | "grid-item"
    | "card"
    | "text"
    | "title"
    | "caption"
    | "badge"
    | "divider"
    | "code"
    | "blockquote"
    | "bold"
    | "italic"
    | "underline"
    | "strikethrough"
    | "spacer"
    | "list"
    | "list-item"
    | "table"
    | "table-row"
    | "table-cell"
    | "flow"
    | "flow-item";
  props?: {
    gap?: number;
    padding?: number;
    columns?: number;
    radius?: "none" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "full";
    border?: boolean;
    color?: "default" | "secondary" | "tertiary" | "success" | "warning" | "danger" | "info" | "accent";
    size?: "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    weight?: "normal" | "medium" | "semibold" | "bold";
    align?: "start" | "center" | "end" | "stretch";
    justify?: "start" | "center" | "end" | "between" | "around";
    width?: number | ("100%" | "auto");
    height?: number;
    maxWidth?: number;
    minWidth?: number;
    background?: "surface" | "surface-secondary" | "surface-tertiary" | "none";
    marker?: "bullet" | "number" | "none";
    variant?: "soft" | "solid" | "outline" | "ghost";
    pill?: boolean;
    textAlign?: "start" | "center" | "end";
  };
  /**
   * @minItems 0
   * @maxItems 500
   */
  children: Node[];
}
